import { MedicalEquipment } from '../types';

export interface EmergencyLoanRecord {
  id: string; // e.g. "LOAN-20260817-001"
  equipmentId: string;
  equipmentName: string;
  equipmentModel: string;
  equipmentSn: string;
  category: string;
  
  // 借用双方
  borrowingDepartment: string; // 借入科室 e.g. "急诊科", "重症医学科", "麻醉手术科"
  borrowerName: string; // 借用人/经办护士/医生
  borrowerPhone: string; // 经办电话
  borrowReason: string; // 借用事由 e.g. "急诊抢救突发群伤应急支持", "病区无创呼吸机临时增援"
  
  // 时间节点
  borrowTime: string; // 借出借用时间 YYYY-MM-DD HH:mm
  expectedReturnTime: string; // 预计归还时间 YYYY-MM-DD HH:mm
  actualReturnTime?: string; // 实际归还时间
  
  // 状态流转
  status: 'borrowed' | 'returned' | 'overdue'; // 借出在用 | 已归还入库 | 超期未还
  
  // 库管与质控核验
  approver: string; // 审批/出库经办人 e.g. "李强 (应急库管员)"
  dispatchLocation: string; // 出库地点 e.g. "医学工程保障中心应急库 1号机架"
  accessoriesIncluded: string[]; // 随附配件清点 e.g. ["电源线", "病人管路", "血氧探头", "转运支架"]
  qualityCheckPassed: boolean; // 出库前质控自检是否合格
  
  // 归还验收
  returnInspector?: string; // 归还验收工程师/库管员
  returnCondition?: 'intact' | 'needs_cleaning' | 'faulty'; // 完好归还 | 需消毒 | 故障报修
  notes?: string;
}

// 应急库初始设备样例（储备于“医疗设备应急库”）
export const INITIAL_EMERGENCY_EQUIPMENT: MedicalEquipment[] = [
  {
    id: 'EMG-1001',
    categoryNo: '08',
    category: '呼吸、麻醉和急救器械',
    level1No: '01',
    level1Category: '呼吸设备',
    level2No: '01',
    level2Category: '治疗呼吸机',
    name: '危重症无创/有创一体化转运呼吸机',
    model: 'SV300 Pro',
    manufactureDate: '2023/5/10',
    enableDate: '2023/6/1',
    productValidity: '10',
    sn: 'MR-SV3-20230501',
    manufacturer: '深圳迈瑞生物医疗电子股份有限公司',
    calibration: 'Yes',
    calibrationType: '强检类',
    catalogueCode: 'QJ-03',
    feePolicy: 'free_national',
    calibrationUnit: '山东省计量科学研究院',
    lastCalibrationDate: '2026-03-15',
    nextCalibrationDate: '2027-03-15',
    calibrationCertificateNo: 'SD-MET-2026-8801',
    department: '医疗设备应急库',
    building: '1号楼 综合楼',
    floor: '1',
    nursePhone: '7991237',
    status: '正常运行',
    manager: '李强 (库管员)',
    location: '1号楼1F医学工程保障中心 应急周转库A-01区',
    imageUrl: 'https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?auto=format&fit=crop&w=320&q=70',
    purchasePrice: 185000,
    repairCount: 0,
    repairRecords: [],
    statusLogs: []
  },
  {
    id: 'EMG-1002',
    categoryNo: '08',
    category: '呼吸、麻醉和急救器械',
    level1No: '01',
    level1Category: '急救转运呼吸机',
    level2No: '02',
    level2Category: '便携式气动电控急救呼吸机',
    name: '便携式急救转运呼吸机',
    model: 'Oxylog 3000 Plus',
    manufactureDate: '2022/8/15',
    enableDate: '2022/9/1',
    productValidity: '10',
    sn: 'DR-OXY-220815',
    manufacturer: '德国德尔格医疗有限公司 (Dräger)',
    calibration: 'Yes',
    calibrationType: '强检类',
    catalogueCode: 'QJ-03',
    feePolicy: 'free_national',
    calibrationUnit: '山东省计量科学研究院',
    lastCalibrationDate: '2026-02-10',
    nextCalibrationDate: '2027-02-10',
    calibrationCertificateNo: 'SD-MET-2026-8802',
    department: '医疗设备应急库',
    building: '1号楼 综合楼',
    floor: '1',
    nursePhone: '7991237',
    status: '正常运行',
    manager: '李强 (库管员)',
    location: '应急周转库A-02区 (带车载气源减压阀)',
    imageUrl: 'https://images.unsplash.com/photo-1516549655169-df83a0774514?auto=format&fit=crop&w=320&q=70',
    purchasePrice: 160000,
    repairCount: 0,
    repairRecords: [],
    statusLogs: []
  },
  {
    id: 'EMG-1003',
    categoryNo: '03',
    category: '医用诊察和监护器械',
    level1No: '04',
    level1Category: '除颤设备',
    level2No: '01',
    level2Category: '双相波除颤起搏监护仪',
    name: '双相波除颤起搏监护仪 (带AED模式)',
    model: 'BeneHeart D6',
    manufactureDate: '2023/2/18',
    enableDate: '2023/3/1',
    productValidity: '10',
    sn: 'MR-D6-20230218',
    manufacturer: '深圳迈瑞生物医疗电子股份有限公司',
    calibration: 'Yes',
    calibrationType: '强检类',
    catalogueCode: 'QJ-04',
    feePolicy: 'free_national',
    calibrationUnit: '山东省计量科学研究院',
    lastCalibrationDate: '2026-04-10',
    nextCalibrationDate: '2027-04-10',
    calibrationCertificateNo: 'SD-MET-2026-8803',
    department: '医疗设备应急库',
    building: '1号楼 综合楼',
    floor: '1',
    nursePhone: '7991237',
    status: '正常运行',
    manager: '李强 (库管员)',
    location: '应急周转库B-01区 (蓄电池满电维护位)',
    imageUrl: 'https://images.unsplash.com/photo-1579684385127-1ef15d508118?auto=format&fit=crop&w=320&q=70',
    purchasePrice: 120000,
    repairCount: 0,
    repairRecords: [],
    statusLogs: []
  },
  {
    id: 'EMG-1004',
    categoryNo: '03',
    category: '医用诊察和监护器械',
    level1No: '04',
    level1Category: '监护设备',
    level2No: '01',
    level2Category: '高档多参数病人监护仪',
    name: '多参数生命体征监护仪 (五导联/IBP/EtCO2)',
    model: 'BeneVision N15',
    manufactureDate: '2023/10/12',
    enableDate: '2023/11/1',
    productValidity: '10',
    sn: 'MR-N15-20231012',
    manufacturer: '深圳迈瑞生物医疗电子股份有限公司',
    calibration: 'Yes',
    calibrationType: '强检类',
    catalogueCode: 'QJ-02',
    feePolicy: 'free_national',
    calibrationUnit: '日照市计量测试所',
    lastCalibrationDate: '2026-05-18',
    nextCalibrationDate: '2027-05-18',
    calibrationCertificateNo: 'RZ-MET-2026-3391',
    department: '医疗设备应急库',
    building: '1号楼 综合楼',
    floor: '1',
    nursePhone: '7991237',
    status: '正常运行',
    manager: '李强 (库管员)',
    location: '应急周转库B-02区',
    imageUrl: 'https://images.unsplash.com/photo-1581594693702-fbdc51b2763b?auto=format&fit=crop&w=320&q=70',
    purchasePrice: 95000,
    repairCount: 0,
    repairRecords: [],
    statusLogs: []
  },
  {
    id: 'EMG-1005',
    categoryNo: '03',
    category: '医用诊察和监护器械',
    level1No: '04',
    level1Category: '监护设备',
    level2No: '01',
    level2Category: '紧凑型转运监护仪',
    name: '便携转运多参数监护仪',
    model: 'BeneVision N1',
    manufactureDate: '2024/1/10',
    enableDate: '2024/2/1',
    productValidity: '10',
    sn: 'MR-N1-20240110',
    manufacturer: '深圳迈瑞生物医疗电子股份有限公司',
    calibration: 'Yes',
    calibrationType: '强检类',
    catalogueCode: 'QJ-02',
    feePolicy: 'free_national',
    calibrationUnit: '日照市计量测试所',
    lastCalibrationDate: '2026-05-18',
    nextCalibrationDate: '2027-05-18',
    calibrationCertificateNo: 'RZ-MET-2026-3392',
    department: '医疗设备应急库',
    building: '1号楼 综合楼',
    floor: '1',
    nursePhone: '7991237',
    status: '正常运行',
    manager: '李强 (库管员)',
    location: '应急周转库B-03区',
    imageUrl: 'https://images.unsplash.com/photo-1551076805-e1869033e561?auto=format&fit=crop&w=320&q=70',
    purchasePrice: 42000,
    repairCount: 0,
    repairRecords: [],
    statusLogs: []
  },
  {
    id: 'EMG-1006',
    categoryNo: '14',
    category: '注输、护理和防护器械',
    level1No: '01',
    level1Category: '注射泵/微量泵',
    level2No: '01',
    level2Category: '高精度双通道微量注射泵',
    name: '双通道智能微量注射泵',
    model: 'BeneFusion SP5 TGA',
    manufactureDate: '2023/7/20',
    enableDate: '2023/8/1',
    productValidity: '8',
    sn: 'MR-SP5-230720',
    manufacturer: '深圳迈瑞生物医疗电子股份有限公司',
    calibration: 'Yes',
    calibrationType: '强检类',
    catalogueCode: 'QJ-05',
    feePolicy: 'free_national',
    calibrationUnit: '日照市计量测试所',
    lastCalibrationDate: '2026-06-12',
    nextCalibrationDate: '2027-06-12',
    calibrationCertificateNo: 'RZ-MET-2026-5512',
    department: '医疗设备应急库',
    building: '1号楼 综合楼',
    floor: '1',
    nursePhone: '7991237',
    status: '正常运行',
    manager: '李强 (库管员)',
    location: '应急周转库C-01区',
    imageUrl: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=320&q=70',
    purchasePrice: 18000,
    repairCount: 0,
    repairRecords: [],
    statusLogs: []
  },
  {
    id: 'EMG-1007',
    categoryNo: '14',
    category: '注输、护理和防护器械',
    level1No: '01',
    level1Category: '输液泵',
    level2No: '01',
    level2Category: '容积式医用输液泵',
    name: '智能容积式输液泵',
    model: 'BeneFusion VP5',
    manufactureDate: '2023/7/20',
    enableDate: '2023/8/1',
    productValidity: '8',
    sn: 'MR-VP5-230721',
    manufacturer: '深圳迈瑞生物医疗电子股份有限公司',
    calibration: 'Yes',
    calibrationType: '强检类',
    catalogueCode: 'QJ-05',
    feePolicy: 'free_national',
    calibrationUnit: '日照市计量测试所',
    lastCalibrationDate: '2026-06-12',
    nextCalibrationDate: '2027-06-12',
    calibrationCertificateNo: 'RZ-MET-2026-5513',
    department: '医疗设备应急库',
    building: '1号楼 综合楼',
    floor: '1',
    nursePhone: '7991237',
    status: '正常运行',
    manager: '李强 (库管员)',
    location: '应急周转库C-02区',
    imageUrl: 'https://images.unsplash.com/photo-1583912267550-d44d95bf0887?auto=format&fit=crop&w=320&q=70',
    purchasePrice: 15000,
    repairCount: 0,
    repairRecords: [],
    statusLogs: []
  },
  {
    id: 'EMG-1008',
    categoryNo: '06',
    category: '医用成像器械',
    level1No: '07',
    level1Category: '超声影像诊断设备',
    level2No: '02',
    level2Category: '便携式彩色超声诊断系统',
    name: '掌上/便携式床旁彩色超声诊断仪 (Point-of-Care US)',
    model: 'M9 Handheld Point-of-Care',
    manufactureDate: '2023/11/05',
    enableDate: '2023/12/01',
    productValidity: '8',
    sn: 'MR-M9-20231105',
    manufacturer: '深圳迈瑞生物医疗电子股份有限公司',
    calibration: 'Yes',
    calibrationType: '强检类',
    catalogueCode: 'QJ-01',
    feePolicy: 'free_national',
    calibrationUnit: '山东省计量科学研究院',
    lastCalibrationDate: '2026-01-20',
    nextCalibrationDate: '2027-01-20',
    calibrationCertificateNo: 'SD-MET-2026-1109',
    department: '医疗设备应急库',
    building: '1号楼 综合楼',
    floor: '1',
    nursePhone: '7991237',
    status: '正常运行',
    manager: '李强 (库管员)',
    location: '应急周转库D-01区 (配凸阵/线阵探头及保护箱)',
    imageUrl: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?auto=format&fit=crop&w=320&q=70',
    purchasePrice: 280000,
    repairCount: 0,
    repairRecords: [],
    statusLogs: []
  },
  {
    id: 'EMG-1009',
    categoryNo: '08',
    category: '呼吸、麻醉和急救器械',
    level1No: '05',
    level1Category: '电动吸引器',
    level2No: '01',
    level2Category: '交直流两用便携式电动吸引器',
    name: '移动式应急电动吸引器 (交直流两用)',
    model: 'DFX-23D.II',
    manufactureDate: '2024/3/01',
    enableDate: '2024/3/15',
    productValidity: '8',
    sn: 'DFX-202403-09',
    manufacturer: '上海达芬医疗器械有限公司',
    calibration: 'No',
    calibrationType: '免计量',
    department: '医疗设备应急库',
    building: '1号楼 综合楼',
    floor: '1',
    nursePhone: '7991237',
    status: '正常运行',
    manager: '李强 (库管员)',
    location: '应急周转库D-02区',
    imageUrl: 'https://images.unsplash.com/photo-1530497610245-94d3c16cda28?auto=format&fit=crop&w=320&q=70',
    purchasePrice: 6800,
    repairCount: 0,
    repairRecords: [],
    statusLogs: []
  },
  {
    id: 'EMG-1010',
    categoryNo: '14',
    category: '注输、护理和防护器械',
    level1No: '05',
    level1Category: '降温/控温设备',
    level2No: '01',
    level2Category: '医用控温毯/控温帽',
    name: '全自动医用升降温控温毯 (亚低温治疗仪)',
    model: 'HGT-200 Pro',
    manufactureDate: '2023/8/10',
    enableDate: '2023/9/01',
    productValidity: '8',
    sn: 'HGT-202308-11',
    manufacturer: '珠海和佳医疗设备股份有限公司',
    calibration: 'Yes',
    calibrationType: '定期校准(自费)',
    department: '医疗设备应急库',
    building: '1号楼 综合楼',
    floor: '1',
    nursePhone: '7991237',
    status: '正常运行',
    manager: '李强 (库管员)',
    location: '应急周转库E-01区',
    purchasePrice: 48000,
    repairCount: 0,
    repairRecords: [],
    statusLogs: []
  }
];

// 初始已发生的应急借调流转历史 (含长期借用、超期未还与正常在用样例)
export const INITIAL_EMERGENCY_LOANS: EmergencyLoanRecord[] = [
  {
    id: 'LOAN-20260728-008',
    equipmentId: 'EMG-1002',
    equipmentName: '便携式急救转运呼吸机',
    equipmentModel: 'Oxylog 3000 Plus',
    equipmentSn: 'DR-OXY-220815',
    category: '呼吸、麻醉和急救器械',
    borrowingDepartment: '重症医学科',
    borrowerName: '张雪梅 (护士长)',
    borrowerPhone: '7991278',
    borrowReason: 'ICU扩增重症隔离床位，急需转运呼吸机维持呼吸衰竭病患床旁与外出CT转运',
    borrowTime: '2026-07-28 10:20',
    expectedReturnTime: '2026-08-04 18:00',
    status: 'borrowed',
    approver: '李强 (库管员)',
    dispatchLocation: '应急周转库A-02区',
    accessoriesIncluded: ['车载氧气减压阀x1', '可重复消毒管路x2', '便携挂架', '专用锂电池x2'],
    qualityCheckPassed: true,
    notes: '【严重超期】借调已达20天，已超过预计归还时间13天，ICU常态化占用中，需督促归还或申请科室新增配置。'
  },
  {
    id: 'LOAN-20260802-005',
    equipmentId: 'EMG-1010',
    equipmentName: '全自动医用升降温控温毯 (亚低温治疗仪)',
    equipmentModel: 'HGT-200 Pro',
    equipmentSn: 'HGT-202308-11',
    category: '注输、护理和防护器械',
    borrowingDepartment: '重症医学科',
    borrowerName: '刘医生 (主治医师)',
    borrowerPhone: '7991280',
    borrowReason: '心肺复苏术后 (ROSC) 脑复苏患者持续目标温度管理 (TTM 33-36℃) 治疗',
    borrowTime: '2026-08-02 16:40',
    expectedReturnTime: '2026-08-08 12:00',
    status: 'borrowed',
    approver: '李强 (库管员)',
    dispatchLocation: '应急周转库E-01区',
    accessoriesIncluded: ['水毯体垫x2', '体温传感器探头x1', '连接水管x2', '专用防冻液加注器'],
    qualityCheckPassed: true,
    notes: '【超期借调】借调已达15天，ICU脑复苏患者密集使用，存在长期以借代配倾向。'
  },
  {
    id: 'LOAN-20260801-004',
    equipmentId: 'EMG-1007',
    equipmentName: '智能容积式输液泵',
    equipmentModel: 'BeneFusion VP5',
    equipmentSn: 'MR-VP5-230721',
    category: '注输、护理和防护器械',
    borrowingDepartment: '急诊科',
    borrowerName: '王护士长',
    borrowerPhone: '7991065',
    borrowReason: '急诊EICU与抢救室微量血管活性药物及高危化疗药品精准匀速给药通道不足',
    borrowTime: '2026-08-01 09:10',
    expectedReturnTime: '2026-08-08 18:00',
    status: 'borrowed',
    approver: '李强 (库管员)',
    dispatchLocation: '应急周转库C-02区',
    accessoriesIncluded: ['快装固定夹x1', '电源线x1', '滴速传感器x1'],
    qualityCheckPassed: true,
    notes: '【长期占用】急诊抢救室连续使用超16天，高危药物输注常态化负荷高。'
  },
  {
    id: 'LOAN-20260815-001',
    equipmentId: 'EMG-1001',
    equipmentName: '危重症无创/有创一体化转运呼吸机',
    equipmentModel: 'SV300 Pro',
    equipmentSn: 'MR-SV3-20230501',
    category: '呼吸、麻醉和急救器械',
    borrowingDepartment: '急诊科',
    borrowerName: '王护士长',
    borrowerPhone: '7991065',
    borrowReason: '急诊抢救室突发批量重度呼吸衰竭患者，原配呼吸机满负荷紧急借用',
    borrowTime: '2026-08-15 14:30',
    expectedReturnTime: '2026-08-18 18:00',
    status: 'borrowed',
    approver: '李强 (库管员)',
    dispatchLocation: '应急周转库A-01区',
    accessoriesIncluded: ['成人重复用管路x2', '高压氧气管x1', '电源线x1', '转运专用支架'],
    qualityCheckPassed: true,
    notes: '出库前自检气路密闭性良好，锂电池满电。'
  },
  {
    id: 'LOAN-20260810-006',
    equipmentId: 'EMG-1009',
    equipmentName: '移动式应急电动吸引器 (交直流两用)',
    equipmentModel: 'DFX-23D.II',
    equipmentSn: 'DFX-202403-09',
    category: '呼吸、麻醉和急救器械',
    borrowingDepartment: '呼吸与危重症医学科',
    borrowerName: '陈建华 (副主任医师)',
    borrowerPhone: '7991312',
    borrowReason: '呼吸病区多名重症卧床排痰障碍患者床旁应急气道清理',
    borrowTime: '2026-08-10 11:30',
    expectedReturnTime: '2026-08-17 18:00',
    status: 'borrowed',
    approver: '李强 (库管员)',
    dispatchLocation: '应急周转库D-02区',
    accessoriesIncluded: ['储液瓶x2', '吸痰导管接头x3', '交直流电源线x1'],
    qualityCheckPassed: true,
    notes: '借用7天，已临近归还节点。'
  },
  {
    id: 'LOAN-20260816-003',
    equipmentId: 'EMG-1008',
    equipmentName: '掌上/便携式床旁彩色超声诊断仪 (Point-of-Care US)',
    equipmentModel: 'M9 Handheld Point-of-Care',
    equipmentSn: 'MR-M9-20231105',
    category: '医用成像器械',
    borrowingDepartment: '重症医学科',
    borrowerName: '张雪梅 (护士长)',
    borrowerPhone: '7991278',
    borrowReason: 'ICU多名重症休克患者床旁心肺血流动力学FAST快速评估',
    borrowTime: '2026-08-16 09:15',
    expectedReturnTime: '2026-08-19 18:00',
    status: 'borrowed',
    approver: '李强 (库管员)',
    dispatchLocation: '应急周转库D-01区',
    accessoriesIncluded: ['心脏相控阵探头', '腹部凸阵探头', '专用保护铝箱', '电源适配器'],
    qualityCheckPassed: true,
    notes: '出库前图像清晰度及探头声透透镜完好。'
  },
  {
    id: 'LOAN-20260814-002',
    equipmentId: 'EMG-1003',
    equipmentName: '双相波除颤起搏监护仪 (带AED模式)',
    equipmentModel: 'BeneHeart D6',
    equipmentSn: 'MR-D6-20230218',
    category: '医用诊察和监护器械',
    borrowingDepartment: '麻醉手术科',
    borrowerName: '赵秀兰 (护士长)',
    borrowerPhone: '7991103',
    borrowReason: '手术5间急诊复合伤手术需多台除颤仪双机备用保障',
    borrowTime: '2026-08-14 08:30',
    expectedReturnTime: '2026-08-16 12:00',
    actualReturnTime: '2026-08-16 11:40',
    status: 'returned',
    approver: '李强 (库管员)',
    dispatchLocation: '应急周转库B-01区',
    accessoriesIncluded: ['除颤电极板一套', '心电导联线x1', '电源线x1'],
    qualityCheckPassed: true,
    returnInspector: '崔工 (维修工程师)',
    returnCondition: 'intact',
    notes: '已完成终末消毒与机内核检，已回库充电备用。'
  },
  {
    id: 'LOAN-20260812-007',
    equipmentId: 'EMG-1006',
    equipmentName: '双通道智能微量注射泵',
    equipmentModel: 'BeneFusion SP5 TGA',
    equipmentSn: 'MR-SP5-230720',
    category: '注输、护理和防护器械',
    borrowingDepartment: '内分泌风湿肾病科',
    borrowerName: '林瑞芳 (护士长)',
    borrowerPhone: '13863371002',
    borrowReason: '内分泌病区重症糖尿病酮症酸中毒 (DKA) 及高渗高血糖状态患者小剂量胰岛素持续微量泵入精准控糖',
    borrowTime: '2026-08-12 10:15',
    expectedReturnTime: '2026-08-19 18:00',
    status: 'borrowed',
    approver: '李强 (库管员)',
    dispatchLocation: '应急周转库C-01区',
    accessoriesIncluded: ['双通道固定架x1', '专用电源线x1', '微量泵连接管卡扣x2'],
    qualityCheckPassed: true,
    notes: '内分泌风湿肾病科重症病患胰岛素持续恒速输注在用，运行良好。'
  },
  {
    id: 'LOAN-20260715-010',
    equipmentId: 'EMG-1005',
    equipmentName: '便携转运多参数监护仪',
    equipmentModel: 'BeneVision N1',
    equipmentSn: 'MR-N1-20240110',
    category: '医用诊察和监护器械',
    borrowingDepartment: '内分泌风湿肾病科',
    borrowerName: '林瑞芳 (护士长)',
    borrowerPhone: '13863371002',
    borrowReason: '风湿免疫重症狼疮脑病伴多脏器功能损伤危重患者床旁生命体征连续监护',
    borrowTime: '2026-07-15 08:30',
    expectedReturnTime: '2026-07-22 18:00',
    actualReturnTime: '2026-07-22 16:40',
    status: 'returned',
    approver: '李强 (库管员)',
    dispatchLocation: '应急周转库B-03区',
    accessoriesIncluded: ['5导联心电电缆x1', '血氧指夹探头x1', '无创血压袖带x1', '电源线x1'],
    qualityCheckPassed: true,
    returnInspector: '崔工 (维修工程师)',
    returnCondition: 'intact',
    notes: '已完好归还入库，自检与终末消毒合格。'
  },
  {
    id: 'LOAN-20260720-009',
    equipmentId: 'EMG-1004',
    equipmentName: '高精度遥测多参数患者监护仪',
    equipmentModel: 'BeneVision N12',
    equipmentSn: 'MR-N12-20230304',
    category: '医用诊察和监护器械',
    borrowingDepartment: '心血管内科 (CCU)',
    borrowerName: '孙主任',
    borrowerPhone: '7991155',
    borrowReason: 'CCU急性心肌梗死溶栓术后持续恶性心律失常监护临时增援',
    borrowTime: '2026-07-20 14:00',
    expectedReturnTime: '2026-07-25 18:00',
    actualReturnTime: '2026-07-25 16:30',
    status: 'returned',
    approver: '李强 (库管员)',
    dispatchLocation: '应急周转库B-02区',
    accessoriesIncluded: ['5导联心电电缆x1', '血氧指夹探头x1', '无创血压袖带x2', '电源线x1'],
    qualityCheckPassed: true,
    returnInspector: '崔工 (维修工程师)',
    returnCondition: 'intact',
    notes: '按期完好归还，已质控自检合格上架。'
  }
];

export const EMERGENCY_LOAN_STORAGE_KEY = 'hospital_emergency_loan_records_v1';

export function loadEmergencyLoans(): EmergencyLoanRecord[] {
  try {
    const saved = localStorage.getItem(EMERGENCY_LOAN_STORAGE_KEY);
    if (saved) {
      const parsed = JSON.parse(saved);
      if (Array.isArray(parsed) && parsed.length > 0) {
        // 自动补充合并科室借调样例
        const existingIds = new Set(parsed.map(r => r.id));
        const missing = INITIAL_EMERGENCY_LOANS.filter(r => !existingIds.has(r.id));
        if (missing.length > 0) {
          const merged = [...missing, ...parsed];
          saveEmergencyLoans(merged);
          return merged;
        }
        return parsed;
      }
    }
  } catch (err) {
    console.warn('Failed to load emergency loans from localStorage', err);
  }
  return INITIAL_EMERGENCY_LOANS;
}

export function saveEmergencyLoans(records: EmergencyLoanRecord[]) {
  try {
    localStorage.setItem(EMERGENCY_LOAN_STORAGE_KEY, JSON.stringify(records));
  } catch (err) {
    console.warn('Failed to save emergency loans to localStorage', err);
  }
}
