import { CampusMaster, BuildingMaster, LocationRoomMaster, DepartmentMaster, StaffPersonMaster, MedicalEquipment } from '../types';
import { DEFAULT_WORKPLACES } from './workplacesData';

// ==================== 1. 默认院区/医院主数据 (Campuses) ====================
export const DEFAULT_CAMPUSES: CampusMaster[] = [
  {
    id: 'CAMPUS-01',
    code: 'WL-HOSP',
    name: '五莲县人民医院',
    shortName: '县人医 (总院)',
    address: '山东省日照市五莲县幸福路中段',
    contactPhone: '0633-7991000',
    description: '集医疗、急救、教学、科研、康复于一体的二级甲等综合性公立医院，设综合楼、原内科楼、原妇幼楼、急救站等',
    status: 'active'
  },
  {
    id: 'CAMPUS-02',
    code: 'WL-DERM',
    name: '五莲县皮肤病医院',
    shortName: '皮肤病医院',
    address: '山东省日照市五莲县城关路',
    contactPhone: '0633-7961100',
    description: '专科医疗机构，设皮肤病门诊、病房、中医科病房、国医堂、医学美容科等',
    status: 'active'
  }
];

// ==================== 2. 默认实体楼宇主数据 (Buildings) ====================
export const DEFAULT_BUILDINGS: BuildingMaster[] = [
  {
    id: 'BLD-01',
    campusId: 'CAMPUS-01',
    campusName: '五莲县人民医院',
    code: '1号楼',
    name: '1号楼 综合楼',
    floors: ['-1F', '1F', '2F', '3F', '4F', '5F', '6F', '7F', '8F', '9F', '10F', '11F', '12F', '13F', '14F', '15F', '16F'],
    description: '核心综合医疗大楼：含内外科临床病区(10-16F)、产房与妇科(9F)、麻醉手术科(8F)、ICU与神经外科(7F)、创伤与血透(6F)、儿科与药剂(5F)、五官眼口腔(4F)、医技检验超声(3F)、门诊(2F)、急诊与医保收费(1F)、介入放射与影像中心(-1F)',
    status: 'active'
  },
  {
    id: 'BLD-02',
    campusId: 'CAMPUS-01',
    campusName: '五莲县人民医院',
    code: '2号楼',
    name: '2号楼 原内科楼',
    floors: ['2F', '3F'],
    description: '老年康复科 (2F)、康复医学科 (3F)',
    status: 'active'
  },
  {
    id: 'BLD-03',
    campusId: 'CAMPUS-01',
    campusName: '五莲县人民医院',
    code: '3号楼',
    name: '3号楼 原妇幼楼',
    floors: ['-1F', '1F', '2F', '3F', '4F'],
    description: '消毒供应室(-1F)、放疗科与母婴保健(1F)、健康服务与司法鉴定(2F)、中医科/理疗科/临床营养(3F)、综合保健科(4F)',
    status: 'active'
  },
  {
    id: 'BLD-04',
    campusId: 'CAMPUS-01',
    campusName: '五莲县人民医院',
    code: '4号楼',
    name: '4号楼 急救站',
    floors: ['1F'],
    description: '120 急救指挥与院前急救站 (1F)',
    status: 'active'
  },
  {
    id: 'BLD-05',
    campusId: 'CAMPUS-01',
    campusName: '五莲县人民医院',
    code: '5号楼',
    name: '5号楼 感染性疾病科',
    floors: ['2F'],
    description: '感染性疾病病区与发热门诊 (2F)',
    status: 'active'
  },
  {
    id: 'BLD-06',
    campusId: 'CAMPUS-01',
    campusName: '五莲县人民医院',
    code: '6号楼',
    name: '6号楼 办公楼',
    floors: ['0F', '1F', '2F', '3F'],
    description: '科教科与老干部活动(0F)、医疗设备科/财务/医务/护理/院感/后勤/安保(1F)、院办/人事/审计/绩效(2F)、宣教/作风办(3F)',
    status: 'active'
  },
  {
    id: 'BLD-07',
    campusId: 'CAMPUS-01',
    campusName: '五莲县人民医院',
    code: '0光明路',
    name: '0光明路',
    floors: ['1F'],
    description: '光明路外设门诊 (1F)',
    status: 'active'
  },
  {
    id: 'BLD-08',
    campusId: 'CAMPUS-01',
    campusName: '五莲县人民医院',
    code: '0公用',
    name: '0公用设施',
    floors: ['0F'],
    description: '全院公用工程、能源动力与特殊预设设施',
    status: 'active'
  },
  {
    id: 'BLD-DERM-01',
    campusId: 'CAMPUS-02',
    campusName: '五莲县皮肤病医院',
    code: '门诊楼',
    name: '0皮肤病医院门诊楼',
    floors: ['1F', '2F'],
    description: '皮肤病门诊/美容/国医堂/检验/药房/收款(1F)、皮肤病病房/中医病房/专家门诊/院长室/财务/办公室(2F)',
    status: 'active'
  }
];

// ==================== 3. 完整科室主数据 (98个标准化科室) ====================
export const DEFAULT_DEPARTMENTS: DepartmentMaster[] = [
  // 1号楼 16F
  {
    id: '254',
    code: 'DEP-254',
    name: '内分泌风湿肾病科',
    hospitalName: '五莲县人民医院',
    disciplineCategory: '内科科',
    category: '临床病区',
    functionType: '临床病区',
    campusId: 'CAMPUS-01',
    campusName: '五莲县人民医院',
    buildingId: 'BLD-01',
    buildingName: '1号楼 综合楼',
    defaultFloor: '16F',
    nursePhone: '7991438',
    adverseEventReporting: true,
    emergencyDeployment: true,
    defaultManager: '崔伟',
    status: 'active'
  },
  {
    id: '253',
    code: 'DEP-253',
    name: '消化保健科',
    hospitalName: '五莲县人民医院',
    disciplineCategory: '内科科',
    category: '临床病区',
    functionType: '临床病区',
    campusId: 'CAMPUS-01',
    campusName: '五莲县人民医院',
    buildingId: 'BLD-01',
    buildingName: '1号楼 综合楼',
    defaultFloor: '16F',
    nursePhone: '7991038',
    adverseEventReporting: true,
    emergencyDeployment: true,
    defaultManager: '崔伟',
    status: 'active'
  },

  // 1号楼 15F
  {
    id: '256',
    code: 'DEP-256',
    name: '神经内二科',
    hospitalName: '五莲县人民医院',
    disciplineCategory: '内科科',
    category: '临床病区',
    functionType: '临床病区',
    campusId: 'CAMPUS-01',
    campusName: '五莲县人民医院',
    buildingId: 'BLD-01',
    buildingName: '1号楼 综合楼',
    defaultFloor: '15F',
    nursePhone: '7991407',
    adverseEventReporting: true,
    emergencyDeployment: true,
    defaultManager: '崔伟',
    status: 'active'
  },
  {
    id: '255',
    code: 'DEP-255',
    name: '神经内一科',
    hospitalName: '五莲县人民医院',
    disciplineCategory: '内科科',
    category: '临床病区',
    functionType: '临床病区',
    campusId: 'CAMPUS-01',
    campusName: '五莲县人民医院',
    buildingId: 'BLD-01',
    buildingName: '1号楼 综合楼',
    defaultFloor: '15F',
    nursePhone: '7991057',
    adverseEventReporting: true,
    emergencyDeployment: true,
    defaultManager: '崔伟',
    status: 'active'
  },

  // 1号楼 14F
  {
    id: '258',
    code: 'DEP-258',
    name: '心血管内二科',
    hospitalName: '五莲县人民医院',
    disciplineCategory: '内科科',
    category: '临床病区',
    functionType: '临床病区',
    campusId: 'CAMPUS-01',
    campusName: '五莲县人民医院',
    buildingId: 'BLD-01',
    buildingName: '1号楼 综合楼',
    defaultFloor: '14F',
    nursePhone: '7991298',
    adverseEventReporting: true,
    emergencyDeployment: true,
    defaultManager: '崔伟',
    status: 'active'
  },
  {
    id: '257',
    code: 'DEP-257',
    name: '心血管内一科',
    hospitalName: '五莲县人民医院',
    disciplineCategory: '内科科',
    category: '临床病区',
    functionType: '临床病区',
    campusId: 'CAMPUS-01',
    campusName: '五莲县人民医院',
    buildingId: 'BLD-01',
    buildingName: '1号楼 综合楼',
    defaultFloor: '14F',
    nursePhone: '7991427',
    adverseEventReporting: true,
    emergencyDeployment: true,
    defaultManager: '崔伟',
    status: 'active'
  },

  // 1号楼 13F
  {
    id: '268',
    code: 'DEP-268',
    name: '普外一科',
    hospitalName: '五莲县人民医院',
    disciplineCategory: '外科科',
    category: '临床病区',
    functionType: '临床病区',
    campusId: 'CAMPUS-01',
    campusName: '五莲县人民医院',
    buildingId: 'BLD-01',
    buildingName: '1号楼 综合楼',
    defaultFloor: '13F',
    nursePhone: '7991688',
    adverseEventReporting: true,
    emergencyDeployment: true,
    defaultManager: '孙志强',
    status: 'active'
  },
  {
    id: '260',
    code: 'DEP-260',
    name: '五官科',
    hospitalName: '五莲县人民医院',
    disciplineCategory: '外科科',
    category: '临床病区',
    functionType: '临床病区',
    campusId: 'CAMPUS-01',
    campusName: '五莲县人民医院',
    buildingId: 'BLD-01',
    buildingName: '1号楼 综合楼',
    defaultFloor: '13F',
    nursePhone: '7991232',
    adverseEventReporting: true,
    emergencyDeployment: true,
    defaultManager: '崔伟',
    status: 'active'
  },

  // 1号楼 12F
  {
    id: '261',
    code: 'DEP-261',
    name: '呼吸与危重症医学科',
    hospitalName: '五莲县人民医院',
    disciplineCategory: '内科科',
    category: '临床病区',
    functionType: '临床病区',
    campusId: 'CAMPUS-01',
    campusName: '五莲县人民医院',
    buildingId: 'BLD-01',
    buildingName: '1号楼 综合楼',
    defaultFloor: '12F',
    nursePhone: '7991225',
    adverseEventReporting: true,
    emergencyDeployment: true,
    defaultManager: '崔伟',
    status: 'active'
  },

  // 1号楼 11F
  {
    id: '263',
    code: 'DEP-263',
    name: '骨二科',
    hospitalName: '五莲县人民医院',
    disciplineCategory: '外科科',
    category: '临床病区',
    functionType: '临床病区',
    campusId: 'CAMPUS-01',
    campusName: '五莲县人民医院',
    buildingId: 'BLD-01',
    buildingName: '1号楼 综合楼',
    defaultFloor: '11F',
    nursePhone: '7991277',
    adverseEventReporting: true,
    emergencyDeployment: true,
    defaultManager: '崔伟',
    status: 'active'
  },
  {
    id: '262',
    code: 'DEP-262',
    name: '骨一科',
    hospitalName: '五莲县人民医院',
    disciplineCategory: '外科科',
    category: '临床病区',
    functionType: '临床病区',
    campusId: 'CAMPUS-01',
    campusName: '五莲县人民医院',
    buildingId: 'BLD-01',
    buildingName: '1号楼 综合楼',
    defaultFloor: '11F',
    nursePhone: '7991097',
    adverseEventReporting: true,
    emergencyDeployment: true,
    defaultManager: '崔伟',
    status: 'active'
  },

  // 1号楼 10F
  {
    id: '265',
    code: 'DEP-265',
    name: '泌尿胸普外科',
    hospitalName: '五莲县人民医院',
    disciplineCategory: '外科科',
    category: '临床病区',
    functionType: '临床病区',
    campusId: 'CAMPUS-01',
    campusName: '五莲县人民医院',
    buildingId: 'BLD-01',
    buildingName: '1号楼 综合楼',
    defaultFloor: '10F',
    nursePhone: '7991280',
    adverseEventReporting: true,
    emergencyDeployment: true,
    defaultManager: '崔伟',
    status: 'active'
  },
  {
    id: '264',
    code: 'DEP-264',
    name: '普外二科',
    hospitalName: '五莲县人民医院',
    disciplineCategory: '外科科',
    category: '临床病区',
    functionType: '临床病区',
    campusId: 'CAMPUS-01',
    campusName: '五莲县人民医院',
    buildingId: 'BLD-01',
    buildingName: '1号楼 综合楼',
    defaultFloor: '10F',
    nursePhone: '7991093',
    adverseEventReporting: true,
    emergencyDeployment: true,
    defaultManager: '崔伟',
    status: 'active'
  },

  // 1号楼 9F
  {
    id: '291',
    code: 'DEP-291',
    name: '产房',
    hospitalName: '五莲县人民医院',
    disciplineCategory: '妇产科',
    category: '医技',
    functionType: '医技',
    campusId: 'CAMPUS-01',
    campusName: '五莲县人民医院',
    buildingId: 'BLD-01',
    buildingName: '1号楼 综合楼',
    defaultFloor: '9F',
    nursePhone: '7991318',
    adverseEventReporting: false,
    emergencyDeployment: false,
    defaultManager: '孙志强',
    status: 'active'
  },
  {
    id: '290',
    code: 'DEP-290',
    name: '产房手术室',
    hospitalName: '五莲县人民医院',
    disciplineCategory: '妇产科',
    category: '临床',
    functionType: '临床',
    campusId: 'CAMPUS-01',
    campusName: '五莲县人民医院',
    buildingId: 'BLD-01',
    buildingName: '1号楼 综合楼',
    defaultFloor: '9F',
    nursePhone: '7991326',
    adverseEventReporting: false,
    emergencyDeployment: false,
    defaultManager: '孙志强',
    status: 'active'
  },
  {
    id: '266',
    code: 'DEP-266',
    name: '妇科',
    hospitalName: '五莲县人民医院',
    disciplineCategory: '妇产科',
    category: '临床病区',
    functionType: '临床病区',
    campusId: 'CAMPUS-01',
    campusName: '五莲县人民医院',
    buildingId: 'BLD-01',
    buildingName: '1号楼 综合楼',
    defaultFloor: '9F',
    nursePhone: '7991089',
    adverseEventReporting: true,
    emergencyDeployment: true,
    defaultManager: '崔伟',
    status: 'active'
  },
  {
    id: '364',
    code: 'DEP-364',
    name: '医疗设备应急库',
    hospitalName: '五莲县人民医院',
    disciplineCategory: '医学工程',
    category: '医技',
    functionType: '医技',
    campusId: 'CAMPUS-01',
    campusName: '五莲县人民医院',
    buildingId: 'BLD-01',
    buildingName: '1号楼 综合楼',
    defaultFloor: '9F',
    nursePhone: '7991237',
    adverseEventReporting: false,
    emergencyDeployment: true,
    defaultManager: '孙志强',
    status: 'active'
  },

  // 1号楼 8F
  {
    id: '267',
    code: 'DEP-267',
    name: '麻醉手术科',
    hospitalName: '五莲县人民医院',
    disciplineCategory: '外科科',
    category: '临床',
    functionType: '临床',
    campusId: 'CAMPUS-01',
    campusName: '五莲县人民医院',
    buildingId: 'BLD-01',
    buildingName: '1号楼 综合楼',
    defaultFloor: '8F',
    nursePhone: '7991103',
    adverseEventReporting: true,
    emergencyDeployment: true,
    defaultManager: '孙志强',
    status: 'active'
  },

  // 1号楼 7F
  {
    id: '272',
    code: 'DEP-272',
    name: '神经外科',
    hospitalName: '五莲县人民医院',
    disciplineCategory: '外科科',
    category: '临床病区',
    functionType: '临床病区',
    campusId: 'CAMPUS-01',
    campusName: '五莲县人民医院',
    buildingId: 'BLD-01',
    buildingName: '1号楼 综合楼',
    defaultFloor: '7F',
    nursePhone: '7991081',
    adverseEventReporting: true,
    emergencyDeployment: true,
    defaultManager: '孙志强',
    status: 'active'
  },
  {
    id: '269',
    code: 'DEP-269',
    name: '重症医学科',
    hospitalName: '五莲县人民医院',
    disciplineCategory: '内科科',
    category: '临床病区',
    functionType: '临床病区',
    campusId: 'CAMPUS-01',
    campusName: '五莲县人民医院',
    buildingId: 'BLD-01',
    buildingName: '1号楼 综合楼',
    defaultFloor: '7F',
    nursePhone: '7991278',
    adverseEventReporting: true,
    emergencyDeployment: true,
    defaultManager: '孙志强',
    status: 'active'
  },

  // 1号楼 6F
  {
    id: '302',
    code: 'DEP-302',
    name: '创伤外科',
    hospitalName: '五莲县人民医院',
    disciplineCategory: '外科科',
    category: '临床',
    functionType: '临床',
    campusId: 'CAMPUS-01',
    campusName: '五莲县人民医院',
    buildingId: 'BLD-01',
    buildingName: '1号楼 综合楼',
    defaultFloor: '6F',
    nursePhone: '7991148',
    adverseEventReporting: true,
    emergencyDeployment: true,
    defaultManager: '孙志强',
    status: 'active'
  },
  {
    id: '271',
    code: 'DEP-271',
    name: '血液透析室',
    hospitalName: '五莲县人民医院',
    disciplineCategory: '内科科',
    category: '临床病区',
    functionType: '临床病区',
    campusId: 'CAMPUS-01',
    campusName: '五莲县人民医院',
    buildingId: 'BLD-01',
    buildingName: '1号楼 综合楼',
    defaultFloor: '6F',
    nursePhone: '7991162',
    adverseEventReporting: true,
    emergencyDeployment: false,
    defaultManager: '孙志强',
    status: 'active'
  },

  // 1号楼 5F
  {
    id: '259',
    code: 'DEP-259',
    name: '小儿科',
    hospitalName: '五莲县人民医院',
    disciplineCategory: '内科科',
    category: '临床病区',
    functionType: '临床病区',
    campusId: 'CAMPUS-01',
    campusName: '五莲县人民医院',
    buildingId: 'BLD-01',
    buildingName: '1号楼 综合楼',
    defaultFloor: '5F',
    nursePhone: '7991142',
    adverseEventReporting: true,
    emergencyDeployment: true,
    defaultManager: '崔伟',
    status: 'active'
  },
  {
    id: '289',
    code: 'DEP-289',
    name: '新生儿科',
    hospitalName: '五莲县人民医院',
    disciplineCategory: '内科科',
    category: '临床病区',
    functionType: '临床病区',
    campusId: 'CAMPUS-01',
    campusName: '五莲县人民医院',
    buildingId: 'BLD-01',
    buildingName: '1号楼 综合楼',
    defaultFloor: '5F',
    nursePhone: '7991358',
    adverseEventReporting: true,
    emergencyDeployment: true,
    defaultManager: '孙志强',
    status: 'active'
  },
  {
    id: '336',
    code: 'DEP-336',
    name: '信息科',
    hospitalName: '五莲县人民医院',
    disciplineCategory: '行政办公室',
    category: '行管后勤',
    functionType: '行管后勤',
    campusId: 'CAMPUS-01',
    campusName: '五莲县人民医院',
    buildingId: 'BLD-01',
    buildingName: '1号楼 综合楼',
    defaultFloor: '5F',
    nursePhone: '7991207',
    adverseEventReporting: false,
    emergencyDeployment: false,
    defaultManager: '孙志强',
    status: 'active'
  },
  {
    id: '307',
    code: 'DEP-307',
    name: '药剂科',
    hospitalName: '五莲县人民医院',
    disciplineCategory: '药剂学',
    category: '医技',
    functionType: '医技',
    campusId: 'CAMPUS-01',
    campusName: '五莲县人民医院',
    buildingId: 'BLD-01',
    buildingName: '1号楼 综合楼',
    defaultFloor: '5F',
    nursePhone: '7991030',
    adverseEventReporting: false,
    emergencyDeployment: false,
    defaultManager: '孙志强',
    status: 'active'
  },

  // 1号楼 4F
  {
    id: '292',
    code: 'DEP-292',
    name: '产科',
    hospitalName: '五莲县人民医院',
    disciplineCategory: '妇产科',
    category: '临床病区',
    functionType: '临床病区',
    campusId: 'CAMPUS-01',
    campusName: '五莲县人民医院',
    buildingId: 'BLD-01',
    buildingName: '1号楼 综合楼',
    defaultFloor: '4F',
    nursePhone: '7991318',
    adverseEventReporting: true,
    emergencyDeployment: true,
    defaultManager: '孙志强',
    status: 'active'
  },
  {
    id: '274',
    code: 'DEP-274',
    name: '耳鼻喉科',
    hospitalName: '五莲县人民医院',
    disciplineCategory: '耳鼻喉科',
    category: '临床',
    functionType: '临床',
    campusId: 'CAMPUS-01',
    campusName: '五莲县人民医院',
    buildingId: 'BLD-01',
    buildingName: '1号楼 综合楼',
    defaultFloor: '4F',
    nursePhone: '7991170',
    adverseEventReporting: true,
    emergencyDeployment: false,
    defaultManager: '孙志强',
    status: 'active'
  },
  {
    id: '275',
    code: 'DEP-275',
    name: '口腔科',
    hospitalName: '五莲县人民医院',
    disciplineCategory: '口腔医学科',
    category: '临床',
    functionType: '临床',
    campusId: 'CAMPUS-01',
    campusName: '五莲县人民医院',
    buildingId: 'BLD-01',
    buildingName: '1号楼 综合楼',
    defaultFloor: '4F',
    nursePhone: '7991169',
    adverseEventReporting: true,
    emergencyDeployment: false,
    defaultManager: '孙志强',
    status: 'active'
  },
  {
    id: '273',
    code: 'DEP-273',
    name: '眼科',
    hospitalName: '五莲县人民医院',
    disciplineCategory: '眼科科',
    category: '临床',
    functionType: '临床',
    campusId: 'CAMPUS-01',
    campusName: '五莲县人民医院',
    buildingId: 'BLD-01',
    buildingName: '1号楼 综合楼',
    defaultFloor: '4F',
    nursePhone: '7991030',
    adverseEventReporting: true,
    emergencyDeployment: false,
    defaultManager: '孙志强',
    status: 'active'
  },
  {
    id: '345',
    code: 'DEP-345',
    name: '医共体',
    hospitalName: '五莲县人民医院',
    disciplineCategory: '行政办公室',
    category: '行管后勤',
    functionType: '行管后勤',
    campusId: 'CAMPUS-01',
    campusName: '五莲县人民医院',
    buildingId: 'BLD-01',
    buildingName: '1号楼 综合楼',
    defaultFloor: '4F',
    nursePhone: '7991100',
    adverseEventReporting: false,
    emergencyDeployment: false,
    defaultManager: '孙志强',
    status: 'active'
  },
  {
    id: '333',
    code: 'DEP-333',
    name: '医共体办公室',
    hospitalName: '五莲县人民医院',
    disciplineCategory: '行政办公室',
    category: '行管后勤',
    functionType: '行管后勤',
    campusId: 'CAMPUS-01',
    campusName: '五莲县人民医院',
    buildingId: 'BLD-01',
    buildingName: '1号楼 综合楼',
    defaultFloor: '4F',
    nursePhone: '7991100',
    adverseEventReporting: false,
    emergencyDeployment: false,
    defaultManager: '孙志强',
    status: 'active'
  },

  // 1号楼 3F
  {
    id: '279',
    code: 'DEP-279',
    name: '超声科',
    hospitalName: '五莲县人民医院',
    disciplineCategory: '医学影像科',
    category: '临床',
    functionType: '临床',
    campusId: 'CAMPUS-01',
    campusName: '五莲县人民医院',
    buildingId: 'BLD-01',
    buildingName: '1号楼 综合楼',
    defaultFloor: '3F',
    nursePhone: '7991195',
    adverseEventReporting: true,
    emergencyDeployment: false,
    defaultManager: '孙志强',
    status: 'active'
  },
  {
    id: '280',
    code: 'DEP-280',
    name: '功能检查科',
    hospitalName: '五莲县人民医院',
    disciplineCategory: '医学影像科',
    category: '医技',
    functionType: '医技',
    campusId: 'CAMPUS-01',
    campusName: '五莲县人民医院',
    buildingId: 'BLD-01',
    buildingName: '1号楼 综合楼',
    defaultFloor: '3F',
    nursePhone: '7991195',
    adverseEventReporting: false,
    emergencyDeployment: false,
    defaultManager: '孙志强',
    status: 'active'
  },
  {
    id: '281',
    code: 'DEP-281',
    name: '检验科',
    hospitalName: '五莲县人民医院',
    disciplineCategory: '医学检验科',
    category: '医技',
    functionType: '医技',
    campusId: 'CAMPUS-01',
    campusName: '五莲县人民医院',
    buildingId: 'BLD-01',
    buildingName: '1号楼 综合楼',
    defaultFloor: '3F',
    nursePhone: '7991397',
    adverseEventReporting: true,
    emergencyDeployment: false,
    defaultManager: '孙志强',
    status: 'active'
  },
  {
    id: '278',
    code: 'DEP-278',
    name: '内镜室',
    hospitalName: '五莲县人民医院',
    disciplineCategory: '内科科',
    category: '临床',
    functionType: '临床',
    campusId: 'CAMPUS-01',
    campusName: '五莲县人民医院',
    buildingId: 'BLD-01',
    buildingName: '1号楼 综合楼',
    defaultFloor: '3F',
    nursePhone: '7991106',
    adverseEventReporting: true,
    emergencyDeployment: true,
    defaultManager: '孙志强',
    status: 'active'
  },
  {
    id: '358',
    code: 'DEP-358',
    name: '输血科',
    hospitalName: '五莲县人民医院',
    disciplineCategory: '医学检验科',
    category: '临床',
    functionType: '临床',
    campusId: 'CAMPUS-01',
    campusName: '五莲县人民医院',
    buildingId: 'BLD-01',
    buildingName: '1号楼 综合楼',
    defaultFloor: '3F',
    nursePhone: '7991168',
    adverseEventReporting: false,
    emergencyDeployment: false,
    defaultManager: '孙志强',
    status: 'active'
  },

  // 1号楼 2F
  {
    id: '366',
    code: 'DEP-366',
    name: '产科门诊',
    hospitalName: '五莲县人民医院',
    disciplineCategory: '妇产科',
    category: '临床',
    functionType: '临床',
    campusId: 'CAMPUS-01',
    campusName: '五莲县人民医院',
    buildingId: 'BLD-01',
    buildingName: '1号楼 综合楼',
    defaultFloor: '2F',
    nursePhone: '7991318',
    adverseEventReporting: false,
    emergencyDeployment: false,
    defaultManager: '孙志强',
    status: 'active'
  },
  {
    id: '284',
    code: 'DEP-284',
    name: '门诊部',
    hospitalName: '五莲县人民医院',
    disciplineCategory: '门诊部',
    category: '临床',
    functionType: '临床',
    campusId: 'CAMPUS-01',
    campusName: '五莲县人民医院',
    buildingId: 'BLD-01',
    buildingName: '1号楼 综合楼',
    defaultFloor: '2F',
    nursePhone: '7991397',
    adverseEventReporting: false,
    emergencyDeployment: false,
    defaultManager: '孙志强',
    status: 'active'
  },
  {
    id: '357',
    code: 'DEP-357',
    name: '门诊手术室',
    hospitalName: '五莲县人民医院',
    disciplineCategory: '外科科',
    category: '临床',
    functionType: '临床',
    campusId: 'CAMPUS-01',
    campusName: '五莲县人民医院',
    buildingId: 'BLD-01',
    buildingName: '1号楼 综合楼',
    defaultFloor: '2F',
    nursePhone: '7991120',
    adverseEventReporting: false,
    emergencyDeployment: false,
    defaultManager: '孙志强',
    status: 'active'
  },
  {
    id: '337',
    code: 'DEP-337',
    name: '门诊输液室',
    hospitalName: '五莲县人民医院',
    disciplineCategory: '门诊部',
    category: '临床',
    functionType: '临床',
    campusId: 'CAMPUS-01',
    campusName: '五莲县人民医院',
    buildingId: 'BLD-01',
    buildingName: '1号楼 综合楼',
    defaultFloor: '2F',
    nursePhone: '7991195',
    adverseEventReporting: false,
    emergencyDeployment: false,
    defaultManager: '孙志强',
    status: 'active'
  },
  {
    id: '283',
    code: 'DEP-283',
    name: '皮肤科',
    hospitalName: '五莲县人民医院',
    disciplineCategory: '皮肤医学科',
    category: '临床',
    functionType: '临床',
    campusId: 'CAMPUS-01',
    campusName: '五莲县人民医院',
    buildingId: 'BLD-01',
    buildingName: '1号楼 综合楼',
    defaultFloor: '2F',
    nursePhone: '7991168',
    adverseEventReporting: false,
    emergencyDeployment: false,
    defaultManager: '孙志强',
    status: 'active'
  },
  {
    id: '305',
    code: 'DEP-305',
    name: '疼痛门诊',
    hospitalName: '五莲县人民医院',
    disciplineCategory: '麻醉科',
    category: '临床',
    functionType: '临床',
    campusId: 'CAMPUS-01',
    campusName: '五莲县人民医院',
    buildingId: 'BLD-01',
    buildingName: '1号楼 综合楼',
    defaultFloor: '2F',
    nursePhone: '7991389',
    adverseEventReporting: false,
    emergencyDeployment: false,
    defaultManager: '孙志强',
    status: 'active'
  },
  {
    id: '342',
    code: 'DEP-342',
    name: '心理咨询门诊',
    hospitalName: '五莲县人民医院',
    disciplineCategory: '临床心理',
    category: '临床',
    functionType: '临床',
    campusId: 'CAMPUS-01',
    campusName: '五莲县人民医院',
    buildingId: 'BLD-01',
    buildingName: '1号楼 综合楼',
    defaultFloor: '2F',
    nursePhone: '7991262',
    adverseEventReporting: false,
    emergencyDeployment: false,
    defaultManager: '孙志强',
    status: 'active'
  },
  {
    id: '341',
    code: 'DEP-341',
    name: '中医不孕不育门诊',
    hospitalName: '五莲县人民医院',
    disciplineCategory: '中医科',
    category: '临床',
    functionType: '临床',
    campusId: 'CAMPUS-01',
    campusName: '五莲县人民医院',
    buildingId: 'BLD-01',
    buildingName: '1号楼 综合楼',
    defaultFloor: '2F',
    nursePhone: '7991496',
    adverseEventReporting: false,
    emergencyDeployment: false,
    defaultManager: '孙志强',
    status: 'active'
  },

  // 1号楼 1F
  {
    id: '286',
    code: 'DEP-286',
    name: '急诊科',
    hospitalName: '五莲县人民医院',
    disciplineCategory: '急危重症',
    category: '临床病区',
    functionType: '临床病区',
    campusId: 'CAMPUS-01',
    campusName: '五莲县人民医院',
    buildingId: 'BLD-01',
    buildingName: '1号楼 综合楼',
    defaultFloor: '1F',
    nursePhone: '7991065',
    adverseEventReporting: true,
    emergencyDeployment: true,
    defaultManager: '孙志强',
    status: 'active'
  },
  {
    id: '338',
    code: 'DEP-338',
    name: '收费结算科',
    hospitalName: '五莲县人民医院',
    disciplineCategory: '财务科',
    category: '行管后勤',
    functionType: '行管后勤',
    campusId: 'CAMPUS-01',
    campusName: '五莲县人民医院',
    buildingId: 'BLD-01',
    buildingName: '1号楼 综合楼',
    defaultFloor: '1F',
    nursePhone: '7991108',
    adverseEventReporting: false,
    emergencyDeployment: false,
    defaultManager: '孙志强',
    status: 'active'
  },
  {
    id: '334',
    code: 'DEP-334',
    name: '医保科',
    hospitalName: '五莲县人民医院',
    disciplineCategory: '行政办公室',
    category: '行管后勤',
    functionType: '行管后勤',
    campusId: 'CAMPUS-01',
    campusName: '五莲县人民医院',
    buildingId: 'BLD-01',
    buildingName: '1号楼 综合楼',
    defaultFloor: '1F',
    nursePhone: '7991186',
    adverseEventReporting: false,
    emergencyDeployment: false,
    defaultManager: '孙志强',
    status: 'active'
  },

  // 1号楼 -1F
  {
    id: '287',
    code: 'DEP-287',
    name: '介入放射科',
    hospitalName: '五莲县人民医院',
    disciplineCategory: '医学影像科',
    category: '医技',
    functionType: '医技',
    campusId: 'CAMPUS-01',
    campusName: '五莲县人民医院',
    buildingId: 'BLD-01',
    buildingName: '1号楼 综合楼',
    defaultFloor: '-1F',
    nursePhone: '7991498',
    adverseEventReporting: true,
    emergencyDeployment: false,
    defaultManager: '孙志强',
    status: 'active'
  },
  {
    id: '288',
    code: 'DEP-288',
    name: '影像科',
    hospitalName: '五莲县人民医院',
    disciplineCategory: '医学影像科',
    category: '医技',
    functionType: '医技',
    campusId: 'CAMPUS-01',
    campusName: '五莲县人民医院',
    buildingId: 'BLD-01',
    buildingName: '1号楼 综合楼',
    defaultFloor: '-1F',
    nursePhone: '7991020',
    adverseEventReporting: true,
    emergencyDeployment: false,
    defaultManager: '孙志强',
    status: 'active'
  },

  // 2号楼 原内科楼
  {
    id: '298',
    code: 'DEP-298',
    name: '康复医学科',
    hospitalName: '五莲县人民医院',
    disciplineCategory: '康复医学',
    category: '临床病区',
    functionType: '临床病区',
    campusId: 'CAMPUS-01',
    campusName: '五莲县人民医院',
    buildingId: 'BLD-02',
    buildingName: '2号楼 原内科楼',
    defaultFloor: '3F',
    nursePhone: '7991721',
    adverseEventReporting: true,
    emergencyDeployment: true,
    defaultManager: '孙志强',
    status: 'active'
  },
  {
    id: '369',
    code: 'DEP-369',
    name: '老年康复科',
    hospitalName: '五莲县人民医院',
    disciplineCategory: '康复医学',
    category: '临床',
    functionType: '临床',
    campusId: 'CAMPUS-01',
    campusName: '五莲县人民医院',
    buildingId: 'BLD-02',
    buildingName: '2号楼 原内科楼',
    defaultFloor: '2F',
    nursePhone: '7991359',
    adverseEventReporting: false,
    emergencyDeployment: false,
    defaultManager: '孙志强',
    status: 'active'
  },

  // 3号楼 原妇幼楼
  {
    id: '297',
    code: 'DEP-297',
    name: '综合保健科',
    hospitalName: '五莲县人民医院',
    disciplineCategory: '预防保健',
    category: '临床病区',
    functionType: '临床病区',
    campusId: 'CAMPUS-01',
    campusName: '五莲县人民医院',
    buildingId: 'BLD-03',
    buildingName: '3号楼 原妇幼楼',
    defaultFloor: '4F',
    nursePhone: '7991061',
    adverseEventReporting: true,
    emergencyDeployment: true,
    defaultManager: '孙志强',
    status: 'active'
  },
  {
    id: '326',
    code: 'DEP-326',
    name: '理疗科',
    hospitalName: '五莲县人民医院',
    disciplineCategory: '康复医学',
    category: '临床',
    functionType: '临床',
    campusId: 'CAMPUS-01',
    campusName: '五莲县人民医院',
    buildingId: 'BLD-03',
    buildingName: '3号楼 原妇幼楼',
    defaultFloor: '3F',
    nursePhone: '7991152',
    adverseEventReporting: true,
    emergencyDeployment: false,
    defaultManager: '孙志强',
    status: 'active'
  },
  {
    id: '327',
    code: 'DEP-327',
    name: '临床营养科',
    hospitalName: '五莲县人民医院',
    disciplineCategory: '医技科室',
    category: '医技',
    functionType: '医技',
    campusId: 'CAMPUS-01',
    campusName: '五莲县人民医院',
    buildingId: 'BLD-03',
    buildingName: '3号楼 原妇幼楼',
    defaultFloor: '3F',
    nursePhone: '7991481',
    adverseEventReporting: false,
    emergencyDeployment: false,
    defaultManager: '孙志强',
    status: 'active'
  },
  {
    id: '270',
    code: 'DEP-270',
    name: '中医科',
    hospitalName: '五莲县人民医院',
    disciplineCategory: '内科科',
    category: '临床病区',
    functionType: '临床病区',
    campusId: 'CAMPUS-01',
    campusName: '五莲县人民医院',
    buildingId: 'BLD-03',
    buildingName: '3号楼 原妇幼楼',
    defaultFloor: '3F',
    nursePhone: '7991073',
    adverseEventReporting: true,
    emergencyDeployment: true,
    defaultManager: '孙志强',
    status: 'active'
  },
  {
    id: '300',
    code: 'DEP-300',
    name: '健康服务科',
    hospitalName: '五莲县人民医院',
    disciplineCategory: '预防保健',
    category: '临床',
    functionType: '临床',
    campusId: 'CAMPUS-01',
    campusName: '五莲县人民医院',
    buildingId: 'BLD-03',
    buildingName: '3号楼 原妇幼楼',
    defaultFloor: '2F',
    nursePhone: '7991272',
    adverseEventReporting: false,
    emergencyDeployment: false,
    defaultManager: '孙志强',
    status: 'active'
  },
  {
    id: '359',
    code: 'DEP-359',
    name: '司法鉴定办公室',
    hospitalName: '五莲县人民医院',
    disciplineCategory: '行政办公室',
    category: '医技',
    functionType: '医技',
    campusId: 'CAMPUS-01',
    campusName: '五莲县人民医院',
    buildingId: 'BLD-03',
    buildingName: '3号楼 原妇幼楼',
    defaultFloor: '2F',
    nursePhone: '7991158',
    adverseEventReporting: false,
    emergencyDeployment: false,
    defaultManager: '孙志强',
    status: 'active'
  },
  {
    id: '295',
    code: 'DEP-295',
    name: '放疗科',
    hospitalName: '五莲县人民医院',
    disciplineCategory: '肿瘤放疗',
    category: '医技',
    functionType: '医技',
    campusId: 'CAMPUS-01',
    campusName: '五莲县人民医院',
    buildingId: 'BLD-03',
    buildingName: '3号楼 原妇幼楼',
    defaultFloor: '1F',
    nursePhone: '7991063',
    adverseEventReporting: false,
    emergencyDeployment: false,
    defaultManager: '孙志强',
    status: 'active'
  },
  {
    id: '293',
    code: 'DEP-293',
    name: '母婴保健科',
    hospitalName: '五莲县人民医院',
    disciplineCategory: '妇幼保健',
    category: '临床',
    functionType: '临床',
    campusId: 'CAMPUS-01',
    campusName: '五莲县人民医院',
    buildingId: 'BLD-03',
    buildingName: '3号楼 原妇幼楼',
    defaultFloor: '1F',
    nursePhone: '7991300',
    adverseEventReporting: false,
    emergencyDeployment: false,
    defaultManager: '孙志强',
    status: 'active'
  },
  {
    id: '294',
    code: 'DEP-294',
    name: '消毒供应室',
    hospitalName: '五莲县人民医院',
    disciplineCategory: '护理部',
    category: '医技',
    functionType: '医技',
    campusId: 'CAMPUS-01',
    campusName: '五莲县人民医院',
    buildingId: 'BLD-03',
    buildingName: '3号楼 原妇幼楼',
    defaultFloor: '-1F',
    nursePhone: '7991496',
    adverseEventReporting: false,
    emergencyDeployment: false,
    defaultManager: '孙志强',
    status: 'active'
  },

  // 4号楼 急救站
  {
    id: '299',
    code: 'DEP-299',
    name: '急救站',
    hospitalName: '五莲县人民医院',
    disciplineCategory: '急危重症',
    category: '临床',
    functionType: '临床',
    campusId: 'CAMPUS-01',
    campusName: '五莲县人民医院',
    buildingId: 'BLD-04',
    buildingName: '4号楼 急救站',
    defaultFloor: '1F',
    nursePhone: '7991359',
    adverseEventReporting: false,
    emergencyDeployment: false,
    defaultManager: '孙志强',
    status: 'active'
  },

  // 5号楼 感染性疾病科
  {
    id: '296',
    code: 'DEP-296',
    name: '感染性疾病科',
    hospitalName: '五莲县人民医院',
    disciplineCategory: '感染性疾病',
    category: '临床病区',
    functionType: '临床病区',
    campusId: 'CAMPUS-01',
    campusName: '五莲县人民医院',
    buildingId: 'BLD-05',
    buildingName: '5号楼 感染性疾病科',
    defaultFloor: '2F',
    nursePhone: '7991247',
    adverseEventReporting: true,
    emergencyDeployment: true,
    defaultManager: '孙志强',
    status: 'active'
  },

  // 6号楼 办公楼
  {
    id: '335',
    code: 'DEP-335',
    name: '宣教科',
    hospitalName: '五莲县人民医院',
    disciplineCategory: '行政办公室',
    category: '行管后勤',
    functionType: '行管后勤',
    campusId: 'CAMPUS-01',
    campusName: '五莲县人民医院',
    buildingId: 'BLD-06',
    buildingName: '6号楼 办公楼',
    defaultFloor: '3F',
    nursePhone: '7991088',
    adverseEventReporting: false,
    emergencyDeployment: false,
    defaultManager: '孙志强',
    status: 'active'
  },
  {
    id: '368',
    code: 'DEP-368',
    name: '作风办公室',
    hospitalName: '五莲县人民医院',
    disciplineCategory: '行政办公室',
    category: '行管后勤',
    functionType: '行管后勤',
    campusId: 'CAMPUS-01',
    campusName: '五莲县人民医院',
    buildingId: 'BLD-06',
    buildingName: '6号楼 办公楼',
    defaultFloor: '3F',
    nursePhone: '7991000',
    adverseEventReporting: false,
    emergencyDeployment: false,
    defaultManager: '孙志强',
    status: 'active'
  },
  {
    id: '324',
    code: 'DEP-324',
    name: '绩效考核科',
    hospitalName: '五莲县人民医院',
    disciplineCategory: '行政办公室',
    category: '行管后勤',
    functionType: '行管后勤',
    campusId: 'CAMPUS-01',
    campusName: '五莲县人民医院',
    buildingId: 'BLD-06',
    buildingName: '6号楼 办公楼',
    defaultFloor: '2F',
    nursePhone: '7991366',
    adverseEventReporting: false,
    emergencyDeployment: false,
    defaultManager: '孙志强',
    status: 'active'
  },
  {
    id: '346',
    code: 'DEP-346',
    name: '领导办公室',
    hospitalName: '五莲县人民医院',
    disciplineCategory: '行政办公室',
    category: '行管后勤',
    functionType: '行管后勤',
    campusId: 'CAMPUS-01',
    campusName: '五莲县人民医院',
    buildingId: 'BLD-06',
    buildingName: '6号楼 办公楼',
    defaultFloor: '2F',
    nursePhone: '7991000',
    adverseEventReporting: false,
    emergencyDeployment: false,
    defaultManager: '孙志强',
    status: 'active'
  },
  {
    id: '328',
    code: 'DEP-328',
    name: '人事科',
    hospitalName: '五莲县人民医院',
    disciplineCategory: '行政办公室',
    category: '行管后勤',
    functionType: '行管后勤',
    campusId: 'CAMPUS-01',
    campusName: '五莲县人民医院',
    buildingId: 'BLD-06',
    buildingName: '6号楼 办公楼',
    defaultFloor: '2F',
    nursePhone: '7991218',
    adverseEventReporting: false,
    emergencyDeployment: false,
    defaultManager: '孙志强',
    status: 'active'
  },
  {
    id: '339',
    code: 'DEP-339',
    name: '审计科',
    hospitalName: '五莲县人民医院',
    disciplineCategory: '行政办公室',
    category: '行管后勤',
    functionType: '行管后勤',
    campusId: 'CAMPUS-01',
    campusName: '五莲县人民医院',
    buildingId: 'BLD-06',
    buildingName: '6号楼 办公楼',
    defaultFloor: '2F',
    nursePhone: '7991027',
    adverseEventReporting: false,
    emergencyDeployment: false,
    defaultManager: '孙志强',
    status: 'active'
  },
  {
    id: '329',
    code: 'DEP-329',
    name: '院办公室',
    hospitalName: '五莲县人民医院',
    disciplineCategory: '行政办公室',
    category: '行管后勤',
    functionType: '行管后勤',
    campusId: 'CAMPUS-01',
    campusName: '五莲县人民医院',
    buildingId: 'BLD-06',
    buildingName: '6号楼 办公楼',
    defaultFloor: '2F',
    nursePhone: '7991204',
    adverseEventReporting: false,
    emergencyDeployment: false,
    defaultManager: '孙志强',
    status: 'active'
  },
  {
    id: '320',
    code: 'DEP-320',
    name: '院长办公室',
    hospitalName: '五莲县人民医院',
    disciplineCategory: '行政办公室',
    category: '行管后勤',
    functionType: '行管后勤',
    campusId: 'CAMPUS-01',
    campusName: '五莲县人民医院',
    buildingId: 'BLD-06',
    buildingName: '6号楼 办公楼',
    defaultFloor: '2F',
    nursePhone: '7991000',
    adverseEventReporting: false,
    emergencyDeployment: false,
    defaultManager: '孙志强',
    status: 'active'
  },
  {
    id: '319',
    code: 'DEP-319',
    name: '财务科',
    hospitalName: '五莲县人民医院',
    disciplineCategory: '财务科',
    category: '行管后勤',
    functionType: '行管后勤',
    campusId: 'CAMPUS-01',
    campusName: '五莲县人民医院',
    buildingId: 'BLD-06',
    buildingName: '6号楼 办公楼',
    defaultFloor: '1F',
    nursePhone: '7991025',
    adverseEventReporting: false,
    emergencyDeployment: false,
    defaultManager: '孙志强',
    status: 'active'
  },
  {
    id: '344',
    code: 'DEP-344',
    name: '扶贫办',
    hospitalName: '五莲县人民医院',
    disciplineCategory: '行政办公室',
    category: '行管后勤',
    functionType: '行管后勤',
    campusId: 'CAMPUS-01',
    campusName: '五莲县人民医院',
    buildingId: 'BLD-06',
    buildingName: '6号楼 办公楼',
    defaultFloor: '1F',
    nursePhone: '7991396',
    adverseEventReporting: false,
    emergencyDeployment: false,
    defaultManager: '孙志强',
    status: 'active'
  },
  {
    id: '321',
    code: 'DEP-321',
    name: '感染管理科',
    hospitalName: '五莲县人民医院',
    disciplineCategory: '院感管理',
    category: '行管后勤',
    functionType: '行管后勤',
    campusId: 'CAMPUS-01',
    campusName: '五莲县人民医院',
    buildingId: 'BLD-06',
    buildingName: '6号楼 办公楼',
    defaultFloor: '1F',
    nursePhone: '7991215',
    adverseEventReporting: false,
    emergencyDeployment: false,
    defaultManager: '孙志强',
    status: 'active'
  },
  {
    id: '322',
    code: 'DEP-322',
    name: '后勤保障部',
    hospitalName: '五莲县人民医院',
    disciplineCategory: '后勤总务',
    category: '行管后勤',
    functionType: '行管后勤',
    campusId: 'CAMPUS-01',
    campusName: '五莲县人民医院',
    buildingId: 'BLD-06',
    buildingName: '6号楼 办公楼',
    defaultFloor: '1F',
    nursePhone: '7991191',
    adverseEventReporting: false,
    emergencyDeployment: false,
    defaultManager: '孙志强',
    status: 'active'
  },
  {
    id: '323',
    code: 'DEP-323',
    name: '护理部',
    hospitalName: '五莲县人民医院',
    disciplineCategory: '护理部',
    category: '行管后勤',
    functionType: '行管后勤',
    campusId: 'CAMPUS-01',
    campusName: '五莲县人民医院',
    buildingId: 'BLD-06',
    buildingName: '6号楼 办公楼',
    defaultFloor: '1F',
    nursePhone: '7991406',
    adverseEventReporting: false,
    emergencyDeployment: false,
    defaultManager: '孙志强',
    status: 'active'
  },
  {
    id: '360',
    code: 'DEP-360',
    name: '医疗安全办公室',
    hospitalName: '五莲县人民医院',
    disciplineCategory: '医疗安全',
    category: '行管后勤',
    functionType: '行管后勤',
    campusId: 'CAMPUS-01',
    campusName: '五莲县人民医院',
    buildingId: 'BLD-06',
    buildingName: '6号楼 办公楼',
    defaultFloor: '1F',
    nursePhone: '7991039',
    adverseEventReporting: false,
    emergencyDeployment: false,
    defaultManager: '孙志强',
    status: 'active'
  },
  {
    id: '332',
    code: 'DEP-332',
    name: '医疗安全科',
    hospitalName: '五莲县人民医院',
    disciplineCategory: '医疗安全',
    category: '行管后勤',
    functionType: '行管后勤',
    campusId: 'CAMPUS-01',
    campusName: '五莲县人民医院',
    buildingId: 'BLD-06',
    buildingName: '6号楼 办公楼',
    defaultFloor: '1F',
    nursePhone: '7991039',
    adverseEventReporting: false,
    emergencyDeployment: false,
    defaultManager: '孙志强',
    status: 'active'
  },
  {
    id: '303',
    code: 'DEP-303',
    name: '医疗设备科',
    hospitalName: '五莲县人民医院',
    disciplineCategory: '医学工程',
    category: '医技',
    functionType: '医技',
    campusId: 'CAMPUS-01',
    campusName: '五莲县人民医院',
    buildingId: 'BLD-06',
    buildingName: '6号楼 办公楼',
    defaultFloor: '1F',
    nursePhone: '7991237',
    adverseEventReporting: false,
    emergencyDeployment: false,
    defaultManager: '孙志强',
    status: 'active'
  },
  {
    id: '331',
    code: 'DEP-331',
    name: '医务科',
    hospitalName: '五莲县人民医院',
    disciplineCategory: '医务管理',
    category: '行管后勤',
    functionType: '行管后勤',
    campusId: 'CAMPUS-01',
    campusName: '五莲县人民医院',
    buildingId: 'BLD-06',
    buildingName: '6号楼 办公楼',
    defaultFloor: '1F',
    nursePhone: '7991112',
    adverseEventReporting: false,
    emergencyDeployment: false,
    defaultManager: '孙志强',
    status: 'active'
  },
  {
    id: '330',
    code: 'DEP-330',
    name: '预防保健科',
    hospitalName: '五莲县人民医院',
    disciplineCategory: '预防保健',
    category: '行管后勤',
    functionType: '行管后勤',
    campusId: 'CAMPUS-01',
    campusName: '五莲县人民医院',
    buildingId: 'BLD-06',
    buildingName: '6号楼 办公楼',
    defaultFloor: '1F',
    nursePhone: '7991032',
    adverseEventReporting: false,
    emergencyDeployment: false,
    defaultManager: '孙志强',
    status: 'active'
  },
  {
    id: '325',
    code: 'DEP-325',
    name: '科教科',
    hospitalName: '五莲县人民医院',
    disciplineCategory: '教学科研',
    category: '行管后勤',
    functionType: '行管后勤',
    campusId: 'CAMPUS-01',
    campusName: '五莲县人民医院',
    buildingId: 'BLD-06',
    buildingName: '6号楼 办公楼',
    defaultFloor: '0F',
    nursePhone: '7991723',
    adverseEventReporting: false,
    emergencyDeployment: false,
    defaultManager: '孙志强',
    status: 'active'
  },
  {
    id: '361',
    code: 'DEP-361',
    name: '老干部活动办公室',
    hospitalName: '五莲县人民医院',
    disciplineCategory: '离退休工作',
    category: '行管后勤',
    functionType: '行管后勤',
    campusId: 'CAMPUS-01',
    campusName: '五莲县人民医院',
    buildingId: 'BLD-06',
    buildingName: '6号楼 办公楼',
    defaultFloor: '0F',
    nursePhone: '2252331',
    adverseEventReporting: false,
    emergencyDeployment: false,
    defaultManager: '孙志强',
    status: 'active'
  },

  // 0光明路
  {
    id: '340',
    code: 'DEP-340',
    name: '光明路门诊',
    hospitalName: '五莲县人民医院',
    disciplineCategory: '门诊部',
    category: '临床',
    functionType: '临床',
    campusId: 'CAMPUS-01',
    campusName: '五莲县人民医院',
    buildingId: 'BLD-07',
    buildingName: '0光明路',
    defaultFloor: '1F',
    nursePhone: '18969332587',
    adverseEventReporting: false,
    emergencyDeployment: false,
    defaultManager: '孙志强',
    status: 'active'
  },

  // 0公用设施 / 特殊设定
  {
    id: '367',
    code: 'DEP-367',
    name: '公用设施',
    hospitalName: '五莲县人民医院',
    disciplineCategory: '公用设施',
    category: '特殊',
    functionType: '特殊',
    campusId: 'CAMPUS-01',
    campusName: '五莲县人民医院',
    buildingId: 'BLD-08',
    buildingName: '0公用设施',
    defaultFloor: '0F',
    nursePhone: '7991100',
    adverseEventReporting: false,
    emergencyDeployment: false,
    defaultManager: '孙志强',
    status: 'active'
  },
  {
    id: '365',
    code: 'DEP-365',
    name: '特殊设定',
    hospitalName: '五莲县人民医院',
    disciplineCategory: '特殊设定',
    category: '特殊',
    functionType: '特殊',
    campusId: 'CAMPUS-01',
    campusName: '五莲县人民医院',
    buildingId: 'BLD-08',
    buildingName: '0公用设施',
    defaultFloor: '0F',
    nursePhone: '7991100',
    adverseEventReporting: false,
    emergencyDeployment: false,
    defaultManager: '孙志强',
    status: 'active'
  },

  // ==================== 五莲县皮肤病医院 ====================
  {
    id: '349',
    code: 'DEP-349',
    name: '皮肤病医院办公室',
    hospitalName: '五莲县皮肤病医院',
    disciplineCategory: '行政办公室',
    category: '行管后勤',
    functionType: '行管后勤',
    campusId: 'CAMPUS-02',
    campusName: '五莲县皮肤病医院',
    buildingId: 'BLD-DERM-01',
    buildingName: '0皮肤病医院门诊楼',
    defaultFloor: '2F',
    nursePhone: '7961100',
    adverseEventReporting: false,
    emergencyDeployment: false,
    defaultManager: '孙志强',
    status: 'active'
  },
  {
    id: '348',
    code: 'DEP-348',
    name: '皮肤病医院财务科',
    hospitalName: '五莲县皮肤病医院',
    disciplineCategory: '财务科',
    category: '行管后勤',
    functionType: '行管后勤',
    campusId: 'CAMPUS-02',
    campusName: '五莲县皮肤病医院',
    buildingId: 'BLD-DERM-01',
    buildingName: '0皮肤病医院门诊楼',
    defaultFloor: '2F',
    nursePhone: '7961100',
    adverseEventReporting: false,
    emergencyDeployment: false,
    defaultManager: '孙志强',
    status: 'active'
  },
  {
    id: '354',
    code: 'DEP-354',
    name: '皮肤病医院皮肤病病房',
    hospitalName: '五莲县皮肤病医院',
    disciplineCategory: '皮肤科',
    category: '临床',
    functionType: '临床',
    campusId: 'CAMPUS-02',
    campusName: '五莲县皮肤病医院',
    buildingId: 'BLD-DERM-01',
    buildingName: '0皮肤病医院门诊楼',
    defaultFloor: '2F',
    nursePhone: '7961102',
    adverseEventReporting: false,
    emergencyDeployment: false,
    defaultManager: '孙志强',
    status: 'active'
  },
  {
    id: '347',
    code: 'DEP-347',
    name: '皮肤病医院院长室',
    hospitalName: '五莲县皮肤病医院',
    disciplineCategory: '行政办公室',
    category: '行管后勤',
    functionType: '行管后勤',
    campusId: 'CAMPUS-02',
    campusName: '五莲县皮肤病医院',
    buildingId: 'BLD-DERM-01',
    buildingName: '0皮肤病医院门诊楼',
    defaultFloor: '2F',
    nursePhone: '7961102',
    adverseEventReporting: false,
    emergencyDeployment: false,
    defaultManager: '孙志强',
    status: 'active'
  },
  {
    id: '356',
    code: 'DEP-356',
    name: '皮肤病医院中医科病房',
    hospitalName: '五莲县皮肤病医院',
    disciplineCategory: '中医科',
    category: '临床',
    functionType: '临床',
    campusId: 'CAMPUS-02',
    campusName: '五莲县皮肤病医院',
    buildingId: 'BLD-DERM-01',
    buildingName: '0皮肤病医院门诊楼',
    defaultFloor: '2F',
    nursePhone: '7961101',
    adverseEventReporting: false,
    emergencyDeployment: false,
    defaultManager: '孙志强',
    status: 'active'
  },
  {
    id: '362',
    code: 'DEP-362',
    name: '皮肤病医院专家门诊',
    hospitalName: '五莲县皮肤病医院',
    disciplineCategory: '专家门诊',
    category: '临床',
    functionType: '临床',
    campusId: 'CAMPUS-02',
    campusName: '五莲县皮肤病医院',
    buildingId: 'BLD-DERM-01',
    buildingName: '0皮肤病医院门诊楼',
    defaultFloor: '2F',
    nursePhone: '7961101',
    adverseEventReporting: false,
    emergencyDeployment: false,
    defaultManager: '孙志强',
    status: 'active'
  },
  {
    id: '363',
    code: 'DEP-363',
    name: '皮肤病医院国医堂',
    hospitalName: '五莲县皮肤病医院',
    disciplineCategory: '中医科',
    category: '临床',
    functionType: '临床',
    campusId: 'CAMPUS-02',
    campusName: '五莲县皮肤病医院',
    buildingId: 'BLD-DERM-01',
    buildingName: '0皮肤病医院门诊楼',
    defaultFloor: '1F',
    nursePhone: '7961100',
    adverseEventReporting: false,
    emergencyDeployment: false,
    defaultManager: '孙志强',
    status: 'active'
  },
  {
    id: '352',
    code: 'DEP-352',
    name: '皮肤病医院检验科',
    hospitalName: '五莲县皮肤病医院',
    disciplineCategory: '医学检验科',
    category: '医技',
    functionType: '医技',
    campusId: 'CAMPUS-02',
    campusName: '五莲县皮肤病医院',
    buildingId: 'BLD-DERM-01',
    buildingName: '0皮肤病医院门诊楼',
    defaultFloor: '1F',
    nursePhone: '7961115',
    adverseEventReporting: false,
    emergencyDeployment: false,
    defaultManager: '孙志强',
    status: 'active'
  },
  {
    id: '351',
    code: 'DEP-351',
    name: '皮肤病医院美容科',
    hospitalName: '五莲县皮肤病医院',
    disciplineCategory: '医疗美容',
    category: '临床',
    functionType: '临床',
    campusId: 'CAMPUS-02',
    campusName: '五莲县皮肤病医院',
    buildingId: 'BLD-DERM-01',
    buildingName: '0皮肤病医院门诊楼',
    defaultFloor: '1F',
    nursePhone: '7991705',
    adverseEventReporting: false,
    emergencyDeployment: false,
    defaultManager: '孙志强',
    status: 'active'
  },
  {
    id: '350',
    code: 'DEP-350',
    name: '皮肤病医院门诊',
    hospitalName: '五莲县皮肤病医院',
    disciplineCategory: '门诊部',
    category: '临床',
    functionType: '临床',
    campusId: 'CAMPUS-02',
    campusName: '五莲县皮肤病医院',
    buildingId: 'BLD-DERM-01',
    buildingName: '0皮肤病医院门诊楼',
    defaultFloor: '1F',
    nursePhone: '7961112',
    adverseEventReporting: false,
    emergencyDeployment: false,
    defaultManager: '孙志强',
    status: 'active'
  },
  {
    id: '353',
    code: 'DEP-353',
    name: '皮肤病医院收款室',
    hospitalName: '五莲县皮肤病医院',
    disciplineCategory: '财务科',
    category: '行管后勤',
    functionType: '行管后勤',
    campusId: 'CAMPUS-02',
    campusName: '五莲县皮肤病医院',
    buildingId: 'BLD-DERM-01',
    buildingName: '0皮肤病医院门诊楼',
    defaultFloor: '1F',
    nursePhone: '7961115',
    adverseEventReporting: false,
    emergencyDeployment: false,
    defaultManager: '孙志强',
    status: 'active'
  },
  {
    id: '355',
    code: 'DEP-355',
    name: '皮肤病医院药房',
    hospitalName: '五莲县皮肤病医院',
    disciplineCategory: '药剂学',
    category: '临床',
    functionType: '临床',
    campusId: 'CAMPUS-02',
    campusName: '五莲县皮肤病医院',
    buildingId: 'BLD-DERM-01',
    buildingName: '0皮肤病医院门诊楼',
    defaultFloor: '1F',
    nursePhone: '7961112',
    adverseEventReporting: false,
    emergencyDeployment: false,
    defaultManager: '孙志强',
    status: 'active'
  }
];

// ==================== 4. 默认全域设备干系人与工程师主数据 (5大干系人集群) ====================
export const DEFAULT_STAFF: StaffPersonMaster[] = [
  // --- A. 院内医学工程保障集群 ---
  {
    id: 'STAFF-01',
    employeeNo: 'EMP-7001',
    name: '崔伟',
    stakeholderCategory: 'hospital_engineering',
    organization: '五莲县人民医院',
    departmentId: '303',
    departmentName: '医疗设备科',
    role: '维修工程师',
    phone: '7991237',
    email: 'cuiwei@hospital.wl.cn',
    title: '主管工程师 / 大型设备专管工程师',
    isPrimaryContact: true,
    specialties: ['放射影像 (CT/MRI/DR/DSA)', '放疗与核医学 (直线加速器/SPECT)'],
    serviceScope: '全院放射影像与核医学设备、DSA血管机维保调配',
    emergencyTier: 'L2',
    certifications: ['大型医用设备上岗证 (CT/MRI/DSA)', '辐射安全与防护培训合格证', '临床工程技师/主管技师职称'],
    credentials: [
      { certName: '大型医用设备上岗证 (CT/MRI/DSA)', certNo: 'SD-RAD-2023-0188', issuer: '国家卫健委能力建设中心', expireDate: '2027-12-31' },
      { certName: '辐射安全与防护培训合格证', certNo: 'ECO-FS-2024-099', issuer: '生态环境部核与辐射安全中心', expireDate: '2028-06-30' }
    ],
    status: 'active',
    notes: '分管1号楼影像中心、核医学科与急诊放射设备。'
  },
  {
    id: 'STAFF-02',
    employeeNo: 'EMP-7002',
    name: '孙志强',
    stakeholderCategory: 'hospital_engineering',
    organization: '五莲县人民医院',
    departmentId: '303',
    departmentName: '医疗设备科',
    role: '维修工程师',
    phone: '7991237',
    email: 'sunzhiqiang@hospital.wl.cn',
    title: '临床工程主管 / 抢修响应责任工程师',
    isPrimaryContact: true,
    specialties: ['急救生命支持 (呼吸机/除颤仪/监护仪)', '手术麻醉 (麻醉机/腔镜/高频电刀)', '血液净化 (血透机/CRRT/水处理系统)'],
    serviceScope: 'ICU/急诊/手术室急救生命支持类设备抢修与日常巡检',
    emergencyTier: 'L1',
    certifications: ['国家特种设备作业人员证 (压力容器)', '低压/高压电工特种作业操作证', '临床工程技师/主管技师职称'],
    credentials: [
      { certName: '特种设备安全管理与作业人员证', certNo: 'TS-SD-2022-8812', issuer: '市场监督管理局', expireDate: '2026-11-20' },
      { certName: '低压电工特种作业操作证', certNo: 'EM-LOW-9912', issuer: '应急管理局', expireDate: '2027-05-15' }
    ],
    status: 'active',
    notes: '24小时急救生命支持设备抢修第一联络人。'
  },
  {
    id: 'STAFF-03',
    employeeNo: 'EMP-7003',
    name: '赵敏',
    stakeholderCategory: 'hospital_engineering',
    organization: '五莲县人民医院',
    departmentId: '303',
    departmentName: '医疗设备科',
    role: '计量管理员',
    phone: '7991237',
    email: 'zhaomin@hospital.wl.cn',
    title: '法定计量专员 / 质量安全工程师',
    isPrimaryContact: true,
    specialties: ['急救生命支持 (呼吸机/除颤仪/监护仪)', '消毒供应与感控 (高压灭菌器/清洗机)'],
    serviceScope: '全院强检目录政策对标、法定计量器具定级复核与外部送检联络',
    emergencyTier: 'L2',
    certifications: ['注册计量检定员证 (医疗计量)', '临床工程技师/主管技师职称'],
    credentials: [
      { certName: '国家注册计量师职业资格证书 (二级)', certNo: 'MET-2023-0471', issuer: '人力资源社会保障部/市场监管总局', expireDate: '2028-09-30' }
    ],
    status: 'active'
  },
  {
    id: 'STAFF-04',
    employeeNo: 'EMP-7004',
    name: '李主任',
    stakeholderCategory: 'hospital_engineering',
    organization: '五莲县人民医院',
    departmentId: '303',
    departmentName: '医疗设备科',
    role: '质控主管',
    phone: '7991237',
    email: 'sbk@hospital.wl.cn',
    title: '医疗设备科主任 / 高级工程师',
    isPrimaryContact: true,
    specialties: ['放射影像 (CT/MRI/DR/DSA)', '手术麻醉 (麻醉机/腔镜/高频电刀)'],
    serviceScope: '全院医疗装备规划、立项论证审核与大型设备报废鉴定',
    emergencyTier: 'L2',
    certifications: ['临床工程技师/主管技师职称'],
    status: 'active'
  },
  {
    id: 'STAFF-05',
    employeeNo: 'EMP-7005',
    name: '李强',
    stakeholderCategory: 'hospital_engineering',
    organization: '五莲县人民医院',
    departmentId: '303',
    departmentName: '医疗设备科',
    role: '库管员',
    phone: '7991237',
    email: 'liqiang@hospital.wl.cn',
    title: '应急周转库管员 / 备品备件专员',
    isPrimaryContact: false,
    specialties: ['急救生命支持 (呼吸机/除颤仪/监护仪)', '病房基础护理 (输液泵/微量泵/防压疮床)'],
    serviceScope: '全院应急备用机出入库调配、周转机维护与维修备件进销存',
    emergencyTier: 'L1',
    status: 'active'
  },

  // --- B. 院内临床与医护应用集群 ---
  {
    id: 'STAFF-06',
    employeeNo: 'EMP-8001',
    name: '王建国',
    stakeholderCategory: 'hospital_clinical',
    organization: '五莲县人民医院',
    departmentId: '269',
    departmentName: '重症医学科',
    role: '科室主任',
    phone: '7991278',
    title: '主任医师 / 重症医学科科主任',
    email: 'wangjianguo@hospital.wl.cn',
    isPrimaryContact: true,
    specialties: ['急救生命支持 (呼吸机/除颤仪/监护仪)', '血液净化 (血透机/CRRT/水处理系统)'],
    emergencyTier: 'L1',
    status: 'active',
    notes: '分管ICU重症监护设备临床安全使用与立项采购。'
  },
  {
    id: 'STAFF-07',
    employeeNo: 'EMP-8002',
    name: '张敏敏',
    stakeholderCategory: 'hospital_clinical',
    organization: '五莲县人民医院',
    departmentId: '269',
    departmentName: '重症医学科',
    role: '护士长',
    phone: '7991278',
    title: '副主任护师 / ICU护士长',
    isPrimaryContact: true,
    specialties: ['急救生命支持 (呼吸机/除颤仪/监护仪)', '病房基础护理 (输液泵/微量泵/防压疮床)'],
    emergencyTier: 'L1',
    status: 'active',
    notes: 'ICU急救生命支持设备日常交接班保管与紧急报修责任人。'
  },
  {
    id: 'STAFF-08',
    employeeNo: 'EMP-8003',
    name: '宋文华',
    stakeholderCategory: 'hospital_clinical',
    organization: '五莲县人民医院',
    departmentId: '288',
    departmentName: '影像科',
    role: '科室主任',
    phone: '7991020',
    title: '主任医师 / 影像科科主任',
    isPrimaryContact: true,
    specialties: ['放射影像 (CT/MRI/DR/DSA)'],
    emergencyTier: 'L2',
    certifications: ['大型医用设备上岗证 (CT/MRI/DSA)', '辐射安全与防护培训合格证'],
    status: 'active'
  },
  {
    id: 'STAFF-09',
    employeeNo: 'EMP-8004',
    name: '孙海燕',
    stakeholderCategory: 'hospital_clinical',
    organization: '五莲县人民医院',
    departmentId: '288',
    departmentName: '影像科',
    role: '设备管理员',
    phone: '7991020',
    title: '主管技师 / 影像科技师长',
    isPrimaryContact: true,
    specialties: ['放射影像 (CT/MRI/DR/DSA)'],
    serviceScope: 'CT/MRI/DR机房设备台账管理、日常开机质控校准与故障首报',
    emergencyTier: 'L1',
    certifications: ['大型医用设备上岗证 (CT/MRI/DSA)', '辐射安全与防护培训合格证'],
    credentials: [
      { certName: '大型医用设备上岗合格证 (CT技师)', certNo: 'SD-MED-2022-772', issuer: '中华医学会影像技术分会', expireDate: '2027-10-31' }
    ],
    status: 'active'
  },
  {
    id: 'STAFF-10',
    employeeNo: 'EMP-8005',
    name: '王护士长',
    stakeholderCategory: 'hospital_clinical',
    organization: '五莲县人民医院',
    departmentId: '286',
    departmentName: '急诊科',
    role: '护士长',
    phone: '7991065',
    title: '急诊科主管护师',
    isPrimaryContact: true,
    specialties: ['急救生命支持 (呼吸机/除颤仪/监护仪)'],
    emergencyTier: 'L1',
    status: 'active'
  },
  {
    id: 'STAFF-10B',
    employeeNo: 'EMP-8007',
    name: '赵秀兰',
    stakeholderCategory: 'hospital_clinical',
    organization: '五莲县人民医院',
    departmentId: '290',
    departmentName: '麻醉手术科',
    role: '护士长',
    phone: '7991103',
    title: '麻醉手术科护士长 / 副主任护师',
    isPrimaryContact: true,
    specialties: ['手术麻醉 (麻醉机/腔镜/高频电刀)'],
    emergencyTier: 'L1',
    status: 'active'
  },
  {
    id: 'STAFF-10C',
    employeeNo: 'EMP-8008',
    name: '张雪梅',
    stakeholderCategory: 'hospital_clinical',
    organization: '五莲县人民医院',
    departmentId: '289',
    departmentName: '重症医学科',
    role: '护士长',
    phone: '7991278',
    title: 'ICU护士长 / 重症专科主管护师',
    isPrimaryContact: true,
    specialties: ['急救生命支持 (呼吸机/除颤仪/监护仪)', '输液与推注设备'],
    emergencyTier: 'L1',
    status: 'active'
  },
  {
    id: 'STAFF-10D',
    employeeNo: 'EMP-8009',
    name: '林护士长',
    stakeholderCategory: 'hospital_clinical',
    organization: '五莲县人民医院',
    departmentId: '292',
    departmentName: '妇科',
    role: '护士长',
    phone: '7991089',
    title: '妇产科病区护士长',
    isPrimaryContact: true,
    specialties: ['妇产科与基础监护'],
    emergencyTier: 'L1',
    status: 'active'
  },
  {
    id: 'STAFF-11',
    employeeNo: 'EMP-8006',
    name: '刘欣',
    stakeholderCategory: 'hospital_clinical',
    organization: '五莲县人民医院',
    departmentId: '290',
    departmentName: '麻醉手术科',
    role: '设备管理员',
    phone: '7991040',
    title: '副主任医师 / 手术室设备专管员',
    isPrimaryContact: true,
    specialties: ['手术麻醉 (麻醉机/腔镜/高频电刀)'],
    emergencyTier: 'L1',
    status: 'active'
  },

  // --- C. 院内行政与职能监管集群 (医务/护理/院感/财务/招标/保卫/信息/医保/审计等) ---
  {
    id: 'STAFF-ADM-01',
    employeeNo: 'EMP-ADM-01',
    name: '李科长',
    stakeholderCategory: 'hospital_administration',
    organization: '五莲县人民医院',
    departmentId: '331',
    departmentName: '医务科',
    role: '医务质控专员',
    phone: '7991112',
    email: 'ywk@hospital.wl.cn',
    title: '医务科科长 / 质控委员会副主任',
    isPrimaryContact: true,
    specialties: ['医务质控与临床新技术准入'],
    serviceScope: '全院大型医疗设备与新技术临床准入前置评估、医疗安全与不良事件多学科会审',
    emergencyTier: 'L1',
    status: 'active',
    notes: '医疗安全与临床应急保障第一行政召集人。'
  },
  {
    id: 'STAFF-ADM-02',
    employeeNo: 'EMP-ADM-02',
    name: '高主任',
    stakeholderCategory: 'hospital_administration',
    organization: '五莲县人民医院',
    departmentId: '321',
    departmentName: '感染管理科',
    role: '院感监测专员',
    phone: '7991215',
    email: 'ygk@hospital.wl.cn',
    title: '院感科主任 / 院感质控组长',
    isPrimaryContact: true,
    specialties: ['院感洗消与灭菌过程监测', '消毒供应与感控 (高压灭菌器/清洗机)'],
    serviceScope: '消毒供应中心灭菌锅生物监测、软式内窥镜洗消质控及全院感控合规巡查',
    emergencyTier: 'L2',
    certifications: ['医院感染管理专职人员培训合格证'],
    status: 'active'
  },
  {
    id: 'STAFF-ADM-03',
    employeeNo: 'EMP-ADM-03',
    name: '周会计',
    stakeholderCategory: 'hospital_administration',
    organization: '五莲县人民医院',
    departmentId: '319',
    departmentName: '财务科',
    role: '财务资产管理员',
    phone: '7991025',
    email: 'cwk@hospital.wl.cn',
    title: '资产会计主管 / 注册会计师',
    isPrimaryContact: true,
    specialties: ['固定资产账务、折旧与清查'],
    serviceScope: '全院医疗设备固定资产财务卡片建档、月度折旧计提、年度资产大清查与报废净值核销',
    emergencyTier: 'none',
    certifications: ['注册会计师/高级会计师资格证'],
    status: 'active'
  },
  {
    id: 'STAFF-ADM-04',
    employeeNo: 'EMP-ADM-04',
    name: '吴主管',
    stakeholderCategory: 'hospital_administration',
    organization: '五莲县人民医院',
    departmentId: '339',
    departmentName: '招标采购科',
    role: '招标采购主管',
    phone: '7991396',
    email: 'zbb@hospital.wl.cn',
    title: '采购办主任 / 招标师',
    isPrimaryContact: true,
    specialties: ['医疗设备招投标与采购商务'],
    serviceScope: '全院医疗装备政府采购公开招投标、供应商准入资信审查及设备买卖商务合同履约',
    emergencyTier: 'none',
    certifications: ['招标师/招投标采购职业能力等级证书'],
    status: 'active'
  },
  {
    id: 'STAFF-ADM-05',
    employeeNo: 'EMP-ADM-05',
    name: '刘工',
    stakeholderCategory: 'hospital_administration',
    organization: '五莲县人民医院',
    departmentId: '325',
    departmentName: '信息网络中心',
    role: '信息网络安全员',
    phone: '7991230',
    email: 'xxk@hospital.wl.cn',
    title: '高级网络安全工程师 / PACS管理员',
    isPrimaryContact: true,
    specialties: ['医疗物联网安全与PACS/DICOM接口'],
    serviceScope: '影像设备DICOM网络准入接入、医用物联网(IoMT)边界安全防护与HIS/PACS接口互联',
    emergencyTier: 'L2',
    certifications: ['注册信息安全专业人员(CISP/CISAW)'],
    status: 'active'
  },
  {
    id: 'STAFF-ADM-06',
    employeeNo: 'EMP-ADM-06',
    name: '孙队长',
    stakeholderCategory: 'hospital_administration',
    organization: '五莲县人民医院',
    departmentId: '322',
    departmentName: '保卫科',
    role: '消防安保负责人',
    phone: '7991110',
    email: 'bwk@hospital.wl.cn',
    title: '保卫科消防主管 / 注册消防工程师',
    isPrimaryContact: true,
    specialties: ['消防安保与放射源安全管理'],
    serviceScope: '高压氧舱、医用气体汇流排机房、直线加速器放射源库安防与消防联动定期演练',
    emergencyTier: 'L1',
    certifications: ['消防设施操作员/注册消防工程师'],
    status: 'active'
  },
  {
    id: 'STAFF-ADM-07',
    employeeNo: 'EMP-ADM-07',
    name: '钱督导',
    stakeholderCategory: 'hospital_administration',
    organization: '五莲县人民医院',
    departmentId: '323',
    departmentName: '护理部',
    role: '护理部专管员',
    phone: '7991406',
    email: 'hlb@hospital.wl.cn',
    title: '护理部副主任 / 主任护师',
    isPrimaryContact: true,
    specialties: ['护理急救设备全院督导与调配', '急救生命支持 (呼吸机/除颤仪/监护仪)'],
    serviceScope: '全院各护理单元抢救车设备日常完好率督查、护士除颤/呼吸机标准化操作考核与应急跨科借调',
    emergencyTier: 'L1',
    status: 'active'
  },

  // --- D. 生产厂家售后与销售集群 ---
  {
    id: 'STAFF-12',
    employeeNo: 'OEM-GE-01',
    name: '杜工',
    stakeholderCategory: 'oem_vendor',
    organization: '通用电气医疗系统 (GE Healthcare)',
    departmentId: '303',
    departmentName: '医疗设备科',
    role: '驻场原厂工程师',
    phone: '138-5321-8899',
    email: 'du.engineer@gehealthcare.com',
    title: '高级现场服务工程师 (FSE-Level 4)',
    isPrimaryContact: true,
    specialties: ['放射影像 (CT/MRI/DR/DSA)'],
    serviceScope: 'GE Revolution CT、Optima 1.5T MR 深度维保、大修调试与核心固件升级',
    emergencyTier: 'L3',
    certifications: ['原厂维修认证工程师证书 (Level 3/4)', '辐射安全与防护培训合格证'],
    credentials: [
      { certName: 'GE Healthcare Global CT/MR Level 4 Certified', certNo: 'GE-FSE-CN-2023-902', issuer: 'GE Healthcare Training Institute', expireDate: '2028-12-31' }
    ],
    serviceContractNo: 'HT-2025-GE-001',
    status: 'active',
    notes: '负责GE CT与MRI保内/保外深度维保与远程TAC诊断支持。'
  },
  {
    id: 'STAFF-13',
    employeeNo: 'OEM-GE-02',
    name: '陈经理',
    stakeholderCategory: 'oem_vendor',
    organization: '通用电气医疗系统 (GE Healthcare)',
    departmentId: '303',
    departmentName: '医疗设备科',
    role: '原厂售后/销售专员',
    phone: '139-6420-5566',
    email: 'chen.manager@gehealthcare.com',
    title: '鲁东大区售后服务经理 (CSM) / 商务专员',
    isPrimaryContact: false,
    specialties: ['放射影像 (CT/MRI/DR/DSA)'],
    serviceScope: 'GE全线设备维保合同续约、原厂配件现货调配、保修方案定制',
    emergencyTier: 'none',
    serviceContractNo: 'HT-2025-GE-001',
    status: 'active'
  },
  {
    id: 'STAFF-14',
    employeeNo: 'OEM-MR-01',
    name: '郑工',
    stakeholderCategory: 'oem_vendor',
    organization: '深圳迈瑞生物医疗电子股份有限公司',
    departmentId: '303',
    departmentName: '医疗设备科',
    role: '驻场原厂工程师',
    phone: '186-6988-1234',
    email: 'zheng.engineer@mindray.com',
    title: '驻点技术工程师 (FSE)',
    isPrimaryContact: true,
    specialties: ['急救生命支持 (呼吸机/除颤仪/监护仪)', '超声诊断 (彩超/超声刀/探头)'],
    serviceScope: '全院迈瑞监护仪、除颤监护仪、呼吸机、麻醉机专机维保与备件支持',
    emergencyTier: 'L3',
    certifications: ['原厂维修认证工程师证书 (Level 3/4)'],
    serviceContractNo: 'HT-2025-MINDRAY-002',
    status: 'active'
  },
  {
    id: 'STAFF-15',
    employeeNo: 'OEM-MR-02',
    name: '周敏',
    stakeholderCategory: 'oem_vendor',
    organization: '深圳迈瑞生物医疗电子股份有限公司',
    departmentId: '269',
    departmentName: '重症医学科',
    role: '临床应用培训专家(FAS)',
    phone: '185-6177-3344',
    email: 'zhou.fas@mindray.com',
    title: '临床应用培训专家 (FAS)',
    isPrimaryContact: false,
    specialties: ['急救生命支持 (呼吸机/除颤仪/监护仪)', '手术麻醉 (麻醉机/腔镜/高频电刀)'],
    serviceScope: '迈瑞高端呼吸机智能通气模式培训、心电监护高级参数设定与临床考核',
    emergencyTier: 'none',
    status: 'active'
  },

  // --- D. 第三方维保托管服务商集群 ---
  {
    id: 'STAFF-16',
    employeeNo: 'EXT-GY-01',
    name: '钱经理',
    stakeholderCategory: 'third_party_service',
    organization: '国药集团医疗器械托管服务部',
    departmentId: '303',
    departmentName: '医疗设备科',
    role: '三方维保工程师',
    phone: '137-0532-6688',
    email: 'qian.pm@sinopharm-med.cn',
    title: '驻场项目经理 / 维保调度主管',
    isPrimaryContact: true,
    specialties: ['病房基础护理 (输液泵/微量泵/防压疮床)', '消毒供应与感控 (高压灭菌器/清洗机)', '康复与物理治疗 (理疗仪/牵引床/水疗)'],
    serviceScope: '全院常规类、基础护理类设备预防性维护(PM)、定期巡检与应急周转调度',
    emergencyTier: 'L2',
    serviceContractNo: 'HT-2025-SINOPHARM-ALL',
    status: 'active'
  },
  {
    id: 'STAFF-17',
    employeeNo: 'EXT-GY-02',
    name: '冯工',
    stakeholderCategory: 'third_party_service',
    organization: '国药集团医疗器械托管服务部',
    departmentId: '303',
    departmentName: '医疗设备科',
    role: '三方维保工程师',
    phone: '136-1234-5678',
    title: '资深电子医疗设备工程师',
    isPrimaryContact: false,
    specialties: ['超声诊断 (彩超/超声刀/探头)', '内窥镜系统 (胃肠镜/支气管镜/洗消)'],
    serviceScope: '软性内窥镜气密性检测、超声探头阻抗测试与电源模块芯片级维修',
    emergencyTier: 'L2',
    certifications: ['低压/高压电工特种作业操作证'],
    serviceContractNo: 'HT-2025-SINOPHARM-ALL',
    status: 'active'
  },

  // --- E. 法定计量与特种监督检测机构集群 ---
  {
    id: 'STAFF-18',
    employeeNo: 'REG-JL-01',
    name: '严工',
    stakeholderCategory: 'metrology_regulatory',
    organization: '日照市质量技术监督评价所 (法定计量检定所)',
    departmentId: '303',
    departmentName: '医疗设备科',
    role: '法定计量检定专员',
    phone: '0633-8772155',
    email: 'yan.metrology@rz-quality.gov.cn',
    title: '副主任计量师 / 医疗强检主任检定员',
    isPrimaryContact: true,
    specialties: ['急救生命支持 (呼吸机/除颤仪/监护仪)', '放射影像 (CT/MRI/DR/DSA)'],
    serviceScope: '全院心电图机、多参数监护仪、脑电图机、除颤仪、医用注射泵法定强制检定',
    emergencyTier: 'none',
    certifications: ['注册计量检定员证 (医疗计量)'],
    credentials: [
      { certName: '国家一级注册计量师证书', certNo: 'MET-1ST-2021-0092', issuer: '国家市场监督管理总局', expireDate: '2029-04-30' }
    ],
    status: 'active',
    notes: '每年春季/秋季全院医疗器具强检主检工程师。'
  },
  {
    id: 'STAFF-19',
    employeeNo: 'REG-TJ-01',
    name: '贾工',
    stakeholderCategory: 'metrology_regulatory',
    organization: '山东省特种设备检验研究院 (特检院)',
    departmentId: '303',
    departmentName: '医疗设备科',
    role: '特种设备检验员',
    phone: '0531-88123344',
    title: '特种设备检验师 (压力容器类)',
    isPrimaryContact: true,
    specialties: ['消毒供应与感控 (高压灭菌器/清洗机)'],
    serviceScope: '消毒供应中心高压蒸汽灭菌器、医用氧舱、高压储气罐法定年度定期检验与安全附件校验',
    emergencyTier: 'none',
    certifications: ['国家特种设备作业人员证 (压力容器)'],
    credentials: [
      { certName: '特种设备检验人员证 (RD-2检验师)', certNo: 'SEI-SD-2022-331', issuer: '中国特种设备检验协会', expireDate: '2027-08-31' }
    ],
    status: 'active'
  }
];

// ==================== 5. 默认空间与具体工作场所主数据 (Workplaces & Rooms) ====================
export const DEFAULT_ROOMS: LocationRoomMaster[] = DEFAULT_WORKPLACES;

// ==================== 6. 辅助查询与持久化工具函数 ====================
export const MASTER_DATA_STORAGE_KEYS = {
  CAMPUSES: 'hospital-master-campuses-v2',
  BUILDINGS: 'hospital-master-buildings-v2',
  ROOMS: 'hospital-master-rooms-v2',
  DEPARTMENTS: 'hospital-master-departments-v2',
  STAFF: 'hospital-master-staff-v2'
};

export function loadMasterData() {
  const loadItem = <T>(key: string, fallback: T): T => {
    try {
      const saved = localStorage.getItem(key);
      if (saved) {
        const parsed = JSON.parse(saved);
        if (Array.isArray(parsed) && parsed.length > 0) return parsed as T;
      }
    } catch (e) {
      console.warn(`Failed to parse master data from ${key}`, e);
    }
    return fallback;
  };

  return {
    campuses: loadItem<CampusMaster[]>(MASTER_DATA_STORAGE_KEYS.CAMPUSES, DEFAULT_CAMPUSES),
    buildings: loadItem<BuildingMaster[]>(MASTER_DATA_STORAGE_KEYS.BUILDINGS, DEFAULT_BUILDINGS),
    rooms: loadItem<LocationRoomMaster[]>(MASTER_DATA_STORAGE_KEYS.ROOMS, DEFAULT_ROOMS),
    departments: loadItem<DepartmentMaster[]>(MASTER_DATA_STORAGE_KEYS.DEPARTMENTS, DEFAULT_DEPARTMENTS),
    staff: loadItem<StaffPersonMaster[]>(MASTER_DATA_STORAGE_KEYS.STAFF, DEFAULT_STAFF)
  };
}

export function saveMasterData(
  campuses?: CampusMaster[],
  buildings?: BuildingMaster[],
  rooms?: LocationRoomMaster[],
  departments?: DepartmentMaster[],
  staff?: StaffPersonMaster[]
) {
  try {
    if (campuses) localStorage.setItem(MASTER_DATA_STORAGE_KEYS.CAMPUSES, JSON.stringify(campuses));
    if (buildings) localStorage.setItem(MASTER_DATA_STORAGE_KEYS.BUILDINGS, JSON.stringify(buildings));
    if (rooms) localStorage.setItem(MASTER_DATA_STORAGE_KEYS.ROOMS, JSON.stringify(rooms));
    if (departments) localStorage.setItem(MASTER_DATA_STORAGE_KEYS.DEPARTMENTS, JSON.stringify(departments));
    if (staff) localStorage.setItem(MASTER_DATA_STORAGE_KEYS.STAFF, JSON.stringify(staff));
  } catch (e) {
    console.warn('Failed to save master data to localStorage', e);
  }
}

/**
 * 根据科室名称获取匹配的标准科室配置（带电话、默认楼宇、责任人）
 */
export function getDepartmentProfile(deptName: string, deptList: DepartmentMaster[]): DepartmentMaster | undefined {
  if (!deptName) return undefined;
  return deptList.find(d => d.name === deptName || deptName.includes(d.name) || d.name.includes(deptName));
}

/**
 * 计算每个科室在设备台账中的实际分布台数
 */
export function computeDepartmentEquipmentCounts(departments: DepartmentMaster[], equipmentList: MedicalEquipment[]): DepartmentMaster[] {
  const counts: Record<string, number> = {};
  for (const eq of equipmentList) {
    const d = eq.department || '未分配';
    counts[d] = (counts[d] || 0) + 1;
  }

  return departments.map(dept => ({
    ...dept,
    equipmentCount: counts[dept.name] || 0
  }));
}

export interface ResolvedDepartmentInfo {
  department: string;
  building: string;
  floor: string;
  nursePhone: string;
  manager: string;
  category?: string;
  disciplineCategory?: string;
  matchedDept?: DepartmentMaster;
}

/**
 * 智能解析科室主数据：提供高精度的名称匹配、别名推导与标准护士站电话/楼宇/楼层联动
 */
export function getDepartmentMasterInfo(
  deptName?: string,
  customDepartments?: DepartmentMaster[]
): ResolvedDepartmentInfo {
  const depts = (customDepartments && customDepartments.length > 0) ? customDepartments : DEFAULT_DEPARTMENTS;
  if (!deptName || !deptName.trim()) {
    return {
      department: '全院科室',
      building: '1号楼 综合楼',
      floor: '1',
      nursePhone: '7991100',
      manager: '崔伟'
    };
  }

  const raw = deptName.trim();
  const clean = raw.replace(/^(五莲县人民医院|五莲县皮肤病医院|总院|分院)/, '').trim();

  // 1. Exact match by name
  let found = depts.find(d => d.name === raw || d.name === clean);

  // 2. Exact match by code or ID
  if (!found) {
    found = depts.find(d => d.code === raw || d.id === raw);
  }

  // 3. Known Aliases / Common Clinical Names
  if (!found) {
    const aliasMap: Record<string, string> = {
      'CT室': '影像科',
      '放射科': '影像科',
      '磁共振室': '影像科',
      'MR室': '影像科',
      'DR室': '影像科',
      '放射影像科': '影像科',
      '医学影像科': '影像科',
      '超声': '超声科',
      '彩超室': '超声科',
      'B超室': '超声科',
      'B超': '超声科',
      'ICU': '重症医学科',
      '重症监护室': '重症医学科',
      '重症监护': '重症医学科',
      '手术室': '麻醉手术科',
      '麻醉科': '麻醉手术科',
      '手术麻醉科': '麻醉手术科',
      '血透室': '血液透析室',
      '血液透析': '血液透析室',
      '血透': '血液透析室',
      '急诊': '急诊科',
      '急诊抢救室': '急诊科',
      '急诊抢救': '急诊科',
      '120': '急救站',
      '院前急救': '急救站',
      '急救中心': '急救站',
      '神经内科': '神经内一科',
      '神内': '神经内一科',
      '神内一科': '神经内一科',
      '神内二科': '神经内二科',
      '心内科': '心血管内一科',
      '心内一科': '心血管内一科',
      '心内二科': '心血管内二科',
      '心血管内科': '心血管内一科',
      '呼吸内科': '呼吸与危重症医学科',
      '呼吸科': '呼吸与危重症医学科',
      '消化内科': '消化保健科',
      '消化科': '消化保健科',
      '内分泌科': '内分泌风湿肾病科',
      '肾内科': '内分泌风湿肾病科',
      '风湿免疫科': '内分泌风湿肾病科',
      '普外科': '普外一科',
      '骨科': '骨一科',
      '骨外科': '骨一科',
      '神外科': '神经外科',
      '创伤科': '创伤外科',
      '肿瘤科': '肿瘤血液科',
      '血液科': '肿瘤血液科',
      '泌尿科': '泌尿外科',
      '五官科': '眼耳鼻喉科',
      '耳鼻喉科': '眼耳鼻喉科',
      '检验': '检验科',
      '化验室': '检验科',
      '妇产科': '产科',
      '产房': '产科',
      '儿科病区': '儿科',
      '设备科': '医疗设备应急库',
      '器械科': '医疗设备应急库',
      '医学工程科': '医疗设备应急库',
      '设备管理科': '医疗设备应急库',
      '应急库': '医疗设备应急库',
      '皮防站': '皮肤病医院办公室',
      '皮肤科': '皮肤病门诊'
    };

    const targetName = aliasMap[raw] || aliasMap[clean];
    if (targetName) {
      found = depts.find(d => d.name === targetName);
    }
  }

  // 4. Substring / Includes matching
  if (!found) {
    found = depts.find(d => raw.includes(d.name) || d.name.includes(raw) || clean.includes(d.name) || d.name.includes(clean));
  }

  if (found) {
    return {
      department: found.name,
      building: found.buildingName || '1号楼 综合楼',
      floor: found.defaultFloor?.replace(/F$/i, '') || '1',
      nursePhone: found.nursePhone || '7991100',
      manager: found.defaultManager || '崔伟',
      category: found.category,
      disciplineCategory: found.disciplineCategory,
      matchedDept: found
    };
  }

  return {
    department: raw,
    building: '1号楼 综合楼',
    floor: '1',
    nursePhone: '7991100',
    manager: '崔伟'
  };
}

/**
 * 将设备台账记录与科室主数据深度关联、补全并同步电话、楼宇及楼层
 */
export function enrichEquipmentWithMasterData(
  equipment: MedicalEquipment,
  customDepartments?: DepartmentMaster[],
  forceSyncAll = false
): MedicalEquipment {
  const info = getDepartmentMasterInfo(equipment.department, customDepartments);
  
  const shouldUpdatePhone = forceSyncAll || !equipment.nursePhone || equipment.nursePhone.trim() === '' || equipment.nursePhone === '-';
  const shouldUpdateBuilding = forceSyncAll || !equipment.building || equipment.building.trim() === '' || equipment.building === '-';
  const shouldUpdateFloor = forceSyncAll || !equipment.floor || equipment.floor.trim() === '' || equipment.floor === '-';

  return {
    ...equipment,
    nursePhone: shouldUpdatePhone ? info.nursePhone : equipment.nursePhone,
    building: shouldUpdateBuilding ? info.building : equipment.building,
    floor: shouldUpdateFloor ? info.floor : equipment.floor,
    manager: (!equipment.manager || equipment.manager === '管理员' || equipment.manager === '张工') && info.manager ? info.manager : equipment.manager
  };
}
