import { LocationRoomMaster } from '../types';

/**
 * 医院标准化具体工作场所/安装点主数据 (Workplaces & Precise Installation Locations)
 * 涵盖：ID_场所信息、ID_科室信息、名称、办公电话、短号、院区、楼宇、楼层及空间类型
 */
export const RAW_WORKPLACES_DATA: Array<{
  workplaceId: string;
  departmentName: string;
  roomName: string;
  officePhone: string;
  shortPhone: string;
  roomType?: '诊室' | '手术室' | '病房' | '抢救室' | '检验中心' | '医技检查室' | '设备库房' | '办公区' | '机房动力' | '治疗室' | '门诊';
}> = [
  { workplaceId: '300', departmentName: '皮肤病医院办公室', roomName: '皮防站办公室', officePhone: '7961100', shortPhone: '53100', roomType: '办公区' },
  { workplaceId: '301', departmentName: '皮肤病医院门诊', roomName: '皮防站专家门诊', officePhone: '7961101', shortPhone: '53101', roomType: '诊室' },
  { workplaceId: '302', departmentName: '皮肤病医院中医科病房', roomName: '皮防站中医科病房', officePhone: '7991127', shortPhone: '53101', roomType: '病房' },
  { workplaceId: '303', departmentName: '皮肤病医院院长室', roomName: '皮防站院长室', officePhone: '7961102', shortPhone: '53102', roomType: '办公区' },
  { workplaceId: '304', departmentName: '皮肤病医院财务科', roomName: '皮防站财务科', officePhone: '7961103', shortPhone: '53103', roomType: '办公区' },
  { workplaceId: '305', departmentName: '皮肤病医院收款室', roomName: '皮防站国医堂挂号室', officePhone: '7961106', shortPhone: '53106', roomType: '办公区' },
  { workplaceId: '306', departmentName: '皮肤病医院收款室', roomName: '皮防站国医堂收款室', officePhone: '7961108', shortPhone: '53108', roomType: '办公区' },
  { workplaceId: '307', departmentName: '皮肤病医院门诊', roomName: '皮防站皮肤病门诊', officePhone: '7961112', shortPhone: '53112', roomType: '诊室' },
  { workplaceId: '308', departmentName: '皮肤病医院检验科', roomName: '皮防站检验科', officePhone: '7961115', shortPhone: '53115', roomType: '检验中心' },
  { workplaceId: '309', departmentName: '皮肤病医院药房', roomName: '皮防站药房', officePhone: '7961116', shortPhone: '53116', roomType: '设备库房' },
  { workplaceId: '310', departmentName: '皮肤病医院皮肤病病房', roomName: '皮防站皮肤病护士病房', officePhone: '7961117', shortPhone: '53117', roomType: '病房' },
  { workplaceId: '311', departmentName: '皮肤病医院收款室', roomName: '皮防站收款室', officePhone: '7961128', shortPhone: '53128', roomType: '办公区' },
  { workplaceId: '312', departmentName: '院办公室', roomName: '院办公室党建办', officePhone: '7991000', shortPhone: '56000', roomType: '办公区' },
  { workplaceId: '313', departmentName: '领导办公室', roomName: '党委书记室', officePhone: '7991001', shortPhone: '', roomType: '办公区' },
  { workplaceId: '314', departmentName: '领导办公室', roomName: '院长室', officePhone: '7991002', shortPhone: '56002', roomType: '办公区' },
  { workplaceId: '315', departmentName: '领导办公室', roomName: '副院长1室', officePhone: '7991008', shortPhone: '', roomType: '办公区' },
  { workplaceId: '316', departmentName: '领导办公室', roomName: '院长助理', officePhone: '7991009', shortPhone: '', roomType: '办公区' },
  { workplaceId: '317', departmentName: '领导办公室', roomName: '副院长2室', officePhone: '7991010', shortPhone: '', roomType: '办公区' },
  { workplaceId: '318', departmentName: '呼吸与危重症医学科', roomName: '呼吸与危重症医学科医生办1', officePhone: '7991012', shortPhone: '56012', roomType: '办公区' },
  { workplaceId: '319', departmentName: '信息科', roomName: '信息科信息中心办公室', officePhone: '7991021', shortPhone: '', roomType: '办公区' },
  { workplaceId: '320', departmentName: '后勤保障部', roomName: '后勤保障部办公用品仓库', officePhone: '7991022', shortPhone: '', roomType: '设备库房' },
  { workplaceId: '321', departmentName: '后勤保障部', roomName: '后勤保障部消保水电办', officePhone: '7991023', shortPhone: '56023', roomType: '机房动力' },
  { workplaceId: '322', departmentName: '财务科', roomName: '财务科财务室', officePhone: '7991025', shortPhone: '', roomType: '办公区' },
  { workplaceId: '323', departmentName: '财务科', roomName: '财务科主任办', officePhone: '7991026', shortPhone: '56026', roomType: '办公区' },
  { workplaceId: '324', departmentName: '审计科', roomName: '审计科审计室', officePhone: '7991027', shortPhone: '56027', roomType: '办公区' },
  { workplaceId: '325', departmentName: '后勤保障部', roomName: '后勤保障部物资采供主任办', officePhone: '7991028', shortPhone: '', roomType: '办公区' },
  { workplaceId: '326', departmentName: '审计科', roomName: '审计科主任办', officePhone: '7991028', shortPhone: '56028', roomType: '办公区' },
  { workplaceId: '327', departmentName: '药剂科', roomName: '药剂科主任办', officePhone: '7991030', shortPhone: '56030', roomType: '办公区' },
  { workplaceId: '328', departmentName: '医务科', roomName: '医务科质控室', officePhone: '7991032', shortPhone: '', roomType: '办公区' },
  { workplaceId: '329', departmentName: '预防保健科', roomName: '预防保健科', officePhone: '7991032', shortPhone: '56032', roomType: '门诊' },
  { workplaceId: '330', departmentName: '重症医学科', roomName: '重症医学科医生办', officePhone: '7991033', shortPhone: '', roomType: '办公区' },
  { workplaceId: '331', departmentName: '信息科', roomName: '信息科信息中心1', officePhone: '7991034', shortPhone: '', roomType: '机房动力' },
  { workplaceId: '332', departmentName: '信息科', roomName: '信息科主任办', officePhone: '7991035', shortPhone: '56035', roomType: '办公区' },
  { workplaceId: '333', departmentName: '消化保健科', roomName: '消化保健科医生办', officePhone: '7991037', shortPhone: '', roomType: '办公区' },
  { workplaceId: '334', departmentName: '消化保健科', roomName: '消化保健科护士站', officePhone: '7991038', shortPhone: '56038', roomType: '办公区' },
  { workplaceId: '335', departmentName: '医疗安全科', roomName: '医疗安全科Ⅰ室', officePhone: '7991039', shortPhone: '', roomType: '办公区' },
  { workplaceId: '336', departmentName: '消化保健科', roomName: '消化保健科主任办', officePhone: '7991049', shortPhone: '', roomType: '办公区' },
  { workplaceId: '337', departmentName: '医疗设备科', roomName: '医疗设备科氧气房', officePhone: '7991050', shortPhone: '56050', roomType: '机房动力' },
  { workplaceId: '338', departmentName: '院办公室', roomName: '院办公室作风办', officePhone: '7991051', shortPhone: '', roomType: '办公区' },
  { workplaceId: '339', departmentName: '院办公室', roomName: '院办公室主任办', officePhone: '7991052', shortPhone: '', roomType: '办公区' },
  { workplaceId: '340', departmentName: '康复医学科', roomName: '康复医学科康复治疗厅', officePhone: '7991055', shortPhone: '', roomType: '治疗室' },
  { workplaceId: '341', departmentName: '神经内一科', roomName: '神经内一科主任办', officePhone: '7991056', shortPhone: '56056', roomType: '办公区' },
  { workplaceId: '342', departmentName: '神经内一科', roomName: '神经内一科护士长办', officePhone: '7991057', shortPhone: '', roomType: '办公区' },
  { workplaceId: '343', departmentName: '神经内一科', roomName: '神经内一科医生办', officePhone: '7991058', shortPhone: '', roomType: '办公区' },
  { workplaceId: '344', departmentName: '综合保健科', roomName: '综合保健科主任办', officePhone: '7991059', shortPhone: '56059', roomType: '办公区' },
  { workplaceId: '345', departmentName: '综合保健科', roomName: '综合保健科一楼医生办', officePhone: '7991060', shortPhone: '', roomType: '办公区' },
  { workplaceId: '346', departmentName: '综合保健科', roomName: '综合保健科一楼护士站', officePhone: '7991061', shortPhone: '', roomType: '办公区' },
  { workplaceId: '347', departmentName: '放疗科', roomName: '放疗科医生办', officePhone: '7991062', shortPhone: '56062', roomType: '办公区' },
  { workplaceId: '348', departmentName: '放疗科', roomName: '放疗科主任办', officePhone: '7991063', shortPhone: '56063', roomType: '办公区' },
  { workplaceId: '349', departmentName: '后勤保障部', roomName: '后勤保障部日用品耗材物资仓库', officePhone: '7991066', shortPhone: '', roomType: '设备库房' },
  { workplaceId: '350', departmentName: '重症医学科', roomName: '重症医学科主任办', officePhone: '7991067', shortPhone: '56067', roomType: '办公区' },
  { workplaceId: '351', departmentName: '心血管内一科', roomName: '心血管内一科主任办', officePhone: '7991069', shortPhone: '56069', roomType: '办公区' },
  { workplaceId: '352', departmentName: '急诊科', roomName: '急诊科护士长办', officePhone: '7991070', shortPhone: '56070', roomType: '办公区' },
  { workplaceId: '353', departmentName: '心血管内一科', roomName: '心血管内一科护士长办', officePhone: '7991071', shortPhone: '56071', roomType: '办公区' },
  { workplaceId: '354', departmentName: '中医科', roomName: '中医科医生办', officePhone: '7991072', shortPhone: '56072', roomType: '办公区' },
  { workplaceId: '355', departmentName: '中医科', roomName: '中医科护士长办', officePhone: '', shortPhone: '', roomType: '办公区' },
  { workplaceId: '356', departmentName: '消化保健科', roomName: '消化保健科护士长办', officePhone: '7991077', shortPhone: '', roomType: '办公区' },
  { workplaceId: '357', departmentName: '神经外科', roomName: '神经外科主任办', officePhone: '7991079', shortPhone: '56079', roomType: '办公区' },
  { workplaceId: '358', departmentName: '神经外科', roomName: '神经外科医生办', officePhone: '7991080', shortPhone: '56080', roomType: '办公区' },
  { workplaceId: '359', departmentName: '妇科', roomName: '妇科医生办', officePhone: '7991087', shortPhone: '56087', roomType: '办公区' },
  { workplaceId: '360', departmentName: '妇科', roomName: '妇科主任办', officePhone: '7991087', shortPhone: '56087', roomType: '办公区' },
  { workplaceId: '361', departmentName: '宣教科', roomName: '宣教科办公室', officePhone: '7991088', shortPhone: '56088', roomType: '办公区' },
  { workplaceId: '362', departmentName: '妇科', roomName: '妇科护士站', officePhone: '7991089', shortPhone: '56089', roomType: '办公区' },
  { workplaceId: '363', departmentName: '妇科', roomName: '妇科护士长办', officePhone: '7991089', shortPhone: '56089', roomType: '办公区' },
  { workplaceId: '364', departmentName: '麻醉手术科', roomName: '麻醉手术科中心换药室', officePhone: '7991090', shortPhone: '', roomType: '治疗室' },
  { workplaceId: '365', departmentName: '妇科', roomName: '妇科流产室', officePhone: '7991091', shortPhone: '56091', roomType: '手术室' },
  { workplaceId: '366', departmentName: '普外二科', roomName: '普外二科医生办', officePhone: '7991092', shortPhone: '56092', roomType: '办公区' },
  { workplaceId: '367', departmentName: '普外二科', roomName: '普外二科主任办', officePhone: '7991092', shortPhone: '56092', roomType: '办公区' },
  { workplaceId: '368', departmentName: '普外二科', roomName: '普外二科护士长办', officePhone: '7991093', shortPhone: '56093', roomType: '办公区' },
  { workplaceId: '369', departmentName: '骨一科', roomName: '骨一科医生办1', officePhone: '7991095', shortPhone: '', roomType: '办公区' },
  { workplaceId: '370', departmentName: '骨一科', roomName: '骨一科护士站', officePhone: '7991097', shortPhone: '', roomType: '办公区' },
  { workplaceId: '371', departmentName: '骨一科', roomName: '骨一科医生办2', officePhone: '7991098', shortPhone: '', roomType: '办公区' },
  { workplaceId: '372', departmentName: '骨一科', roomName: '骨一科护士长办', officePhone: '7991099', shortPhone: '56099', roomType: '办公区' },
  { workplaceId: '373', departmentName: '麻醉手术科', roomName: '麻醉手术科主任办', officePhone: '7991101', shortPhone: '56101', roomType: '办公区' },
  { workplaceId: '374', departmentName: '麻醉手术科', roomName: '麻醉手术科医生办', officePhone: '7991102', shortPhone: '56102', roomType: '办公区' },
  { workplaceId: '375', departmentName: '麻醉手术科', roomName: '麻醉手术科护士站', officePhone: '7991103', shortPhone: '', roomType: '办公区' },
  { workplaceId: '376', departmentName: '五官科', roomName: '五官科护士长办', officePhone: '7991105', shortPhone: '56105', roomType: '办公区' },
  { workplaceId: '377', departmentName: '内镜室', roomName: '内镜室护士站', officePhone: '7991106', shortPhone: '56106', roomType: '医技检查室' },
  { workplaceId: '378', departmentName: '健康服务科', roomName: '健康服务科内科', officePhone: '7991110', shortPhone: '56110', roomType: '诊室' },
  { workplaceId: '379', departmentName: '医务科', roomName: '医务科办公室', officePhone: '7991112', shortPhone: '', roomType: '办公区' },
  { workplaceId: '380', departmentName: '医务科', roomName: '医务科主任办', officePhone: '7991113', shortPhone: '56113', roomType: '办公区' },
  { workplaceId: '381', departmentName: '医疗安全科', roomName: '医疗安全科Ⅱ室', officePhone: '7991116', shortPhone: '', roomType: '办公区' },
  { workplaceId: '382', departmentName: '急诊科', roomName: '急诊科门诊手术室', officePhone: '7991120', shortPhone: '56251', roomType: '手术室' },
  { workplaceId: '383', departmentName: '医共体', roomName: '医共体办公室', officePhone: '7991120', shortPhone: '56120', roomType: '办公区' },
  { workplaceId: '384', departmentName: '影像科', roomName: '影像科登记室', officePhone: '7991126', shortPhone: '56126', roomType: '医技检查室' },
  { workplaceId: '385', departmentName: '超声科', roomName: '超声科彩超1室', officePhone: '7991130', shortPhone: '56130', roomType: '医技检查室' },
  { workplaceId: '386', departmentName: '超声科', roomName: '超声科彩超2室', officePhone: '7991131', shortPhone: '56131', roomType: '医技检查室' },
  { workplaceId: '387', departmentName: '超声科', roomName: '超声科彩超5室', officePhone: '7991131', shortPhone: '', roomType: '医技检查室' },
  { workplaceId: '388', departmentName: '超声科', roomName: '超声科彩超3室', officePhone: '7991133', shortPhone: '56133', roomType: '医技检查室' },
  { workplaceId: '389', departmentName: '影像科', roomName: '影像科磁共振2室', officePhone: '7991135', shortPhone: '56135', roomType: '医技检查室' },
  { workplaceId: '390', departmentName: '产科', roomName: '产科护士长办', officePhone: '7991140', shortPhone: '56140', roomType: '办公区' },
  { workplaceId: '391', departmentName: '产科', roomName: '产科产一主任办', officePhone: '7991141', shortPhone: '56141', roomType: '办公区' },
  { workplaceId: '392', departmentName: '小儿科', roomName: '小儿科护士站', officePhone: '7991142', shortPhone: '56142', roomType: '办公区' },
  { workplaceId: '393', departmentName: '产科', roomName: '产科产二主任办', officePhone: '7991145', shortPhone: '56145', roomType: '办公区' },
  { workplaceId: '394', departmentName: '理疗科', roomName: '理疗科门诊', officePhone: '7991152', shortPhone: '', roomType: '诊室' },
  { workplaceId: '395', departmentName: '医疗设备科', roomName: '医疗设备科仓库库房', officePhone: '7991153', shortPhone: '', roomType: '设备库房' },
  { workplaceId: '396', departmentName: '检验科', roomName: '检验科临检组', officePhone: '7991155', shortPhone: '56155', roomType: '检验中心' },
  { workplaceId: '397', departmentName: '医务科', roomName: '医务科司法鉴定办公Ⅱ室', officePhone: '7991156', shortPhone: '', roomType: '办公区' },
  { workplaceId: '398', departmentName: '检验科', roomName: '检验科血库', officePhone: '7991157', shortPhone: '', roomType: '检验中心' },
  { workplaceId: '399', departmentName: '医务科', roomName: '医务科司法鉴定办公Ⅰ室', officePhone: '7991158', shortPhone: '', roomType: '办公区' },
  { workplaceId: '400', departmentName: '检验科', roomName: '检验科主任办', officePhone: '7991159', shortPhone: '56159', roomType: '办公区' },
  { workplaceId: '401', departmentName: '检验科', roomName: '检验科PCR室', officePhone: '7991160', shortPhone: '', roomType: '检验中心' },
  { workplaceId: '402', departmentName: '功能检查科', roomName: '功能检查科心电图室', officePhone: '7991161', shortPhone: '56161', roomType: '医技检查室' },
  { workplaceId: '403', departmentName: '血液透析室', roomName: '血液透析室主任办', officePhone: '7991162', shortPhone: '56162', roomType: '办公区' },
  { workplaceId: '404', departmentName: '检验科', roomName: '检验科病理室', officePhone: '7991163', shortPhone: '', roomType: '检验中心' },
  { workplaceId: '405', departmentName: '功能检查科', roomName: '功能检查科动态心电图室', officePhone: '7991166', shortPhone: '56166', roomType: '医技检查室' },
  { workplaceId: '406', departmentName: '健康服务科', roomName: '健康服务科彩超Ⅰ室', officePhone: '7991167', shortPhone: '56167', roomType: '医技检查室' },
  { workplaceId: '407', departmentName: '皮肤科', roomName: '皮防站皮肤科主任办', officePhone: '7991168', shortPhone: '56168', roomType: '办公区' },
  { workplaceId: '408', departmentName: '口腔科', roomName: '口腔科主任办', officePhone: '7991169', shortPhone: '', roomType: '办公区' },
  { workplaceId: '409', departmentName: '耳鼻喉科', roomName: '耳鼻喉科主任办', officePhone: '7991170', shortPhone: '', roomType: '办公区' },
  { workplaceId: '410', departmentName: '功能检查科', roomName: '功能检查科脑电图室', officePhone: '7991171', shortPhone: '56171', roomType: '医技检查室' },
  { workplaceId: '411', departmentName: '健康服务科', roomName: '健康服务科资料室', officePhone: '7991175', shortPhone: '56175', roomType: '办公区' },
  { workplaceId: '412', departmentName: '药剂科', roomName: '药剂科药库办公室1', officePhone: '7991176', shortPhone: '', roomType: '设备库房' },
  { workplaceId: '413', departmentName: '药剂科', roomName: '药剂科药库办公室2', officePhone: '7991177', shortPhone: '', roomType: '设备库房' },
  { workplaceId: '414', departmentName: '药剂科', roomName: '药剂科煎药室', officePhone: '7991178', shortPhone: '', roomType: '治疗室' },
  { workplaceId: '415', departmentName: '药剂科', roomName: '药剂科临床药学室', officePhone: '7991180', shortPhone: '', roomType: '办公区' },
  { workplaceId: '416', departmentName: '神经内二科', roomName: '神经内二科主任办', officePhone: '7991181', shortPhone: '56181', roomType: '办公区' },
  { workplaceId: '417', departmentName: '检验科', roomName: '检验科细菌组', officePhone: '7991182', shortPhone: '', roomType: '检验中心' },
  { workplaceId: '418', departmentName: '后勤保障部', roomName: '后勤保障部综合楼水电暖值班', officePhone: '7991185', shortPhone: '', roomType: '机房动力' },
  { workplaceId: '419', departmentName: '医保科', roomName: '医保科档案管理', officePhone: '7991186', shortPhone: '56186', roomType: '办公区' },
  { workplaceId: '420', departmentName: '医保科', roomName: '医保科医保稽查', officePhone: '7991186', shortPhone: '', roomType: '办公区' },
  { workplaceId: '421', departmentName: '医保科', roomName: '医保科主任办', officePhone: '7991186', shortPhone: '56186', roomType: '办公区' },
  { workplaceId: '422', departmentName: '内分泌风湿肾病科', roomName: '内分泌风湿肾病科医生办2', officePhone: '7991188', shortPhone: '', roomType: '办公区' },
  { workplaceId: '423', departmentName: '内分泌风湿肾病科', roomName: '内分泌风湿肾病科护士长办', officePhone: '7991189', shortPhone: '56189', roomType: '办公区' },
  { workplaceId: '424', departmentName: '门诊输液室', roomName: '输液室护士站', officePhone: '7991195', shortPhone: '56195', roomType: '治疗室' },
  { workplaceId: '425', departmentName: '重症医学科', roomName: '重症医学科护士长办', officePhone: '7991196', shortPhone: '56196', roomType: '办公区' },
  { workplaceId: '426', departmentName: '医疗设备科', roomName: '医疗设备科仓库办公室', officePhone: '7991199', shortPhone: '56199', roomType: '设备库房' },
  { workplaceId: '427', departmentName: '院办公室', roomName: '院办公室办公室1', officePhone: '7991208', shortPhone: '', roomType: '办公区' },
  { workplaceId: '428', departmentName: '院办公室', roomName: '院办公室传真室', officePhone: '7991211', shortPhone: '56211', roomType: '办公区' },
  { workplaceId: '429', departmentName: '医务科', roomName: '医务科病案室办公Ⅰ室', officePhone: '7991213', shortPhone: '', roomType: '办公区' },
  { workplaceId: '430', departmentName: '感染管理科', roomName: '感染管理科主任办', officePhone: '7991215', shortPhone: '56215', roomType: '办公区' },
  { workplaceId: '431', departmentName: '护理部', roomName: '护理部主任办', officePhone: '7991217', shortPhone: '56217', roomType: '办公区' },
  { workplaceId: '432', departmentName: '后勤保障部', roomName: '后勤保障部消防控制室监控室', officePhone: '7991221', shortPhone: '', roomType: '机房动力' },
  { workplaceId: '433', departmentName: '后勤保障部', roomName: '后勤保障部综合办公室', officePhone: '7991222', shortPhone: '56222', roomType: '办公区' },
  { workplaceId: '434', departmentName: '呼吸与危重症医学科', roomName: '呼吸与危重症医学科护士长办', officePhone: '7991225', shortPhone: '', roomType: '办公区' },
  { workplaceId: '435', departmentName: '综合保健科', roomName: '综合保健科护士长办', officePhone: '7991229', shortPhone: '56229', roomType: '办公区' },
  { workplaceId: '436', departmentName: '五官科', roomName: '五官科护士站', officePhone: '7991232', shortPhone: '', roomType: '办公区' },
  { workplaceId: '437', departmentName: '医疗设备科', roomName: '医疗设备科主任办', officePhone: '7991236', shortPhone: '56236', roomType: '办公区' },
  { workplaceId: '438', departmentName: '医疗设备科', roomName: '医疗设备科维修室', officePhone: '7991237', shortPhone: '56237', roomType: '机房动力' },
  { workplaceId: '439', departmentName: '神经内二科', roomName: '神经内二科医生办', officePhone: '7991238', shortPhone: '', roomType: '办公区' },
  { workplaceId: '440', departmentName: '小儿科', roomName: '小儿科医生办', officePhone: '7991245', shortPhone: '', roomType: '办公区' },
  { workplaceId: '441', departmentName: '感染性疾病科', roomName: '感染性疾病科主任办', officePhone: '7991246', shortPhone: '', roomType: '办公区' },
  { workplaceId: '442', departmentName: '感染性疾病科', roomName: '感染性疾病科护士站', officePhone: '7991247', shortPhone: '', roomType: '办公区' },
  { workplaceId: '443', departmentName: '院办公室', roomName: '院办公室司机办', officePhone: '7991251', shortPhone: '', roomType: '办公区' },
  { workplaceId: '444', departmentName: '中医科', roomName: '中医科主任办', officePhone: '7991253', shortPhone: '56253', roomType: '办公区' },
  { workplaceId: '445', departmentName: '心理咨询门诊', roomName: '心理咨询门诊', officePhone: '7991262', shortPhone: '', roomType: '诊室' },
  { workplaceId: '446', departmentName: '消化保健科', roomName: '消化保健科特保门诊', officePhone: '7991265', shortPhone: '', roomType: '诊室' },
  { workplaceId: '447', departmentName: '骨二科', roomName: '骨二科主任办', officePhone: '7991275', shortPhone: '', roomType: '办公区' },
  { workplaceId: '448', departmentName: '骨二科', roomName: '骨二科医生办', officePhone: '7991276', shortPhone: '56276', roomType: '办公区' },
  { workplaceId: '449', departmentName: '骨二科', roomName: '骨二科护士站', officePhone: '7991277', shortPhone: '56277', roomType: '办公区' },
  { workplaceId: '450', departmentName: '重症医学科', roomName: '重症医学科护士站', officePhone: '7991278', shortPhone: '', roomType: '抢救室' },
  { workplaceId: '451', departmentName: '泌尿胸普外科', roomName: '泌尿胸普外科医生办', officePhone: '7991279', shortPhone: '', roomType: '办公区' },
  { workplaceId: '452', departmentName: '泌尿胸普外科', roomName: '泌尿胸普外科护士长办', officePhone: '7991280', shortPhone: '56280', roomType: '办公区' },
  { workplaceId: '453', departmentName: '泌尿胸普外科', roomName: '泌尿胸普外科主任办', officePhone: '7991283', shortPhone: '56283', roomType: '办公区' },
  { workplaceId: '454', departmentName: '放疗科', roomName: '放疗科技术员办公室', officePhone: '7991286', shortPhone: '56286', roomType: '医技检查室' },
  { workplaceId: '455', departmentName: '放疗科', roomName: '放疗科加速器室', officePhone: '7991287', shortPhone: '56287', roomType: '医技检查室' },
  { workplaceId: '456', departmentName: '急救站', roomName: '急救站主任办', officePhone: '7991288', shortPhone: '56288', roomType: '办公区' },
  { workplaceId: '457', departmentName: '急救站', roomName: '急救站调度室', officePhone: '7991289', shortPhone: '56289', roomType: '抢救室' },
  { workplaceId: '458', departmentName: '新生儿科', roomName: '新生儿科医生办', officePhone: '7991295', shortPhone: '56295', roomType: '办公区' },
  { workplaceId: '459', departmentName: '母婴保健科', roomName: '母婴保健科新生儿筛选', officePhone: '7991296', shortPhone: '56296', roomType: '诊室' },
  { workplaceId: '460', departmentName: '急诊科', roomName: '急诊科内科接诊室', officePhone: '7991297', shortPhone: '56297', roomType: '抢救室' },
  { workplaceId: '461', departmentName: '母婴保健科', roomName: '母婴保健科护士办', officePhone: '7991300', shortPhone: '56300', roomType: '办公区' },
  { workplaceId: '462', departmentName: '母婴保健科', roomName: '母婴保健科孕保门诊', officePhone: '7991302', shortPhone: '56302', roomType: '诊室' },
  { workplaceId: '463', departmentName: '检验科', roomName: '检验科采血组', officePhone: '7991305', shortPhone: '', roomType: '检验中心' },
  { workplaceId: '464', departmentName: '母婴保健科', roomName: '母婴保健科出生证明', officePhone: '7991308', shortPhone: '', roomType: '办公区' },
  { workplaceId: '465', departmentName: '母婴保健科', roomName: '母婴保健科产后门诊', officePhone: '7991309', shortPhone: '56309', roomType: '诊室' },
  { workplaceId: '466', departmentName: '母婴保健科', roomName: '母婴保健科护士长办', officePhone: '7991313', shortPhone: '56313', roomType: '办公区' },
  { workplaceId: '467', departmentName: '产科', roomName: '产科产一医生办', officePhone: '7991317', shortPhone: '56322', roomType: '办公区' },
  { workplaceId: '468', departmentName: '产科', roomName: '产科产一护士站', officePhone: '7991318', shortPhone: '56318', roomType: '办公区' },
  { workplaceId: '469', departmentName: '产科', roomName: '产科产二医生办', officePhone: '7991322', shortPhone: '56322', roomType: '办公区' },
  { workplaceId: '470', departmentName: '产科', roomName: '产科产二护士站', officePhone: '7991323', shortPhone: '56323', roomType: '办公区' },
  { workplaceId: '471', departmentName: '产房手术室', roomName: '产房手术室护士站', officePhone: '7991326', shortPhone: '66326', roomType: '手术室' },
  { workplaceId: '472', departmentName: '产房', roomName: '产房隔离分娩室', officePhone: '7991327', shortPhone: '56327', roomType: '手术室' },
  { workplaceId: '473', departmentName: '产房', roomName: '产房分娩室I间', officePhone: '7991336', shortPhone: '56336', roomType: '手术室' },
  { workplaceId: '474', departmentName: '产房', roomName: '产房待产室I间', officePhone: '7991351', shortPhone: '56351', roomType: '病房' },
  { workplaceId: '475', departmentName: '消毒供应室', roomName: '消毒供应室护士长办', officePhone: '7991353', shortPhone: '56353', roomType: '办公区' },
  { workplaceId: '476', departmentName: '新生儿科', roomName: '新生儿科主任办', officePhone: '7991355', shortPhone: '56355', roomType: '办公区' },
  { workplaceId: '477', departmentName: '新生儿科', roomName: '新生儿科西护士站（母婴同室）', officePhone: '7991357', shortPhone: '', roomType: '病房' },
  { workplaceId: '478', departmentName: '新生儿科', roomName: '新生儿科护士长办', officePhone: '7991358', shortPhone: '', roomType: '办公区' },
  { workplaceId: '479', departmentName: '急救站', roomName: '急救站护士长办', officePhone: '7991359', shortPhone: '56359', roomType: '办公区' },
  { workplaceId: '480', departmentName: '后勤保障部', roomName: '后勤保障部消保水电主任办', officePhone: '7991362', shortPhone: '56362', roomType: '机房动力' },
  { workplaceId: '481', departmentName: '综合保健科', roomName: '综合保健科PICC门诊', officePhone: '7991363', shortPhone: '', roomType: '诊室' },
  { workplaceId: '482', departmentName: '绩效考核科', roomName: '绩效考核科办公室', officePhone: '7991366', shortPhone: '56366', roomType: '办公区' },
  { workplaceId: '483', departmentName: '内分泌风湿肾病科', roomName: '内分泌风湿肾病科医生办', officePhone: '7991368', shortPhone: '56368', roomType: '办公区' },
  { workplaceId: '484', departmentName: '药剂科', roomName: '药剂科液体库', officePhone: '7991371', shortPhone: '', roomType: '设备库房' },
  { workplaceId: '485', departmentName: '后勤保障部', roomName: '后勤保障部设施维护办', officePhone: '7991373', shortPhone: '', roomType: '机房动力' },
  { workplaceId: '488', departmentName: '宣教科', roomName: '宣教科主任办', officePhone: '7991378', shortPhone: '56378', roomType: '办公区' },
  { workplaceId: '489', departmentName: '小儿科', roomName: '小儿科主任室', officePhone: '7991379', shortPhone: '', roomType: '办公区' },
  { workplaceId: '490', departmentName: '心血管内二科', roomName: '心血管内二科护士长办', officePhone: '7991380', shortPhone: '56380', roomType: '办公区' },
  { workplaceId: '491', departmentName: '心血管内二科', roomName: '心血管内二科主任办', officePhone: '7991381', shortPhone: '56381', roomType: '办公区' },
  { workplaceId: '492', departmentName: '药剂科', roomName: '药剂科片剂库', officePhone: '7991382', shortPhone: '', roomType: '设备库房' },
  { workplaceId: '493', departmentName: '影像科', roomName: '影像科CT扫描1室', officePhone: '7991387', shortPhone: '', roomType: '医技检查室' },
  { workplaceId: '494', departmentName: '疼痛门诊', roomName: '疼痛门诊', officePhone: '7991389', shortPhone: '', roomType: '诊室' },
  { workplaceId: '495', departmentName: '药剂科', roomName: '药剂科针剂库', officePhone: '7991391', shortPhone: '', roomType: '设备库房' },
  { workplaceId: '496', departmentName: '药剂科', roomName: '药剂科中药库', officePhone: '7991393', shortPhone: '', roomType: '设备库房' },
  { workplaceId: '497', departmentName: '扶贫办', roomName: '扶贫办', officePhone: '7991396', shortPhone: '56396', roomType: '办公区' },
  { workplaceId: '498', departmentName: '门诊部', roomName: '门诊部主任办', officePhone: '7991397', shortPhone: '56397', roomType: '办公区' },
  { workplaceId: '499', departmentName: '门诊部', roomName: '门诊部预约挂号', officePhone: '7991398', shortPhone: '', roomType: '办公区' },
  { workplaceId: '500', departmentName: '内镜室', roomName: '内镜室护士长办', officePhone: '7991402', shortPhone: '56402', roomType: '医技检查室' },
  { workplaceId: '501', departmentName: '呼吸与危重症医学科', roomName: '呼吸与危重症医学科医生办2', officePhone: '7991404', shortPhone: '', roomType: '办公区' },
  { workplaceId: '502', departmentName: '护理部', roomName: '护理部办公室', officePhone: '7991406', shortPhone: '56406', roomType: '办公区' },
  { workplaceId: '503', departmentName: '神经内二科', roomName: '神经内二科护士长办', officePhone: '7991407', shortPhone: '', roomType: '办公区' },
  { workplaceId: '504', departmentName: '医疗设备科', roomName: '医疗设备科会计室', officePhone: '7991408', shortPhone: '56408', roomType: '办公区' },
  { workplaceId: '505', departmentName: '超声科', roomName: '超声科登记室', officePhone: '7991417', shortPhone: '', roomType: '医技检查室' },
  { workplaceId: '506', departmentName: '内镜室', roomName: '内镜室洗消室', officePhone: '7991420', shortPhone: '56420', roomType: '治疗室' },
  { workplaceId: '507', departmentName: '心血管内一科', roomName: '心血管内一科医生办', officePhone: '7991422', shortPhone: '56422', roomType: '办公区' },
  { workplaceId: '508', departmentName: '内镜室', roomName: '内镜室胃肠镜室', officePhone: '7991423', shortPhone: '56423', roomType: '医技检查室' },
  { workplaceId: '509', departmentName: '急诊科', roomName: '急诊科外科接诊室', officePhone: '7991426', shortPhone: '56426', roomType: '抢救室' },
  { workplaceId: '511', departmentName: '内分泌风湿肾病科', roomName: '内分泌风湿肾病科护士站', officePhone: '7991438', shortPhone: '', roomType: '办公区' },
  { workplaceId: '512', departmentName: '检验科', roomName: '检验科生化组', officePhone: '7991440', shortPhone: '', roomType: '检验中心' },
  { workplaceId: '513', departmentName: '医保科', roomName: '医保科医保会计', officePhone: '7991449', shortPhone: '', roomType: '办公区' },
  { workplaceId: '514', departmentName: '门诊输液室', roomName: '输液室护士长办', officePhone: '7991451', shortPhone: '56451', roomType: '治疗室' },
  { workplaceId: '515', departmentName: '功能检查科', roomName: '功能检查科主任办', officePhone: '7991452', shortPhone: '56452', roomType: '办公区' },
  { workplaceId: '516', departmentName: '超声科', roomName: '超声科主任办', officePhone: '7991453', shortPhone: '', roomType: '办公区' },
  { workplaceId: '517', departmentName: '功能检查科', roomName: '功能检查科平板试验室', officePhone: '7991454', shortPhone: '56454', roomType: '医技检查室' },
  { workplaceId: '518', departmentName: '院办公室', roomName: '院办公室办公室2', officePhone: '7991456', shortPhone: '', roomType: '办公区' },
  { workplaceId: '519', departmentName: '放疗科', roomName: '放疗科物理室', officePhone: '7991464', shortPhone: '56464', roomType: '医技检查室' },
  { workplaceId: '520', departmentName: '小儿科', roomName: '小儿科护士长办', officePhone: '7991468', shortPhone: '56468', roomType: '办公区' },
  { workplaceId: '521', departmentName: '超声科', roomName: '超声科彩超4室', officePhone: '7991473', shortPhone: '56473', roomType: '医技检查室' },
  { workplaceId: '522', departmentName: '功能检查科', roomName: '功能检查科肌电图室', officePhone: '7991474', shortPhone: '56474', roomType: '医技检查室' },
  { workplaceId: '523', departmentName: '健康服务科', roomName: '健康服务科彩超Ⅱ室', officePhone: '7991478', shortPhone: '56478', roomType: '医技检查室' },
  { workplaceId: '524', departmentName: '健康服务科', roomName: '健康服务科检验', officePhone: '7991479', shortPhone: '56479', roomType: '检验中心' },
  { workplaceId: '525', departmentName: '健康服务科', roomName: '健康服务科主任办', officePhone: '7991480', shortPhone: '56480', roomType: '办公区' },
  { workplaceId: '526', departmentName: '临床营养科', roomName: '临床营养科', officePhone: '7991481', shortPhone: '56481', roomType: '诊室' },
  { workplaceId: '527', departmentName: '健康服务科', roomName: '健康服务科外科', officePhone: '7991482', shortPhone: '56482', roomType: '诊室' },
  { workplaceId: '528', departmentName: '麻醉手术科', roomName: '麻醉手术科护士长办', officePhone: '7991487', shortPhone: '56487', roomType: '办公区' },
  { workplaceId: '529', departmentName: '门诊部', roomName: '门诊部预约挂号1', officePhone: '7991491', shortPhone: '56491', roomType: '办公区' },
  { workplaceId: '530', departmentName: '消毒供应室', roomName: '消毒供应室护士办', officePhone: '7991493', shortPhone: '56493', roomType: '办公区' },
  { workplaceId: '531', departmentName: '眼科', roomName: '眼科视光学门诊', officePhone: '7991494', shortPhone: '56494', roomType: '诊室' },
  { workplaceId: '532', departmentName: '消毒供应室', roomName: '消毒供应室检查包装区', officePhone: '7991495', shortPhone: '56495', roomType: '机房动力' },
  { workplaceId: '533', departmentName: '中医不孕不育门诊', roomName: '中医不孕不育门诊', officePhone: '7991496', shortPhone: '', roomType: '诊室' },
  { workplaceId: '534', departmentName: '健康服务科', roomName: '健康服务科心电图', officePhone: '7991499', shortPhone: '56499', roomType: '医技检查室' },
  { workplaceId: '535', departmentName: '医务科', roomName: '医务科病案室办公Ⅱ室', officePhone: '7991546', shortPhone: '', roomType: '办公区' },
  { workplaceId: '536', departmentName: '呼吸与危重症医学科', roomName: '内镜室肺功能室', officePhone: '', shortPhone: '', roomType: '医技检查室' },
  { workplaceId: '537', departmentName: '内镜室', roomName: '内镜室支气管镜室', officePhone: '7991586', shortPhone: '', roomType: '医技检查室' },
  { workplaceId: '538', departmentName: '内镜室', roomName: '内镜室宫腔镜', officePhone: '7991587', shortPhone: '', roomType: '医技检查室' },
  { workplaceId: '539', departmentName: '急诊科', roomName: '急诊科EICU护士站', officePhone: '7991598', shortPhone: '51598', roomType: '抢救室' },
  { workplaceId: '540', departmentName: '理疗科', roomName: '理疗科病房', officePhone: '7991599', shortPhone: '56599', roomType: '病房' },
  { workplaceId: '541', departmentName: '普外一科', roomName: '普外小儿外科主任办', officePhone: '7991666', shortPhone: '51666', roomType: '办公区' },
  { workplaceId: '542', departmentName: '理疗科', roomName: '理疗科主任办', officePhone: '7991677', shortPhone: '', roomType: '办公区' },
  { workplaceId: '543', departmentName: '普外一科', roomName: '普外小儿外科医生办', officePhone: '7991678', shortPhone: '56678', roomType: '办公区' },
  { workplaceId: '544', departmentName: '普外一科', roomName: '普外小儿外科护士长办', officePhone: '7991688', shortPhone: '51688', roomType: '办公区' },
  { workplaceId: '545', departmentName: '影像科', roomName: '影像科CT扫描2室', officePhone: '7991702', shortPhone: '56702', roomType: '医技检查室' },
  { workplaceId: '546', departmentName: '骨二科', roomName: '骨二科护士长办', officePhone: '7991703', shortPhone: '56703', roomType: '办公区' },
  { workplaceId: '547', departmentName: '皮肤病医院美容科', roomName: '皮防站美容科', officePhone: '7991705', shortPhone: '56705', roomType: '诊室' },
  { workplaceId: '548', departmentName: '医疗安全科', roomName: '医疗安全科回访室回访工位Ⅱ', officePhone: '7991711', shortPhone: '', roomType: '办公区' },
  { workplaceId: '549', departmentName: '医疗安全科', roomName: '医疗安全科回访室回访工位Ⅰ', officePhone: '7991712', shortPhone: '', roomType: '办公区' },
  { workplaceId: '550', departmentName: '医疗安全科', roomName: '医疗安全科回访室回访工位Ⅲ', officePhone: '7991718', shortPhone: '', roomType: '办公区' },
  { workplaceId: '551', departmentName: '康复医学科', roomName: '康复医学科护士长办', officePhone: '7991721', shortPhone: '56721', roomType: '办公区' },
  { workplaceId: '552', departmentName: '康复医学科', roomName: '康复医学科医生办', officePhone: '7991722', shortPhone: '', roomType: '办公区' },
  { workplaceId: '553', departmentName: '科教科', roomName: '科教科', officePhone: '7991723', shortPhone: '57723', roomType: '办公区' },
  { workplaceId: '554', departmentName: '康复医学科', roomName: '康复医学科主任办', officePhone: '7991729', shortPhone: '', roomType: '办公区' },
  { workplaceId: '555', departmentName: '骨一科', roomName: '骨一科主任办', officePhone: '7991730', shortPhone: '', roomType: '办公区' },
  { workplaceId: '556', departmentName: '急诊科', roomName: '急诊科护士站', officePhone: '', shortPhone: '', roomType: '抢救室' },
  { workplaceId: '557', departmentName: '急诊科', roomName: '急诊科主任办', officePhone: '', shortPhone: '', roomType: '办公区' },
  { workplaceId: '558', departmentName: '神经外科', roomName: '神经外科护士站', officePhone: '', shortPhone: '', roomType: '办公区' },
  { workplaceId: '559', departmentName: '收费结算科', roomName: '收费结算科主任办', officePhone: '', shortPhone: '', roomType: '办公区' },
  { workplaceId: '560', departmentName: '影像科', roomName: '影像科DR拍片1室', officePhone: '', shortPhone: '', roomType: '医技检查室' },
  { workplaceId: '561', departmentName: '影像科', roomName: '影像科数字胃肠1室', officePhone: '', shortPhone: '', roomType: '医技检查室' },
  { workplaceId: '562', departmentName: '影像科', roomName: '影像科阅片室', officePhone: '', shortPhone: '', roomType: '医技检查室' },
  { workplaceId: '563', departmentName: '影像科', roomName: '影像科主任办', officePhone: '', shortPhone: '', roomType: '办公区' },
  { workplaceId: '564', departmentName: '影像科', roomName: '影像科办公室', officePhone: '', shortPhone: '', roomType: '办公区' },
  { workplaceId: '565', departmentName: '收费结算科', roomName: '收费结算科住院结算', officePhone: '', shortPhone: '', roomType: '办公区' },
  { workplaceId: '566', departmentName: '人事科', roomName: '人事科主任办', officePhone: '', shortPhone: '56218', roomType: '办公区' },
  { workplaceId: '567', departmentName: '人事科', roomName: '人事科老干部管理科', officePhone: '', shortPhone: '56219', roomType: '办公区' },
  { workplaceId: '568', departmentName: '眼科', roomName: '眼科病房', officePhone: '', shortPhone: '', roomType: '病房' },
  { workplaceId: '569', departmentName: '药剂科', roomName: '药剂科住院药房', officePhone: '', shortPhone: '', roomType: '设备库房' },
  { workplaceId: '570', departmentName: '眼科', roomName: '眼科主任办', officePhone: '', shortPhone: '', roomType: '办公区' },
  { workplaceId: '571', departmentName: '心血管内二科', roomName: '心血管内二科护士站', officePhone: '', shortPhone: '', roomType: '办公区' },
  { workplaceId: '572', departmentName: '心血管内二科', roomName: '心血管内二科医生办', officePhone: '', shortPhone: '', roomType: '办公区' },
  { workplaceId: '573', departmentName: '药剂科', roomName: '药剂科西药房', officePhone: '', shortPhone: '', roomType: '设备库房' },
  { workplaceId: '574', departmentName: '药剂科', roomName: '药剂科中药房', officePhone: '', shortPhone: '', roomType: '设备库房' },
  { workplaceId: '575', departmentName: '呼吸与危重症医学科', roomName: '呼吸与危重症医学科护士站', officePhone: '', shortPhone: '', roomType: '办公区' },
  { workplaceId: '576', departmentName: '神经外科', roomName: '神经外科护士长办', officePhone: '', shortPhone: '', roomType: '办公区' },
  { workplaceId: '577', departmentName: '介入放射科', roomName: '介入放射科主任办', officePhone: '', shortPhone: '', roomType: '办公区' },
  { workplaceId: '578', departmentName: '药剂科', roomName: '药剂科中心摆药室', officePhone: '', shortPhone: '', roomType: '治疗室' },
  { workplaceId: '597', departmentName: '院办公室', roomName: '院办公室司机室', officePhone: '5213159', shortPhone: '', roomType: '办公区' },
  { workplaceId: '598', departmentName: '信息科', roomName: '信息科办公楼机房', officePhone: '7991207', shortPhone: '56207', roomType: '机房动力' },
  { workplaceId: '599', departmentName: '收费结算科', roomName: '收费结算科夜间值班室', officePhone: '7991107', shortPhone: '56107', roomType: '办公区' },
  { workplaceId: '600', departmentName: '后勤保障部', roomName: '后勤保障部后勤保障部24小时服务电话', officePhone: '7991221', shortPhone: '56221', roomType: '机房动力' },
  { workplaceId: '601', departmentName: '后勤保障部', roomName: '后勤保障部北大门警务室', officePhone: '7991183', shortPhone: '56183', roomType: '办公区' },
  { workplaceId: '602', departmentName: '医务科', roomName: '质量管理办公室评审办公室', officePhone: '7991121', shortPhone: '56121', roomType: '办公区' },
  { workplaceId: '603', departmentName: '医共体', roomName: '医共体远程会诊中心', officePhone: '7991725', shortPhone: '56725', roomType: '诊室' },
  { workplaceId: '604', departmentName: '康复医学科', roomName: '康复医学科高压氧舱治疗室', officePhone: '7991676', shortPhone: '51676', roomType: '治疗室' },
  { workplaceId: '605', departmentName: '呼吸与危重症医学科', roomName: '呼吸与危重症医学科医生值班室', officePhone: '7991223', shortPhone: '56223', roomType: '办公区' },
  { workplaceId: '606', departmentName: '呼吸与危重症医学科', roomName: '呼吸与危重症医学科监护室', officePhone: '7991706', shortPhone: '56706', roomType: '病房' },
  { workplaceId: '607', departmentName: '神经外科', roomName: '神经外科监护病房', officePhone: '7991720', shortPhone: '56720', roomType: '病房' },
  { workplaceId: '608', departmentName: '神经外科', roomName: '神经外科医生值班室', officePhone: '7991282', shortPhone: '56282', roomType: '办公区' },
  { workplaceId: '610', departmentName: '麻醉手术科', roomName: '麻醉手术科手术室门口', officePhone: '7991200', shortPhone: '56200', roomType: '手术室' },
  { workplaceId: '612', departmentName: '产房手术室', roomName: '产房手术室医生办', officePhone: '7991329', shortPhone: '56329', roomType: '办公区' },
  { workplaceId: '613', departmentName: '产房手术室', roomName: '产房手术室男值班室', officePhone: '7991328', shortPhone: '56328', roomType: '办公区' },
  { workplaceId: '614', departmentName: '产房手术室', roomName: '产房手术室女值班室', officePhone: '7991333', shortPhone: '56333', roomType: '办公区' },
  { workplaceId: '615', departmentName: '产房手术室', roomName: '产房手术室换鞋处', officePhone: '7991252', shortPhone: '56252', roomType: '手术室' },
  { workplaceId: '616', departmentName: '产房手术室', roomName: '产房手术室污物间', officePhone: '7991330', shortPhone: '56330', roomType: '手术室' },
  { workplaceId: '617', departmentName: '新生儿科', roomName: '新生儿科新生儿专线', officePhone: '7991202', shortPhone: '56202', roomType: '病房' },
  { workplaceId: '618', departmentName: '新生儿科', roomName: '新生儿科会议室', officePhone: '7991361', shortPhone: '56361', roomType: '办公区' },
  { workplaceId: '619', departmentName: '感染性疾病科', roomName: '感染性疾病科三楼护士站', officePhone: '7991248', shortPhone: '56248', roomType: '办公区' },
  { workplaceId: '620', departmentName: '感染性疾病科', roomName: '感染性疾病科肝病门诊', officePhone: '7991249', shortPhone: '56249', roomType: '诊室' },
  { workplaceId: '621', departmentName: '感染性疾病科', roomName: '感染性疾病科艾滋病门诊', officePhone: '7991243', shortPhone: '56243', roomType: '诊室' },
  { workplaceId: '622', departmentName: '感染性疾病科', roomName: '感染性疾病科发热门诊', officePhone: '7991241', shortPhone: '56241', roomType: '诊室' },
  { workplaceId: '623', departmentName: '感染性疾病科', roomName: '感染性疾病科结核病门诊', officePhone: '7991709', shortPhone: '56709', roomType: '诊室' },
  { workplaceId: '624', departmentName: '五官科', roomName: '五官科医生办', officePhone: '7991235', shortPhone: '56235', roomType: '办公区' },
  { workplaceId: '625', departmentName: '五官科', roomName: '五官科医生值班室', officePhone: '7991100', shortPhone: '56100', roomType: '办公区' },
  { workplaceId: '626', departmentName: '急诊科', roomName: '急诊科EICU医生值班室', officePhone: '7991661', shortPhone: '51661', roomType: '抢救室' },
  { workplaceId: '627', departmentName: '小儿科', roomName: '儿科门诊I室', officePhone: '7991151', shortPhone: '56151', roomType: '诊室' },
  { workplaceId: '628', departmentName: '小儿科', roomName: '儿科中医特色门诊', officePhone: '7991726', shortPhone: '56726', roomType: '诊室' },
  { workplaceId: '629', departmentName: '门诊部', roomName: '神经内科门诊', officePhone: '7991412', shortPhone: '56412', roomType: '诊室' },
  { workplaceId: '630', departmentName: '门诊部', roomName: '呼吸风湿免疫门诊', officePhone: '7991139', shortPhone: '56139', roomType: '诊室' },
  { workplaceId: '631', departmentName: '消化保健科', roomName: '消化保健科门诊', officePhone: '7991109', shortPhone: '56109', roomType: '诊室' },
  { workplaceId: '632', departmentName: '门诊部', roomName: '内分泌肾病科门诊', officePhone: '7991042', shortPhone: '56042', roomType: '诊室' },
  { workplaceId: '633', departmentName: '门诊部', roomName: '心内科门诊', officePhone: '7991310', shortPhone: '56310', roomType: '诊室' },
  { workplaceId: '634', departmentName: '门诊部', roomName: '资深专家门诊1', officePhone: '7991382', shortPhone: '56382', roomType: '诊室' },
  { workplaceId: '635', departmentName: '门诊部', roomName: '便民门诊', officePhone: '7991470', shortPhone: '56470', roomType: '诊室' },
  { workplaceId: '636', departmentName: '门诊部', roomName: '资深专家门诊3', officePhone: '7990138', shortPhone: '56138', roomType: '诊室' },
  { workplaceId: '637', departmentName: '神经外科', roomName: '神经外科门诊', officePhone: '7991111', shortPhone: '56111', roomType: '诊室' },
  { workplaceId: '638', departmentName: '门诊部', roomName: '普外小儿外科门诊', officePhone: '7991119', shortPhone: '56119', roomType: '诊室' },
  { workplaceId: '639', departmentName: '门诊部', roomName: '泌尿胸普外科门诊', officePhone: '7991399', shortPhone: '56399', roomType: '诊室' },
  { workplaceId: '640', departmentName: '骨一科', roomName: '骨一科门诊', officePhone: '7991730', shortPhone: '56731', roomType: '诊室' },
  { workplaceId: '641', departmentName: '骨二科', roomName: '骨二科门诊', officePhone: '7991369', shortPhone: '56369', roomType: '诊室' },
  { workplaceId: '642', departmentName: '妇科', roomName: '妇科门诊', officePhone: '7991136', shortPhone: '56136', roomType: '诊室' },
  { workplaceId: '643', departmentName: '产科', roomName: '产科门诊Ⅰ室', officePhone: '7991137', shortPhone: '56137', roomType: '诊室' },
  { workplaceId: '644', departmentName: '产科', roomName: '产科门诊Ⅱ室', officePhone: '7991469', shortPhone: '56469', roomType: '诊室' },
  { workplaceId: '645', departmentName: '消化保健科', roomName: '特保门诊', officePhone: '7991265', shortPhone: '56265', roomType: '诊室' },
  { workplaceId: '646', departmentName: '门诊部', roomName: '中医科门诊', officePhone: '7991203', shortPhone: '56203', roomType: '诊室' },
  { workplaceId: '647', departmentName: '中医科', roomName: '中医科体外碎石治疗室', officePhone: '7991337', shortPhone: '56337', roomType: '治疗室' },
  { workplaceId: '648', departmentName: '骨一科', roomName: '骨一科冲击波治疗室', officePhone: '7991403', shortPhone: '56403', roomType: '治疗室' },
  { workplaceId: '649', departmentName: '门诊部', roomName: 'PICC门诊', officePhone: '7991363', shortPhone: '56363', roomType: '诊室' },
  { workplaceId: '651', departmentName: '眼科', roomName: '眼科门诊', officePhone: '7996165', shortPhone: '56165', roomType: '诊室' },
  { workplaceId: '652', departmentName: '超声科', roomName: '超声科医生办', officePhone: '7991129', shortPhone: '56129', roomType: '医技检查室' },
  { workplaceId: '653', departmentName: '影像科', roomName: '影像科学习室', officePhone: '7996125', shortPhone: '56125', roomType: '办公区' },
  { workplaceId: '654', departmentName: '影像科', roomName: '影像科数字胃肠Ⅱ室', officePhone: '7996127', shortPhone: '56127', roomType: '医技检查室' },
  { workplaceId: '655', departmentName: '影像科', roomName: '影像科夜班室', officePhone: '7996448', shortPhone: '56448', roomType: '医技检查室' },
  { workplaceId: '656', departmentName: '母婴保健科', roomName: '母婴保健科预防接种室', officePhone: '', shortPhone: '', roomType: '诊室' },
  { workplaceId: '657', departmentName: '母婴保健科', roomName: '母婴保健科产后康复', officePhone: '', shortPhone: '', roomType: '治疗室' },
  { workplaceId: '658', departmentName: '医疗设备科', roomName: '综合楼电梯1号梯', officePhone: '7991461', shortPhone: '56461', roomType: '机房动力' },
  { workplaceId: '659', departmentName: '医疗设备科', roomName: '综合楼电梯2号梯', officePhone: '7991462', shortPhone: '56462', roomType: '机房动力' },
  { workplaceId: '660', departmentName: '医疗设备科', roomName: '妇幼楼电梯孕产专用梯', officePhone: '7991331', shortPhone: '56331', roomType: '机房动力' },
  { workplaceId: '662', departmentName: '产房', roomName: '产房', officePhone: '', shortPhone: '', roomType: '手术室' },
  { workplaceId: '663', departmentName: '产房', roomName: '产房待产室II间', officePhone: '', shortPhone: '', roomType: '病房' },
  { workplaceId: '664', departmentName: '产房', roomName: '产房分娩室II间', officePhone: '', shortPhone: '', roomType: '手术室' },
  { workplaceId: '665', departmentName: '耳鼻喉科', roomName: '耳鼻喉科门诊', officePhone: '', shortPhone: '', roomType: '诊室' },
  { workplaceId: '666', departmentName: '后勤保障部', roomName: '后勤保障部家属区业主委员会', officePhone: '', shortPhone: '', roomType: '办公区' },
  { workplaceId: '667', departmentName: '光明路门诊', roomName: '机关门诊部', officePhone: '', shortPhone: '', roomType: '诊室' },
  { workplaceId: '669', departmentName: '急诊科', roomName: '急诊科EICU医生办', officePhone: '', shortPhone: '', roomType: '抢救室' },
  { workplaceId: '671', departmentName: '康复医学科', roomName: '康复医学科护士站', officePhone: '', shortPhone: '', roomType: '办公区' },
  { workplaceId: '672', departmentName: '口腔科', roomName: '口腔科门诊', officePhone: '', shortPhone: '', roomType: '诊室' },
  { workplaceId: '674', departmentName: '泌尿胸普外科', roomName: '泌尿胸普外科护士站', officePhone: '', shortPhone: '', roomType: '办公区' },
  { workplaceId: '675', departmentName: '皮肤科', roomName: '皮防站皮肤科门诊', officePhone: '', shortPhone: '', roomType: '诊室' },
  { workplaceId: '676', departmentName: '普外二科', roomName: '普外二科护士站', officePhone: '', shortPhone: '', roomType: '办公区' },
  { workplaceId: '677', departmentName: '普外一科', roomName: '普外小儿外科护士站', officePhone: '', shortPhone: '', roomType: '办公区' },
  { workplaceId: '678', departmentName: '神经内二科', roomName: '神经内二科护士站', officePhone: '', shortPhone: '', roomType: '办公区' },
  { workplaceId: '679', departmentName: '神经内一科', roomName: '神经内一科护士站', officePhone: '', shortPhone: '', roomType: '办公区' },
  { workplaceId: '680', departmentName: '收费结算科', roomName: '收费结算科门诊收费', officePhone: '', shortPhone: '', roomType: '办公区' },
  { workplaceId: '681', departmentName: '心血管内一科', roomName: '心血管内一科护士站', officePhone: '7991427', shortPhone: '', roomType: '办公区' },
  { workplaceId: '682', departmentName: '中医科', roomName: '中医科护士站', officePhone: '', shortPhone: '', roomType: '办公区' },
  { workplaceId: '683', departmentName: '消毒供应室', roomName: '消毒供应室灭菌室', officePhone: '', shortPhone: '', roomType: '机房动力' },
  { workplaceId: '685', departmentName: '新生儿科', roomName: '新生儿科东护士站（NICU监护室）', officePhone: '', shortPhone: '', roomType: '病房' },
  { workplaceId: '686', departmentName: '血液透析室', roomName: '血液透析室护士站', officePhone: '', shortPhone: '', roomType: '治疗室' },
  { workplaceId: '687', departmentName: '血液透析室', roomName: '血液透析室护士长办', officePhone: '', shortPhone: '', roomType: '办公区' },
  { workplaceId: '688', departmentName: '药剂科', roomName: '药剂科药库办公室', officePhone: '', shortPhone: '', roomType: '设备库房' },
  { workplaceId: '689', departmentName: '医保科', roomName: '医保科目录审核', officePhone: '', shortPhone: '', roomType: '办公区' },
  { workplaceId: '690', departmentName: '介入放射科', roomName: '介入放射科介入Ⅰ室', officePhone: '', shortPhone: '', roomType: '医技检查室' },
  { workplaceId: '691', departmentName: '介入放射科', roomName: '介入放射科介入Ⅱ室', officePhone: '', shortPhone: '', roomType: '医技检查室' },
  { workplaceId: '692', departmentName: '影像科', roomName: '影像科DR拍片2室', officePhone: '', shortPhone: '', roomType: '医技检查室' },
  { workplaceId: '693', departmentName: '口腔科', roomName: '口腔科门诊拍片室', officePhone: '', shortPhone: '', roomType: '医技检查室' },
  { workplaceId: '694', departmentName: '新生儿科', roomName: '新生儿科新生儿拍片室', officePhone: '7991295', shortPhone: '56295', roomType: '医技检查室' },
  { workplaceId: '695', departmentName: '影像科', roomName: '影像科CT扫描3室', officePhone: '7991702', shortPhone: '56702', roomType: '医技检查室' },
  { workplaceId: '696', departmentName: '麻醉手术科', roomName: '麻醉手术科手术1间', officePhone: '', shortPhone: '', roomType: '手术室' },
  { workplaceId: '697', departmentName: '麻醉手术科', roomName: '麻醉手术科手术2间', officePhone: '', shortPhone: '', roomType: '手术室' },
  { workplaceId: '698', departmentName: '麻醉手术科', roomName: '麻醉手术科手术3间', officePhone: '', shortPhone: '', roomType: '手术室' },
  { workplaceId: '699', departmentName: '麻醉手术科', roomName: '麻醉手术科手术4间', officePhone: '', shortPhone: '', roomType: '手术室' },
  { workplaceId: '700', departmentName: '麻醉手术科', roomName: '麻醉手术科手术5间', officePhone: '', shortPhone: '', roomType: '手术室' },
  { workplaceId: '701', departmentName: '麻醉手术科', roomName: '麻醉手术科手术6间', officePhone: '', shortPhone: '', roomType: '手术室' },
  { workplaceId: '702', departmentName: '麻醉手术科', roomName: '麻醉手术科手术7间', officePhone: '', shortPhone: '', roomType: '手术室' },
  { workplaceId: '703', departmentName: '麻醉手术科', roomName: '麻醉手术科手术8间', officePhone: '', shortPhone: '', roomType: '手术室' },
  { workplaceId: '704', departmentName: '麻醉手术科', roomName: '麻醉手术科手术9间', officePhone: '', shortPhone: '', roomType: '手术室' },
  { workplaceId: '706', departmentName: '产科', roomName: '产科门诊胎心监护室', officePhone: '', shortPhone: '', roomType: '诊室' },
  { workplaceId: '707', departmentName: '消毒供应室', roomName: '消毒供应室洗消室', officePhone: '', shortPhone: '', roomType: '机房动力' },
  { workplaceId: '708', departmentName: '消毒供应室', roomName: '消毒供应室蒸汽室', officePhone: '', shortPhone: '', roomType: '机房动力' },
  { workplaceId: '709', departmentName: '消毒供应室', roomName: '消毒供应室空调机房', officePhone: '', shortPhone: '', roomType: '机房动力' },
  { workplaceId: '710', departmentName: '医疗设备科', roomName: '手术室空气净化机房', officePhone: '', shortPhone: '', roomType: '机房动力' },
  { workplaceId: '711', departmentName: '医疗设备科', roomName: '5楼净化机房设备平台', officePhone: '', shortPhone: '', roomType: '机房动力' },
  { workplaceId: '712', departmentName: '医疗设备科', roomName: '感染楼负压净化机房', officePhone: '', shortPhone: '', roomType: '机房动力' },
  { workplaceId: '713', departmentName: '医疗设备科', roomName: '氧舱供气机房', officePhone: '', shortPhone: '', roomType: '机房动力' },
  { workplaceId: '714', departmentName: '医疗设备科', roomName: '液氧储罐', officePhone: '', shortPhone: '', roomType: '机房动力' },
  { workplaceId: '715', departmentName: '医疗设备科', roomName: '负压吸引机房', officePhone: '', shortPhone: '', roomType: '机房动力' },
  { workplaceId: '716', departmentName: '医疗设备科', roomName: '医学装备应急库', officePhone: '', shortPhone: '', roomType: '设备库房' },
  { workplaceId: '717', departmentName: '创伤外科', roomName: '创伤外科护士站', officePhone: '7991073', shortPhone: '56073', roomType: '办公区' },
  { workplaceId: '718', departmentName: '创伤外科', roomName: '创伤外科医生办', officePhone: '', shortPhone: '', roomType: '办公区' },
  { workplaceId: '719', departmentName: '产房手术室', roomName: '产房手术室手术1间', officePhone: '', shortPhone: '', roomType: '手术室' },
  { workplaceId: '720', departmentName: '产房手术室', roomName: '产房手术室手术2间', officePhone: '', shortPhone: '', roomType: '手术室' },
  { workplaceId: '721', departmentName: '产房手术室', roomName: '产房手术室手术3间', officePhone: '', shortPhone: '', roomType: '手术室' },
  { workplaceId: '722', departmentName: '影像科', roomName: '影像科磁共振1室', officePhone: '7991135', shortPhone: '56135', roomType: '医技检查室' }
];

/**
 * 将原始场所数据转换为标准化的 LocationRoomMaster 对象，自动匹配所属院区、楼宇与楼层
 */
export function buildStandardWorkplaces(rawList = RAW_WORKPLACES_DATA): LocationRoomMaster[] {
  return rawList.map(raw => {
    let campusId = 'CAMPUS-01';
    let campusName = '五莲县人民医院';
    let buildingId = 'BLD-01';
    let buildingName = '1号楼 综合楼';
    let floor = '1F';
    const dept = raw.departmentName || '';

    // 匹配院区与楼宇
    if (dept.includes('皮肤病医院') || dept.includes('皮防站') || dept.includes('皮肤科')) {
      campusId = 'CAMPUS-02';
      campusName = '五莲县皮肤病医院';
      buildingId = 'BLD-DERM-01';
      buildingName = '0皮肤病医院门诊楼';
      floor = (raw.roomName.includes('病房') || raw.roomName.includes('专家') || raw.roomName.includes('院长') || raw.roomName.includes('财务') || raw.roomName.includes('办公室')) ? '2F' : '1F';
    } else if (dept.includes('办公室') || dept.includes('宣教') || dept.includes('财务') || dept.includes('人事') || dept.includes('审计') || dept.includes('绩效') || dept.includes('医务') || dept.includes('护理') || dept.includes('感染管理') || dept.includes('安全') || dept.includes('扶贫') || dept.includes('信息科') || (dept.includes('医疗设备科') && !raw.roomName.includes('机房') && !raw.roomName.includes('储罐') && !raw.roomName.includes('电梯'))) {
      buildingId = 'BLD-06';
      buildingName = '6号楼 办公楼';
      floor = (dept.includes('宣教') || dept.includes('作风')) ? '3F' : (dept.includes('院办') || dept.includes('人事') || dept.includes('审计') || dept.includes('绩效') || dept.includes('领导')) ? '2F' : (dept.includes('科教')) ? '0F' : '1F';
    } else if (dept.includes('急救站')) {
      buildingId = 'BLD-04';
      buildingName = '4号楼 急救站';
      floor = '1F';
    } else if (dept.includes('感染性疾病') || dept.includes('发热') || dept.includes('肝病') || dept.includes('结核')) {
      buildingId = 'BLD-05';
      buildingName = '5号楼 感染性疾病科';
      floor = '2F';
    } else if (dept.includes('康复') || dept.includes('高压氧')) {
      buildingId = 'BLD-02';
      buildingName = '2号楼 原内科楼';
      floor = '3F';
    } else if (dept.includes('放疗') || dept.includes('母婴') || dept.includes('消毒供应') || dept.includes('健康服务') || dept.includes('中医') || dept.includes('理疗') || dept.includes('营养') || dept.includes('综合保健')) {
      buildingId = 'BLD-03';
      buildingName = '3号楼 原妇幼楼';
      floor = dept.includes('消毒供应') ? '-1F' : (dept.includes('放疗') || dept.includes('母婴')) ? '1F' : (dept.includes('健康服务') || dept.includes('司法鉴定')) ? '2F' : (dept.includes('中医') || dept.includes('理疗') || dept.includes('营养')) ? '3F' : '4F';
    } else if (dept.includes('光明路')) {
      buildingId = 'BLD-07';
      buildingName = '0光明路';
      floor = '1F';
    } else {
      // 1号楼综合楼楼层匹配
      buildingId = 'BLD-01';
      buildingName = '1号楼 综合楼';
      if (dept.includes('内分泌') || dept.includes('消化保健') || dept.includes('肾病')) floor = '16F';
      else if (dept.includes('神经内')) floor = '15F';
      else if (dept.includes('心血管')) floor = '14F';
      else if (dept.includes('普外一')) floor = '13F';
      else if (dept.includes('普外二') || dept.includes('泌尿')) floor = '12F';
      else if (dept.includes('呼吸') || dept.includes('危重症')) floor = '11F';
      else if (dept.includes('骨一') || dept.includes('骨二')) floor = '10F';
      else if (dept.includes('妇科') || dept.includes('产科') || dept.includes('产房')) floor = '9F';
      else if (dept.includes('麻醉手术') || raw.roomName.includes('手术') || raw.roomName.includes('净化机房')) floor = '8F';
      else if (dept.includes('重症') || dept.includes('ICU') || dept.includes('神经外科')) floor = '7F';
      else if (dept.includes('创伤') || dept.includes('透析')) floor = '6F';
      else if (dept.includes('儿科') || dept.includes('新生儿') || dept.includes('药剂')) floor = '5F';
      else if (dept.includes('五官') || dept.includes('眼科') || dept.includes('口腔') || dept.includes('耳鼻喉')) floor = '4F';
      else if (dept.includes('检验') || dept.includes('超声') || dept.includes('功能检查')) floor = '3F';
      else if (dept.includes('门诊') || dept.includes('内镜') || dept.includes('输液')) floor = '2F';
      else if (dept.includes('急诊') || dept.includes('收费') || dept.includes('医保')) floor = '1F';
      else if (dept.includes('影像') || dept.includes('CT') || dept.includes('磁共振') || dept.includes('DR') || dept.includes('介入') || dept.includes('胃肠')) floor = '-1F';
      else floor = '1F';
    }

    const fullLocationPath = `${campusName} > ${buildingName} > ${floor} > ${dept} > ${raw.roomName}`;

    return {
      id: raw.workplaceId,
      workplaceId: raw.workplaceId,
      campusId,
      campusName,
      buildingId,
      buildingName,
      floor,
      roomCode: `LOC-${raw.workplaceId}`,
      roomName: raw.roomName,
      officePhone: raw.officePhone,
      shortPhone: raw.shortPhone,
      roomType: raw.roomType || '办公区',
      departmentName: raw.departmentName,
      fullLocationPath
    };
  });
}

export const DEFAULT_WORKPLACES = buildStandardWorkplaces();
