import { MedicalEquipment } from './types';

export const INITIAL_EQUIPMENT: MedicalEquipment[] = [
  {
    id: 'EQ-2023-09855',
    internalNo: '7991105',
    categoryNo: '06',
    category: '医用光学内窥镜与微创器械',
    level1No: '01',
    level1Category: '硬性内窥镜',
    level2No: '01',
    level2Category: '输尿管硬镜/经皮肾镜',
    name: '德国狼牌输尿管硬镜',
    model: 'Richard Wolf 8703.534 (8/9.8Fr 430mm 12°)',
    manufactureDate: '2023/4/15',
    enableDate: '2023/5/1',
    productValidity: '8',
    sn: 'RW-20230415-87035',
    manufacturer: '德国狼牌医疗 (Richard Wolf GmbH)',
    calibration: 'Yes',
    calibrationType: '常规校准',
    calibrationUnit: '山东省医疗器械产品质量检验中心',
    lastCalibrationDate: '2025-11-10',
    nextCalibrationDate: '2026-11-10',
    calibrationCertificateNo: 'SD-MD-202511029',
    department: '麻醉手术科',
    building: '1号楼 综合楼',
    floor: '8',
    nursePhone: '7991086',
    status: '故障待修',
    manager: '黄晓彤 护士长 / 崔伟 工程师',
    purchasePrice: 168000,
    repairCount: 1,
    repairRecords: [
      {
        id: 'REP-20260921-008',
        equipmentId: 'EQ-2023-09855',
        equipmentName: '德国狼牌输尿管硬镜',
        equipmentSn: 'RW-20230415-87035',
        faultDate: '2026-09-21',
        repairType: '紧急故障维修',
        faultDescription: '术中发现输尿管镜视野严重模糊起雾，光轴反光，需大修重置内部光学柱状透镜',
        technician: '德国狼牌技术中心 (李海明)',
        cost: 14200,
        resolution: '返厂大修更换第2组柱镜、密封保护窗并激光调校光轴',
        status: '处理中',
        department: '麻醉手术科'
      }
    ],
    statusLogs: []
  },
  {
    id: '10159',
    categoryNo: '06',
    category: '医用成像器械',
    level1No: '02',
    level1Category: 'X射线计算机体层摄影设备(CT)',
    level2No: '01',
    level2Category: 'X射线计算机体层摄影设备(CT)',
    name: 'X射线计算机体层摄影设备',
    model: 'NeuViz 128',
    manufactureDate: '2020/6/18',
    enableDate: '2020/9/12',
    productValidity: '10',
    sn: 'N1281200421E',
    manufacturer: '沈阳东软医疗系统有限公司',
    calibration: 'Yes',
    calibrationType: '强检类',
    calibrationUnit: '广东省计量科学研究院 (省级)',
    lastCalibrationDate: '2025-08-20',
    nextCalibrationDate: '2026-08-25',
    calibrationCertificateNo: 'JL2025081901',
    department: '影像科',
    building: '1号楼 综合楼',
    floor: '-1',
    nursePhone: '',
    status: '正常运行',
    manager: '崔工程师',
    purchasePrice: 4500000,
    repairCount: 0,
    repairRecords: [],
    statusLogs: []
  },
  {
    id: '10171',
    categoryNo: '06',
    category: '医用成像器械',
    level1No: '01',
    level1Category: '诊断X射线机',
    level2No: '01',
    level2Category: '血管造影X射线机',
    name: 'X射线血管造影机',
    model: 'Arits zee Floor',
    manufactureDate: '2014/3/10',
    enableDate: '2014/5/1',
    productValidity: '10',
    sn: '100005',
    manufacturer: '西门子股份公司',
    calibration: 'Yes',
    calibrationType: '强检类',
    calibrationUnit: '深圳市计量质量检测研究院 (市级)',
    lastCalibrationDate: '2025-07-01',
    nextCalibrationDate: '2026-07-01',
    calibrationCertificateNo: 'JL2025070188',
    department: '介入放射科',
    building: '1号楼 综合楼',
    floor: '-1',
    nursePhone: '7991498',
    status: '正常运行',
    manager: '张工程师',
    purchasePrice: 3800000,
    repairCount: 1,
    repairRecords: [
      {
        id: 'REP-20260510-01',
        equipmentId: '10171',
        equipmentName: 'X射线血管造影机',
        equipmentSn: '100005',
        faultDate: '2026-05-10',
        repairType: '定期预防性保养',
        faultDescription: '球管热容量定标与C臂球管定位校验。',
        technician: '西门子原厂工程师',
        cost: 3500,
        partsReplaced: '球管滤尘风扇',
        resolution: '完成定位校验，热容量指标符合临床要求。',
        status: '已完成',
        completionDate: '2026-05-11'
      }
    ],
    statusLogs: []
  },
  {
    id: '10170',
    categoryNo: '06',
    category: '医用成像器械',
    level1No: '01',
    level1Category: '诊断X射线机',
    level2No: '01',
    level2Category: '血管造影X射线机',
    name: 'X射线血管造影机',
    model: 'AXIOM Artis U',
    manufactureDate: '2012/6/15',
    enableDate: '2012/8/1',
    productValidity: '10',
    sn: '11222',
    manufacturer: '上海西门子医疗器械有限公司',
    calibration: 'Yes',
    calibrationUnit: '市级',
    department: '介入放射科',
    building: '1号楼 综合楼',
    floor: '-1',
    nursePhone: '7991498',
    status: '维护保养中',
    manager: '张工程师',
    purchasePrice: 3200000,
    repairCount: 1,
    repairRecords: [
      {
        id: 'REP-20260802-01',
        equipmentId: '10170',
        equipmentName: 'X射线血管造影机',
        equipmentSn: '11222',
        faultDate: '2026-08-02',
        repairType: '定期预防性保养',
        faultDescription: '年度计量检测与管电压高压校准。',
        technician: '上海西门子维修团队',
        cost: 1200,
        resolution: '正在校准管电压及辐射剂量指标。',
        status: '处理中'
      }
    ],
    statusLogs: []
  },
  {
    id: '10163',
    categoryNo: '06',
    category: '医用成像器械',
    level1No: '01',
    level1Category: '诊断X射线机',
    level2No: '07',
    level2Category: '摄影X射线机',
    name: 'X线摄影系统',
    model: 'RAD SPEED M',
    enableDate: '2013/7/1',
    productValidity: '10',
    sn: '61C795',
    manufacturer: '北京岛津医疗器械有限公司',
    calibration: 'Yes',
    calibrationUnit: '市级',
    department: '影像科',
    building: '1号楼 综合楼',
    floor: '-1',
    nursePhone: '',
    status: '正常运行',
    manager: '王工程师',
    purchasePrice: 1200000,
    repairCount: 0,
    repairRecords: [],
    statusLogs: [],
    overdueFiling: {
      filingNo: 'EXT-2026-0518',
      filingStatus: 'ACTIVE',
      originalLifespanYears: 10,
      overdueYears: 3.1,
      refurbishDate: '2026-05-18',
      refurbishProvider: '北京岛津原厂技术中心 & 院医学工程处精修组',
      refurbishSummary: '完成整机高压电缆绝缘层翻新、限束器光学定位定标、滤线栅轨道清洗润滑、平板探测器坏点增益校正及系统深度除尘与主板电容阵列更新。',
      partsReplaced: ['高压发生器绝缘衬套', '限束器卤素定标光源', '主电源稳压滤波电容组'],
      refurbishCost: 28500,
      stabilityTestDate: '2026-05-25',
      stabilityTestAgency: '山东省医疗器械质量检验中心',
      stabilityTestReportNo: 'QA-STB-20260525-09',
      continuousRunHours: 72,
      driftRate: '<0.28% (符合且优于国标限值≤1.5%)',
      testItems: [
        {
          id: 'TEST-01',
          name: 'GB 9706.1 保护接地阻抗测试',
          standard: 'GB 9706.1-2020 第8.6条',
          result: 'PASS',
          measuredValue: '0.042 Ω (标准限值: < 0.1 Ω)',
          conclusion: '保护接地连通性良好，满足一类设备防护标准'
        },
        {
          id: 'TEST-02',
          name: 'GB 9706.1 对地漏电流与外壳漏电流',
          standard: 'GB 9706.1-2020 第8.7条',
          result: 'PASS',
          measuredValue: '对地漏电流 0.086 mA; 外壳漏电流 0.021 mA (标准限值: < 0.5 mA / 0.1 mA)',
          conclusion: '正常工况及单一故障工况下漏电流均符合安全限值'
        },
        {
          id: 'TEST-03',
          name: '72小时满载连续开机曝光稳定性测试',
          standard: 'YY/T 0011 医用诊断X射线机稳定性评价',
          result: 'PASS',
          measuredValue: '管电压输出重复性 CV = 0.45%; 空气比释动能率漂移 0.28%',
          conclusion: '热衰减性能与输出重复性优异，无异常断电或伪影突发'
        },
        {
          id: 'TEST-04',
          name: '空间分辨率与低对比度分辨力质控测试',
          standard: 'WS 76 医用X射线摄影质量控制标准',
          result: 'PASS',
          measuredValue: '空间分辨力 3.2 lp/mm (标准≥2.5); 低对比度探测到第5组孔',
          conclusion: '图像解析度完全符合临床常规平片诊断标准'
        }
      ],
      approvedDate: '2026-06-01',
      validUntil: '2027-05-31',
      leadEngineer: '崔伟 (主任工程师)',
      leadEngineerPhone: '6802',
      approverRole: '医院医学装备管理与伦理委员会',
      approverName: '孙志强 (医工处长)',
      approvalDocNo: '医装委备[2026]019号',
      monitoringFrequency: 'MONTHLY',
      lastInspectionDate: '2026-08-10',
      nextInspectionDate: '2026-09-10',
      remarks: '本设备已经委员会论证特许准用，仅限用于门诊常规骨骼平片及常规胸腹部非危重筛查，严禁用于急危重症抢救转运。',
      reports: [
        {
          id: 'REP-2026-001',
          fileName: '山东省医疗器械产品质量检验中心_72小时连续稳定性检测报告.pdf',
          fileType: 'pdf',
          fileSize: '3.8 MB',
          uploadDate: '2026-05-25 15:30',
          uploaderName: '崔伟 (主任工程师)',
          reportType: 'stability_72h',
          reportTypeName: '72小时满负荷连续工况稳定性检测报告',
          agencyName: '山东省医疗器械产品质量检验中心',
          reportNo: 'QA-STB-20260525-09',
          verificationStatus: 'verified',
          conclusion: 'QUALIFIED',
          summary: '72h连续开机满负荷曝光无故障，空气比释动能率漂移率0.28%，热衰减与重复性优异',
          extractedData: {
            testDate: '2026-05-25',
            agency: '山东省医疗器械产品质量检验中心',
            reportNo: 'QA-STB-20260525-09',
            continuousHours: 72,
            driftRate: '0.28%',
            conclusion: '综合评定：合格 (具备 CMA / CNAS 实验室资质认证)'
          }
        },
        {
          id: 'REP-2026-002',
          fileName: 'GB9706.1-2020医用电气安全全项测试合格证书.pdf',
          fileType: 'pdf',
          fileSize: '2.4 MB',
          uploadDate: '2026-05-25 16:10',
          uploaderName: '崔伟 (主任工程师)',
          reportType: 'electrical_safety_gb9706',
          reportTypeName: 'GB 9706.1-2020 医用电气安全全项检验证书',
          agencyName: '山东省医疗器械产品质量检验中心',
          reportNo: 'QA-SAF-20260525-14',
          verificationStatus: 'verified',
          conclusion: 'QUALIFIED',
          summary: '保护接地阻抗0.042Ω(<0.1Ω)，对地漏电流0.086mA(<0.5mA)，外壳漏电流0.021mA(<0.1mA)',
          extractedData: {
            testDate: '2026-05-25',
            agency: '山东省医疗器械产品质量检验中心',
            reportNo: 'QA-SAF-20260525-14',
            groundResistance: '0.042 Ω',
            leakageCurrent: '0.086 mA',
            conclusion: '符合 GB 9706.1-2020 及 IEC 60601-1 一类BF型设备电气绝缘要求'
          }
        },
        {
          id: 'REP-2026-003',
          fileName: '岛津原厂技术中心深度整修核心配件换新竣工报告.pdf',
          fileType: 'pdf',
          fileSize: '1.9 MB',
          uploadDate: '2026-05-18 11:20',
          uploaderName: '崔伟 (主任工程师)',
          reportType: 'refurbish_inspection',
          reportTypeName: '深度整修与核心配件更新竣工验收单',
          agencyName: '北京岛津原厂技术服务中心 & 院医学工程处精修组',
          reportNo: 'SHIMADZU-REFURB-20260518',
          verificationStatus: 'verified',
          conclusion: 'QUALIFIED',
          summary: '高压电缆绝缘层翻新、高压发生器绝缘衬套更换、限束器卤素定标光源换新、主电源滤波电容组更新',
          extractedData: {
            testDate: '2026-05-18',
            conclusion: '深度整修竣工验收合格，各项几何与能量指标已恢复至出厂基准'
          }
        }
      ]
    }
  },
  {
    id: '10154',
    categoryNo: '06',
    category: '医用成像器械',
    level1No: '07',
    level1Category: '超声影像诊断设备',
    level2No: '02',
    level2Category: '超声回波多普勒成像设备',
    name: '便携式彩色超声诊断系统',
    model: 'CX50',
    enableDate: '2021/1/6',
    productValidity: '10',
    sn: 'B3KB6Q',
    manufacturer: '飞利浦超声股份有限公司',
    calibration: 'Yes',
    calibrationUnit: '市级',
    department: '超声科',
    ownerDepartment: '超声科',
    building: '1号楼 综合楼',
    floor: '3',
    nursePhone: '',
    currentLoan: {
      id: 'LOAN-20260814-001',
      equipmentId: '10154',
      equipmentName: '便携式彩色超声诊断系统',
      ownerDepartment: '超声科',
      borrowingDepartment: '心血管内科',
      borrowerName: '王建平医生',
      borrowerPhone: '13863301122',
      lenderName: '刘医生',
      borrowTime: '2026-08-14 09:30',
      expectedReturnTime: '2026-08-25 17:00',
      borrowReason: '心内科CCU病房急危重症床旁超声血管与心功能筛查周转借用',
      loanStatus: 'borrowed',
      accessories: ['主机电源线', '相控阵心脏探头 (S5-1)', '凸阵腹部探头 (C5-1)', '便携推车与耦合剂'],
      handoverNotes: '设备外观完好，探头声学透镜完好无损，开机自检通过。'
    },
    loanHistory: [
      {
        id: 'LOAN-20260115-001',
        equipmentId: '10154',
        equipmentName: '便携式彩色超声诊断系统',
        ownerDepartment: '超声科',
        borrowingDepartment: '麻醉手术科',
        borrowerName: '孙志强工程师',
        borrowerPhone: '13963308811',
        lenderName: '刘医生',
        borrowTime: '2026-01-15 08:00',
        expectedReturnTime: '2026-01-18 18:00',
        actualReturnTime: '2026-01-18 16:30',
        borrowReason: '手术室神经阻滞穿刺定位临时借用',
        loanStatus: 'returned',
        accessories: ['主机电源线', '高频线阵探头'],
        handoverNotes: '交接正常',
        returnNotes: '探头及主机完好无损，功能正常归还。',
        returnReceiverName: '刘医生'
      }
    ],
    status: '正常运行',
    manager: '刘医生',
    purchasePrice: 480000,
    repairCount: 2,
    repairRecords: [
      {
        id: 'REP-20260710-04',
        equipmentId: '10154',
        equipmentName: '便携式彩色超声诊断系统',
        equipmentSn: '20PA12030001',
        repairType: '定期预防性保养',
        faultDate: '2026-07-10 14:20',
        faultDescription: '例行探头声束定标与散热滤网清洁，超声声能衰减率在三级合格标准内。',
        technician: '北京智影售后技术服务中心',
        cost: 3200,
        status: '已完成',
        resolution: '探头声学透镜声场均匀度及信噪比检测通过，设备运行良好。',
        partsReplaced: '高压滤网总成',
        completionDate: '2026-07-11 10:00'
      },
      {
        id: 'REP-20260218-08',
        equipmentId: '10154',
        equipmentName: '便携式彩色超声诊断系统',
        equipmentSn: '20PA12030001',
        repairType: '紧急故障维修',
        faultDate: '2026-02-18 09:15',
        faultDescription: '心脏探头接口接触不良，偶发彩超血流信号伪影杂波。',
        technician: '医学工程科 (张工)',
        cost: 850,
        status: '已完成',
        resolution: '校准探头插座金手指针脚并加装屏蔽铜箔，伪影彻底消除。',
        partsReplaced: '探头插头PIN针校准及屏蔽铜箔',
        completionDate: '2026-02-18 16:30'
      }
    ],
    statusLogs: []
  },
  {
    id: '10380',
    categoryNo: '06',
    category: '医用成像器械',
    level1No: '07',
    level1Category: '超声影像诊断设备',
    level2No: '02',
    level2Category: '超声回波多普勒成像设备',
    name: '便携式彩色多普勒超声诊断系统',
    model: 'PA12A',
    enableDate: '2023/1/9',
    productValidity: '',
    sn: '20PA12030002',
    manufacturer: '北京智影技术有限公司',
    calibration: 'Yes',
    calibrationUnit: '市级',
    department: '血液透析室',
    building: '1号楼 综合楼',
    floor: '6',
    nursePhone: '7991162',
    status: '正常运行',
    manager: '赵护士长',
    purchasePrice: 260000,
    repairCount: 1,
    repairRecords: [
      {
        id: 'REP-20260605-03',
        equipmentId: '10380',
        equipmentName: '便携式彩色多普勒超声诊断系统',
        equipmentSn: '20PA12030002',
        repairType: '计量校准',
        faultDate: '2026-06-05 10:00',
        faultDescription: '市级计量测试研究院年度强制检定与灵敏度标定，出具合格证书。',
        technician: '市级计量测试研究院',
        cost: 1800,
        status: '已完成',
        resolution: '探测深度、几何位置示值误差与分辨力均达JJG 899标准，合格准用。',
        partsReplaced: '计量合格贴签',
        completionDate: '2026-06-05 16:00'
      }
    ],
    statusLogs: []
  },
  {
    id: '10416',
    categoryNo: '06',
    category: '医用成像器械',
    level1No: '07',
    level1Category: '超声影像诊断设备',
    level2No: '02',
    level2Category: '超声回波多普勒成像设备',
    name: '便携式彩色多普勒超声诊断系统',
    model: 'PA12A',
    enableDate: '2022/12/28',
    productValidity: '',
    sn: '22PA12110006',
    manufacturer: '北京智影技术有限公司',
    calibration: 'Yes',
    calibrationUnit: '市级',
    department: '医疗设备应急库',
    building: '1号楼 综合楼',
    floor: '9',
    nursePhone: '7991237',
    status: '正常运行',
    manager: '设备科备用',
    purchasePrice: 260000,
    repairCount: 1,
    repairRecords: [
      {
        id: 'REP-20260512-07',
        equipmentId: '10416',
        equipmentName: '便携式彩色多普勒超声诊断系统',
        equipmentSn: '22PA12110006',
        repairType: '定期预防性保养',
        faultDate: '2026-05-12 11:30',
        faultDescription: '备用机电池充放电周期性激活维护，按键面板胶垫清理消毒。',
        technician: '医学工程科 (李工)',
        cost: 0,
        status: '已完成',
        resolution: '锂电池自放电率正常，连续续航达2.5小时，回库待命。',
        partsReplaced: '',
        completionDate: '2026-05-12 14:00'
      }
    ],
    statusLogs: []
  },
  {
    id: '9912',
    categoryNo: '03',
    category: '医用诊察和监护器械',
    level1No: '04',
    level1Category: '监护设备',
    level2No: '01',
    level2Category: '病人监护设备',
    name: '便携式多参数监护仪',
    model: 'MEC-2000',
    enableDate: '',
    productValidity: '10',
    sn: 'EB-15004044',
    manufacturer: '深圳迈瑞生物医疗电子股份有限公司',
    calibration: 'Yes',
    calibrationUnit: '市级',
    department: '产科',
    building: '1号楼 综合楼',
    floor: '4',
    nursePhone: '7991318',
    status: '正常运行',
    manager: '陈护士',
    purchasePrice: 38000,
    repairCount: 0,
    repairRecords: [],
    statusLogs: []
  },
  {
    id: '9911',
    categoryNo: '03',
    category: '医用诊察和监护器械',
    level1No: '04',
    level1Category: '监护设备',
    level2No: '01',
    level2Category: '病人监护设备',
    name: '便携式多参数监护仪',
    model: 'MEC-2000',
    enableDate: '',
    productValidity: '10',
    sn: 'EB-15004067',
    manufacturer: '深圳迈瑞生物医疗电子股份有限公司',
    calibration: 'Yes',
    calibrationUnit: '市级',
    department: '妇科',
    building: '1号楼 综合楼',
    floor: '9',
    nursePhone: '7991089',
    status: '故障待修',
    manager: '林护士长',
    purchasePrice: 38000,
    repairCount: 1,
    repairRecords: [
      {
        id: 'REP-20260806-01',
        equipmentId: '9911',
        equipmentName: '便携式多参数监护仪',
        equipmentSn: 'EB-15004067',
        faultDate: '2026-08-06',
        repairType: '紧急故障维修',
        faultDescription: '屏幕显示雪花噪点，心电波形采集干扰严重。',
        technician: '迈瑞工程师',
        cost: 450,
        partsReplaced: '心电主板导联接口',
        resolution: '已提交工单派单，等待配件更换。',
        status: '处理中'
      }
    ],
    statusLogs: []
  },
  {
    id: '10077',
    categoryNo: '03',
    category: '医用诊察和监护器械',
    level1No: '04',
    level1Category: '监护设备',
    level2No: '01',
    level2Category: '病人监护设备',
    name: '病人监护仪',
    model: 'BeneView T5',
    enableDate: '2012/9/20',
    productValidity: '10',
    sn: 'CM-22122924',
    manufacturer: '深圳迈瑞生物医疗电子股份有限公司',
    calibration: 'Yes',
    calibrationUnit: '市级',
    department: '重症医学科',
    building: '1号楼 综合楼',
    floor: '7',
    nursePhone: '7991278',
    status: '正常运行',
    manager: 'ICU护理组',
    purchasePrice: 85000,
    repairCount: 1,
    repairRecords: [
      {
        id: 'REP-20260722-09',
        equipmentId: '10077',
        equipmentName: '病人监护仪',
        equipmentSn: 'CM-22122924',
        faultDate: '2026-07-22',
        repairType: '定期预防性保养',
        faultDescription: '季度深度清洁与无创血压(NIBP)气路气密性校验，充放气性能合格。',
        technician: '医学工程科 (周工)',
        cost: 0,
        partsReplaced: '',
        resolution: 'NIBP定标及心电各导联自检通过。',
        status: '已完成'
      }
    ],
    statusLogs: []
  },
  {
    id: '10076',
    categoryNo: '03',
    category: '医用诊察和监护器械',
    level1No: '04',
    level1Category: '监护设备',
    level2No: '01',
    level2Category: '病人监护设备',
    name: '病人监护仪',
    model: 'BeneView T5',
    enableDate: '2012/9/20',
    productValidity: '10',
    sn: 'CM-22122925',
    manufacturer: '深圳迈瑞生物医疗电子股份有限公司',
    calibration: 'Yes',
    calibrationUnit: '市级',
    department: '重症医学科',
    building: '1号楼 综合楼',
    floor: '7',
    nursePhone: '7991278',
    status: '正常运行',
    manager: 'ICU护理组',
    purchasePrice: 85000,
    repairCount: 1,
    repairRecords: [
      {
        id: 'REP-20260411-06',
        equipmentId: '10076',
        equipmentName: '病人监护仪',
        equipmentSn: 'CM-22122925',
        faultDate: '2026-04-11',
        repairType: '紧急故障维修',
        faultDescription: '血氧饱和度探头引线磨损断路，读数时有时无。',
        technician: '迈瑞售后服务部',
        cost: 1200,
        partsReplaced: '成人指夹式血氧探头',
        resolution: '更换原厂血氧探头，实测脉搏波形连续平稳。',
        status: '已完成'
      }
    ],
    statusLogs: []
  },
  {
    id: '10075',
    categoryNo: '03',
    category: '医用诊察和监护器械',
    level1No: '04',
    level1Category: '监护设备',
    level2No: '01',
    level2Category: '病人监护设备',
    name: '病人监护仪',
    model: 'BeneView T5',
    enableDate: '2012/9/20',
    productValidity: '10',
    sn: 'CM-22122938',
    manufacturer: '深圳迈瑞生物医疗电子股份有限公司',
    calibration: 'Yes',
    calibrationUnit: '市级',
    department: '重症医学科',
    building: '1号楼 综合楼',
    floor: '7',
    nursePhone: '7991278',
    status: '故障待修',
    manager: 'ICU护理组',
    purchasePrice: 85000,
    repairCount: 1,
    repairRecords: [
      {
        id: 'REP-20260807-02',
        equipmentId: '10075',
        equipmentName: '病人监护仪',
        equipmentSn: 'CM-22122938',
        faultDate: '2026-08-07',
        repairType: '紧急故障维修',
        faultDescription: '无创血压NIBP充气泵超时报警，无法完成测压。',
        technician: '设备科崔工',
        cost: 320,
        partsReplaced: 'NIBP内部气泵马达',
        resolution: '已报修派单排查，拟更换气泵软管和马达。',
        status: '处理中'
      }
    ],
    statusLogs: []
  },
  {
    id: '10074',
    categoryNo: '03',
    category: '医用诊察和监护器械',
    level1No: '04',
    level1Category: '监护设备',
    level2No: '01',
    level2Category: '病人监护设备',
    name: '病人监护仪',
    model: 'BeneView T5',
    enableDate: '2012/9/20',
    productValidity: '10',
    sn: 'CM-22122939',
    manufacturer: '深圳迈瑞生物医疗电子股份有限公司',
    calibration: 'Yes',
    calibrationUnit: '市级',
    department: '重症医学科',
    building: '1号楼 综合楼',
    floor: '7',
    nursePhone: '7991278',
    status: '正常运行',
    manager: 'ICU护理组',
    purchasePrice: 85000,
    repairCount: 0,
    repairRecords: [],
    statusLogs: []
  },
  {
    id: '10073',
    categoryNo: '03',
    category: '医用诊察和监护器械',
    level1No: '04',
    level1Category: '监护设备',
    level2No: '01',
    level2Category: '病人监护设备',
    name: '病人监护仪',
    model: 'BeneView T5',
    enableDate: '2012/9/20',
    productValidity: '10',
    sn: 'CM-22122967',
    manufacturer: '深圳迈瑞生物医疗电子股份有限公司',
    calibration: 'Yes',
    calibrationUnit: '市级',
    department: '重症医学科',
    building: '1号楼 综合楼',
    floor: '7',
    nursePhone: '7991278',
    status: '正常运行',
    manager: 'ICU护理组',
    purchasePrice: 85000,
    repairCount: 0,
    repairRecords: [],
    statusLogs: []
  },
  {
    id: '10072',
    categoryNo: '03',
    category: '医用诊察和监护器械',
    level1No: '04',
    level1Category: '监护设备',
    level2No: '01',
    level2Category: '病人监护设备',
    name: '病人监护仪',
    model: 'BeneView T5',
    enableDate: '2012/9/20',
    productValidity: '10',
    sn: 'CM-22122970',
    manufacturer: '深圳迈瑞生物医疗电子股份有限公司',
    calibration: 'Yes',
    calibrationUnit: '市级',
    department: '重症医学科',
    building: '1号楼 综合楼',
    floor: '7',
    nursePhone: '7991278',
    status: '正常运行',
    manager: 'ICU护理组',
    purchasePrice: 85000,
    repairCount: 0,
    repairRecords: [],
    statusLogs: []
  },
  {
    id: '10071',
    categoryNo: '03',
    category: '医用诊察和监护器械',
    level1No: '04',
    level1Category: '监护设备',
    level2No: '01',
    level2Category: '病人监护设备',
    name: '病人监护仪',
    model: 'BeneView T5',
    enableDate: '2012/9/20',
    productValidity: '10',
    sn: 'CM-23123378',
    manufacturer: '深圳迈瑞生物医疗电子股份有限公司',
    calibration: 'Yes',
    calibrationUnit: '市级',
    department: '重症医学科',
    building: '1号楼 综合楼',
    floor: '7',
    nursePhone: '7991278',
    status: '正常运行',
    manager: 'ICU护理组',
    purchasePrice: 85000,
    repairCount: 0,
    repairRecords: [],
    statusLogs: []
  },
  {
    id: '10070',
    categoryNo: '03',
    category: '医用诊察和监护器械',
    level1No: '04',
    level1Category: '监护设备',
    level2No: '01',
    level2Category: '病人监护设备',
    name: '病人监护仪',
    model: 'BeneView T5',
    enableDate: '2012/9/20',
    productValidity: '10',
    sn: 'CM-23123390',
    manufacturer: '深圳迈瑞生物医疗电子股份有限公司',
    calibration: 'Yes',
    calibrationUnit: '市级',
    department: '重症医学科',
    building: '1号楼 综合楼',
    floor: '7',
    nursePhone: '7991278',
    status: '正常运行',
    manager: 'ICU护理组',
    purchasePrice: 85000,
    repairCount: 0,
    repairRecords: [],
    statusLogs: []
  },
  {
    id: '10069',
    categoryNo: '03',
    category: '医用诊察和监护器械',
    level1No: '04',
    level1Category: '监护设备',
    level2No: '01',
    level2Category: '病人监护设备',
    name: '病人监护仪',
    model: 'BeneView T5',
    enableDate: '2012/9/20',
    productValidity: '10',
    sn: 'CM-23123529',
    manufacturer: '深圳迈瑞生物医疗电子股份有限公司',
    calibration: 'Yes',
    calibrationUnit: '市级',
    department: '重症医学科',
    building: '1号楼 综合楼',
    floor: '7',
    nursePhone: '7991278',
    status: '维护保养中',
    manager: 'ICU护理组',
    purchasePrice: 85000,
    repairCount: 1,
    repairRecords: [
      {
        id: 'REP-20260804-03',
        equipmentId: '10069',
        equipmentName: '病人监护仪',
        equipmentSn: 'CM-23123529',
        faultDate: '2026-08-04',
        repairType: '定期预防性保养',
        faultDescription: '例行安全及电源接地电阻质控检测。',
        technician: '医学装备科崔工',
        cost: 0,
        resolution: '质控检测符合标准，待复核归还。',
        status: '处理中'
      }
    ],
    statusLogs: []
  },
  {
    id: '10068',
    categoryNo: '03',
    category: '医用诊察和监护器械',
    level1No: '04',
    level1Category: '监护设备',
    level2No: '01',
    level2Category: '病人监护设备',
    name: '病人监护仪',
    model: 'BeneView T5',
    enableDate: '2012/9/20',
    productValidity: '10',
    sn: 'CM-23123535',
    manufacturer: '深圳迈瑞生物医疗电子股份有限公司',
    calibration: 'Yes',
    calibrationUnit: '市级',
    department: '重症医学科',
    building: '1号楼 综合楼',
    floor: '7',
    nursePhone: '7991278',
    status: '正常运行',
    manager: 'ICU护理组',
    purchasePrice: 85000,
    repairCount: 0,
    repairRecords: [],
    statusLogs: []
  },
  {
    id: '10078',
    categoryNo: '03',
    category: '医用诊察和监护器械',
    level1No: '04',
    level1Category: '监护设备',
    level2No: '01',
    level2Category: '病人监护设备',
    name: '病人监护仪',
    model: 'BeneView T5',
    enableDate: '',
    productValidity: '10',
    sn: 'CM-25125208',
    manufacturer: '深圳迈瑞生物医疗电子股份有限公司',
    calibration: 'Yes',
    calibrationUnit: '市级',
    department: '介入放射科',
    building: '1号楼 综合楼',
    floor: '-1',
    nursePhone: '7991498',
    status: '正常运行',
    manager: '介入科护士站',
    purchasePrice: 85000,
    repairCount: 1,
    repairRecords: [
      {
        id: 'REP-20260630-11',
        equipmentId: '10078',
        equipmentName: '病人监护仪',
        equipmentSn: 'CM-25125208',
        faultDate: '2026-06-30',
        repairType: '紧急故障维修',
        faultDescription: '介入手术过程中心电波形偶发抖动，排查接地线螺母氧化。',
        technician: '医学工程科 (崔工)',
        cost: 360,
        partsReplaced: '等电位接地端子柱',
        resolution: '打磨氧化触点，紧固等电位接地线，术中抗高频电刀干扰测试合格。',
        status: '已完成'
      }
    ],
    statusLogs: []
  },
  {
    id: '10067',
    categoryNo: '03',
    category: '医用诊察和监护器械',
    level1No: '04',
    level1Category: '监护设备',
    level2No: '01',
    level2Category: '病人监护设备',
    name: '病人监护仪',
    model: 'BeneView T8',
    enableDate: '',
    productValidity: '10',
    sn: 'CF-0C107923',
    manufacturer: '深圳迈瑞生物医疗电子股份有限公司',
    calibration: 'Yes',
    calibrationUnit: '市级',
    department: '麻醉手术科',
    building: '1号楼 综合楼',
    floor: '8',
    nursePhone: '7991103',
    status: '正常运行',
    manager: '手术室麻醉组',
    purchasePrice: 120000,
    repairCount: 1,
    repairRecords: [
      {
        id: 'REP-20260315-12',
        equipmentId: '10067',
        equipmentName: '病人监护仪',
        equipmentSn: 'CF-0C107923',
        faultDate: '2026-03-15',
        repairType: '定期预防性保养',
        faultDescription: '手术室麻醉深浅度模块(BIS)校准与多气体分析模块水阱更换。',
        technician: '迈瑞医疗高级技术专家',
        cost: 6500,
        partsReplaced: '麻醉多气体水阱滤杯及定标气阀',
        resolution: '五种麻醉挥发气体红外浓度标定通过，出具质检报告。',
        status: '已完成'
      }
    ],
    statusLogs: []
  },
  {
    id: '10066',
    categoryNo: '03',
    category: '医用诊察和监护器械',
    level1No: '04',
    level1Category: '监护设备',
    level2No: '01',
    level2Category: '病人监护设备',
    name: '病人监护仪',
    model: 'BeneView T8',
    enableDate: '',
    productValidity: '10',
    sn: 'CF-0C107924',
    manufacturer: '深圳迈瑞生物医疗电子股份有限公司',
    calibration: 'Yes',
    calibrationUnit: '市级',
    department: '麻醉手术科',
    building: '1号楼 综合楼',
    floor: '8',
    nursePhone: '7991103',
    status: '正常运行',
    manager: '手术室麻醉组',
    purchasePrice: 120000,
    repairCount: 0,
    repairRecords: [],
    statusLogs: []
  },
  {
    id: '10065',
    categoryNo: '03',
    category: '医用诊察和监护器械',
    level1No: '04',
    level1Category: '监护设备',
    level2No: '01',
    level2Category: '病人监护设备',
    name: '病人监护仪',
    model: 'BeneView T8',
    enableDate: '',
    productValidity: '10',
    sn: 'CF-41121435',
    manufacturer: '深圳迈瑞生物医疗电子股份有限公司',
    calibration: 'Yes',
    calibrationUnit: '市级',
    department: '麻醉手术科',
    building: '1号楼 综合楼',
    floor: '8',
    nursePhone: '7991103',
    status: '正常运行',
    manager: '手术室麻醉组',
    purchasePrice: 120000,
    repairCount: 0,
    repairRecords: [],
    statusLogs: []
  },
  {
    id: '10064',
    categoryNo: '03',
    category: '医用诊察和监护器械',
    level1No: '04',
    level1Category: '监护设备',
    level2No: '01',
    level2Category: '病人监护设备',
    name: '病人监护仪',
    model: 'BeneView T8',
    enableDate: '',
    productValidity: '10',
    sn: 'CF-41121436',
    manufacturer: '深圳迈瑞生物医疗电子股份有限公司',
    calibration: 'Yes',
    calibrationUnit: '市级',
    department: '麻醉手术科',
    building: '1号楼 综合楼',
    floor: '8',
    nursePhone: '7991103',
    status: '停用/报废',
    manager: '手术室麻醉组',
    purchasePrice: 120000,
    repairCount: 1,
    repairRecords: [
      {
        id: 'REP-20251120-09',
        equipmentId: '10064',
        equipmentName: '病人监护仪',
        equipmentSn: 'CF-41121436',
        faultDate: '2025-11-20',
        repairType: '紧急故障维修',
        faultDescription: '主板供电烧毁，屏幕无法开启。',
        technician: '迈瑞工程师',
        cost: 42000,
        resolution: '已超安全使用年限，主板停产无原厂配件，技术鉴定后封存停用。',
        status: '已完成',
        completionDate: '2025-11-22'
      }
    ],
    statusLogs: []
  },
  {
    id: '10185',
    categoryNo: '03',
    category: '医用诊察和监护器械',
    level1No: '01',
    level1Category: '心电诊断设备',
    level2No: '01',
    level2Category: '十二导联心电图机',
    name: '十二导联同步心电图机',
    model: 'BeneHeart R12',
    enableDate: '2023/5/10',
    manufactureDate: '2023/4/15',
    productValidity: '8',
    sn: 'ECG-20230415-08',
    manufacturer: '深圳迈瑞生物医疗电子股份有限公司',
    calibration: 'Yes',
    calibrationType: '强检(国家免费)',
    catalogueCode: 'QJ-01',
    feePolicy: 'free_national',
    calibrationUnit: '市计量质量检测研究院 (法定强检)',
    lastCalibrationDate: '2025-05-15',
    nextCalibrationDate: '2026-05-15',
    calibrationCertificateNo: 'QJ-ECG-2025-0588',
    department: '重症医学科',
    building: '1号楼 综合楼',
    floor: '7',
    nursePhone: '7991278',
    status: '正常运行',
    manager: '心电主管技师',
    purchasePrice: 42000,
    repairCount: 0,
    repairRecords: [],
    statusLogs: []
  },
  {
    id: '10186',
    categoryNo: '03',
    category: '医用诊察和监护器械',
    level1No: '02',
    level1Category: '脑电诊断设备',
    level2No: '01',
    level2Category: '数字脑电地形图仪',
    name: '数字视频脑电图仪',
    model: 'EEG-1200C',
    enableDate: '2022/8/18',
    manufactureDate: '2022/6/20',
    productValidity: '10',
    sn: 'EEG-202206-89',
    manufacturer: '日本光电工业株式会社',
    calibration: 'Yes',
    calibrationType: '强检(国家免费)',
    catalogueCode: 'QJ-02',
    feePolicy: 'free_national',
    calibrationUnit: '广东省计量科学研究院 (法定强检)',
    lastCalibrationDate: '2025-08-10',
    nextCalibrationDate: '2026-08-10',
    calibrationCertificateNo: 'QJ-EEG-2025-0192',
    department: '神经内科',
    building: '1号楼 综合楼',
    floor: '5',
    nursePhone: '7991120',
    status: '正常运行',
    manager: '神经内科脑电室',
    purchasePrice: 180000,
    repairCount: 0,
    repairRecords: [],
    statusLogs: []
  },
  {
    id: '10195',
    categoryNo: '03',
    category: '医用诊察和监护器械',
    level1No: '03',
    level1Category: '生理参数测量',
    level2No: '01',
    level2Category: '台式水银/电子血压计',
    name: '医用精密台式血压计',
    model: 'HBP-1300',
    enableDate: '2024/1/10',
    manufactureDate: '2023/12/01',
    productValidity: '5',
    sn: 'BP-20231201-99',
    manufacturer: '欧姆龙(大连)有限公司',
    calibration: 'Yes',
    calibrationType: '强检(国家免费)',
    catalogueCode: 'QJ-07',
    feePolicy: 'free_national',
    calibrationUnit: '县/区级法定计量检定所',
    lastCalibrationDate: '2025-11-20',
    nextCalibrationDate: '2026-05-20',
    calibrationCertificateNo: 'QJ-BP-2025-9921',
    department: '急诊科',
    building: '1号楼 综合楼',
    floor: '1',
    nursePhone: '7991120',
    status: '正常运行',
    manager: '急诊分诊台',
    purchasePrice: 2800,
    repairCount: 0,
    repairRecords: [],
    statusLogs: []
  },
  {
    id: '10188',
    categoryNo: '08',
    category: '呼吸、麻醉和急救器械',
    level1No: '03',
    level1Category: '输液与推注设备',
    level2No: '01',
    level2Category: '医用双通道注射泵',
    name: '双通道微量注射泵',
    model: 'BeneFusion SP5',
    enableDate: '2023/3/15',
    manufactureDate: '2023/2/10',
    productValidity: '8',
    sn: 'SP5-202302-009',
    manufacturer: '深圳迈瑞生物医疗电子股份有限公司',
    calibration: 'Yes',
    calibrationType: '定期校准(自费)',
    catalogueCode: 'JZ-01',
    feePolicy: 'paid_hospital',
    calibrationUnit: '华南国家计量测试中心 (校准部)',
    lastCalibrationDate: '2025-04-10',
    nextCalibrationDate: '2026-04-10',
    calibrationCertificateNo: 'JZ-CAL-2025-4421',
    department: '重症医学科',
    building: '1号楼 综合楼',
    floor: '7',
    nursePhone: '7991278',
    status: '正常运行',
    manager: 'ICU护理组',
    purchasePrice: 16000,
    repairCount: 1,
    repairRecords: [
      {
        id: 'REP-20260718-13',
        equipmentId: '10188',
        equipmentName: '双通道微量注射泵',
        equipmentSn: 'SP5-202302-009',
        faultDate: '2026-07-18',
        repairType: '定期预防性保养',
        faultDescription: '注射泵推杆滑轨精密润滑与堵塞报警压力阈值精度标定。',
        technician: '医学工程科 (周工)',
        cost: 150,
        partsReplaced: '推杆防尘硅胶圈',
        resolution: '推注精度误差小于±2%，各档位堵塞声光报警灵敏。',
        status: '已完成'
      }
    ],
    statusLogs: []
  },
  {
    id: '10189',
    categoryNo: '01',
    category: '有源手术器械',
    level1No: '01',
    level1Category: '高频手术设备',
    level2No: '01',
    level2Category: '高频电刀发生器',
    name: '高频电外科能量平台 (电刀)',
    model: 'Force FX-8C',
    enableDate: '2021/6/18',
    manufactureDate: '2021/4/20',
    productValidity: '10',
    sn: 'VALLEYLAB-8812',
    manufacturer: '美敦力柯惠医疗器材有限公司',
    calibration: 'Yes',
    calibrationType: '定期校准(自费)',
    catalogueCode: 'JZ-03',
    feePolicy: 'paid_hospital',
    calibrationUnit: '省医疗器械质量监督检验所 (校准室)',
    lastCalibrationDate: '2025-06-25',
    nextCalibrationDate: '2026-06-25',
    calibrationCertificateNo: 'JZ-CAL-2025-1033',
    department: '麻醉手术科',
    building: '1号楼 综合楼',
    floor: '8',
    nursePhone: '7991103',
    status: '正常运行',
    manager: '手术室器械组',
    purchasePrice: 280000,
    repairCount: 1,
    repairRecords: [
      {
        id: 'REP-20260520-14',
        equipmentId: '10189',
        equipmentName: '高频电外科能量平台 (电刀)',
        equipmentSn: 'VALLEYLAB-8812',
        faultDate: '2026-05-20',
        repairType: '紧急故障维修',
        faultDescription: '单极电凝功率输出偏低，负极回路监测板(REM)误报警。',
        technician: '美敦力原厂签约维保中心',
        cost: 8800,
        partsReplaced: 'REM回路阻抗检测主控板',
        resolution: '更换REM模组，高频功率计测试单极切/凝输出线性度达标。',
        status: '已完成'
      }
    ],
    statusLogs: []
  },
  {
    id: '10176',
    categoryNo: '08',
    category: '呼吸、麻醉和急救器械',
    level1No: '02',
    level1Category: '心脏除颤设备',
    level2No: '01',
    level2Category: '双相波除颤监护仪',
    name: '双相波除颤起搏监护仪',
    model: 'BeneHeart D3',
    enableDate: '2022/10/12',
    manufactureDate: '2022/9/01',
    productValidity: '8',
    sn: 'D3-202209-441',
    manufacturer: '深圳迈瑞生物医疗电子股份有限公司',
    calibration: 'Yes',
    calibrationType: '定期校准(自费)',
    catalogueCode: 'JZ-04',
    feePolicy: 'paid_hospital',
    calibrationUnit: '深圳市计量质量检测研究院 (校准中心)',
    lastCalibrationDate: '2025-10-15',
    nextCalibrationDate: '2026-10-15',
    calibrationCertificateNo: 'JZ-CAL-2025-8832',
    department: '急诊科',
    building: '1号楼 综合楼',
    floor: '1',
    nursePhone: '7991120',
    status: '正常运行',
    manager: '王护士长 / 急诊抢救室',
    purchasePrice: 75000,
    repairCount: 1,
    repairRecords: [
      {
        id: 'REP-20260801-15',
        equipmentId: '10176',
        equipmentName: '双相波除颤起搏监护仪',
        equipmentSn: 'D3-202209-441',
        faultDate: '2026-08-01',
        repairType: '计量校准',
        faultDescription: '除颤能量释放精度(20J-360J)周期校检，充电时间测试≤3秒。',
        technician: '市计量院医学计量部',
        cost: 1600,
        partsReplaced: '',
        resolution: '高压储能放电精度误差在1.5%以内，签发检定合格证。',
        status: '已完成'
      }
    ],
    statusLogs: []
  },
  {
    id: '10196',
    categoryNo: '08',
    category: '呼吸、麻醉和急救器械',
    level1No: '01',
    level1Category: '医用呼吸机',
    level2No: '02',
    level2Category: '急救转运呼吸机',
    name: '电动涡轮急救转运呼吸机',
    model: 'SV300',
    enableDate: '2023/4/20',
    manufactureDate: '2023/3/10',
    productValidity: '8',
    sn: 'SV300-202303-118',
    manufacturer: '深圳迈瑞生物医疗电子股份有限公司',
    calibration: 'Yes',
    calibrationType: '定期校准(自费)',
    catalogueCode: 'JZ-05',
    feePolicy: 'paid_hospital',
    calibrationUnit: '广东省计量科学研究院 (气体流量校准室)',
    lastCalibrationDate: '2025-09-10',
    nextCalibrationDate: '2026-09-10',
    calibrationCertificateNo: 'JZ-CAL-2025-9923',
    department: '急诊科',
    ownerDepartment: '急诊科',
    building: '1号楼 综合楼',
    floor: '1',
    nursePhone: '7991120',
    currentLoan: {
      id: 'LOAN-20260812-003',
      equipmentId: '10196',
      equipmentName: '电动涡轮急救转运呼吸机',
      ownerDepartment: '急诊科',
      borrowingDepartment: '重症医学科',
      borrowerName: '郑晓明医生',
      borrowerPhone: '13793400918',
      lenderName: '王护士长',
      borrowTime: '2026-08-12 11:00',
      expectedReturnTime: '2026-08-18 18:00',
      borrowReason: '重症ICU收治多名急性呼吸窘迫综合征(ARDS)患者紧急借调支持',
      loanStatus: 'overdue',
      accessories: ['呼吸机管路', '高压氧气连接软管', '电源线及适配器', '转运专用支架'],
      handoverNotes: '急诊科出借交接，涡轮气密性及潮气量检测正常。'
    },
    loanHistory: [
      {
        id: 'LOAN-20260310-001',
        equipmentId: '10196',
        equipmentName: '电动涡轮急救转运呼吸机',
        ownerDepartment: '急诊科',
        borrowingDepartment: '呼吸内科',
        borrowerName: '刘海波医生',
        borrowerPhone: '13563388712',
        lenderName: '王护士长',
        borrowTime: '2026-03-10 08:30',
        expectedReturnTime: '2026-03-15 17:00',
        actualReturnTime: '2026-03-15 15:20',
        borrowReason: '呼吸内科重症病房转运检查临时借用',
        loanStatus: 'returned',
        accessories: ['电源线', '转运支架'],
        handoverNotes: '设备正常交接',
        returnNotes: '外观完整，功能正常，附件齐全验收归还。',
        returnReceiverName: '王护士长'
      }
    ],
    status: '正常运行',
    manager: '王护士长 / 急诊抢救室',
    purchasePrice: 180000,
    repairCount: 0,
    repairRecords: [],
    statusLogs: []
  },
  {
    id: '10197',
    categoryNo: '03',
    category: '医用诊察和监护器械',
    level1No: '01',
    level1Category: '心电诊断设备',
    level2No: '01',
    level2Category: '数字式十二导联心电图机',
    name: '十二导联自动分析心电图机',
    model: 'BeneHeart R12',
    enableDate: '2022/8/15',
    manufactureDate: '2022/7/01',
    productValidity: '8',
    sn: 'R12-202207-092',
    manufacturer: '深圳迈瑞生物医疗电子股份有限公司',
    calibration: 'Yes',
    calibrationType: '强检(国家免费)',
    catalogueCode: 'QJ-01',
    feePolicy: 'free_national',
    calibrationUnit: '日照市计量测试所 (法定强检)',
    lastCalibrationDate: '2025-08-15',
    nextCalibrationDate: '2026-08-15',
    calibrationCertificateNo: 'QJ-ECG-2025-1102',
    department: '急诊科',
    building: '1号楼 综合楼',
    floor: '1',
    nursePhone: '7991120',
    status: '正常运行',
    manager: '王护士长 / 急诊抢救室',
    purchasePrice: 42000,
    repairCount: 0,
    repairRecords: [],
    statusLogs: []
  },
  {
    id: '10198',
    categoryNo: '08',
    category: '呼吸、麻醉和急救器械',
    level1No: '04',
    level1Category: '心肺复苏及辅助设备',
    level2No: '01',
    level2Category: '便携式全自动胸外按压机',
    name: '便携式电动心肺复苏机',
    model: 'E6 AutoCPR',
    enableDate: '2023/11/10',
    manufactureDate: '2023/10/05',
    productValidity: '8',
    sn: 'CPR-202310-004',
    manufacturer: '苏州心锐医疗器械有限公司',
    calibration: 'Yes',
    calibrationType: '定期校准(自费)',
    catalogueCode: 'JZ-08',
    feePolicy: 'paid_hospital',
    calibrationUnit: '深圳市计量质量检测研究院 (校准中心)',
    lastCalibrationDate: '2025-11-12',
    nextCalibrationDate: '2026-11-12',
    calibrationCertificateNo: 'JZ-CAL-2025-8812',
    department: '急诊科',
    building: '1号楼 综合楼',
    floor: '1',
    nursePhone: '7991120',
    status: '故障待修',
    lastFaultReason: '锂电池无法充电，外接AC电源插座松动报错',
    manager: '王护士长 / 急诊抢救室',
    purchasePrice: 125000,
    repairCount: 1,
    repairRecords: [
      {
        id: 'REP-20260814-05',
        equipmentId: '10198',
        equipmentName: '便携式电动心肺复苏机',
        equipmentSn: 'CPR-202310-004',
        faultDate: '2026-08-14',
        repairType: '紧急故障维修',
        faultDescription: '锂电池无法充电，外接AC电源插座松动报错',
        technician: '设备科崔工',
        cost: 0,
        resolution: '已派单至医学工程科，准备更换电源板和专用电池。',
        status: '处理中'
      }
    ],
    statusLogs: []
  },
  {
    id: '10199',
    categoryNo: '08',
    category: '呼吸、麻醉和急救器械',
    level1No: '05',
    level1Category: '洗胃设备',
    level2No: '01',
    level2Category: '自动洗胃机',
    name: '全自动自动控制洗胃机',
    model: 'GX-III',
    enableDate: '2021/5/12',
    manufactureDate: '2021/4/10',
    productValidity: '8',
    sn: 'GX3-202104-033',
    manufacturer: '上海康人医学仪器设备有限公司',
    calibration: 'No',
    calibrationType: '免计量',
    department: '急诊科',
    building: '1号楼 综合楼',
    floor: '1',
    nursePhone: '7991120',
    status: '维护保养中',
    manager: '王护士长 / 急诊抢救室',
    purchasePrice: 28000,
    repairCount: 1,
    repairRecords: [
      {
        id: 'REP-20260812-02',
        equipmentId: '10199',
        equipmentName: '全自动自动控制洗胃机',
        equipmentSn: 'GX3-202104-033',
        faultDate: '2026-08-12',
        repairType: '定期预防性保养',
        faultDescription: '例行管路压力传感器校准与电磁阀密封保养。',
        technician: '医学装备科孙志强',
        cost: 150,
        resolution: '电磁阀密封圈更换完毕，正在执行冲洗压力验证。',
        status: '处理中'
      }
    ],
    statusLogs: []
  },
  {
    id: '10175',
    categoryNo: '08',
    category: '呼吸、麻醉和急救器械',
    level1No: '01',
    level1Category: '医用呼吸机',
    level2No: '01',
    level2Category: '重症治疗呼吸机',
    name: '重症有创呼吸机',
    model: 'PB 840',
    enableDate: '2020/5/20',
    manufactureDate: '2020/3/15',
    productValidity: '10',
    sn: 'PB840-2020-09',
    manufacturer: '美敦力呼吸与监测事业部',
    calibration: 'Yes',
    calibrationType: '定期校准(自费)',
    catalogueCode: 'JZ-05',
    feePolicy: 'paid_hospital',
    calibrationUnit: '广东省计量科学研究院 (气体流量校准室)',
    lastCalibrationDate: '2025-05-18',
    nextCalibrationDate: '2026-05-18',
    calibrationCertificateNo: 'JZ-CAL-2025-5512',
    department: '重症医学科',
    building: '1号楼 综合楼',
    floor: '7',
    nursePhone: '7991278',
    status: '正常运行',
    manager: 'ICU呼吸治疗师',
    purchasePrice: 320000,
    repairCount: 0,
    repairRecords: [],
    statusLogs: []
  },
  {
    id: '10190',
    categoryNo: '22',
    category: '临床检验器械',
    level1No: '05',
    level1Category: '离心机设备',
    level2No: '01',
    level2Category: '台式高速冷冻离心机',
    name: '台式高速冷冻离心机',
    model: 'Micro 21R',
    enableDate: '2022/11/05',
    manufactureDate: '2022/9/10',
    productValidity: '10',
    sn: 'THERMO-202209-12',
    manufacturer: '赛默飞世尔科技(中国)有限公司',
    calibration: 'Yes',
    calibrationType: '定期校准(自费)',
    catalogueCode: 'JZ-07',
    feePolicy: 'paid_hospital',
    calibrationUnit: '市计量质量检测所',
    lastCalibrationDate: '2025-11-01',
    nextCalibrationDate: '2026-11-01',
    calibrationCertificateNo: 'JZ-CAL-2025-7731',
    department: '检验科',
    building: '1号楼 综合楼',
    floor: '2',
    nursePhone: '7991115',
    status: '正常运行',
    manager: '生化检验组',
    purchasePrice: 68000,
    repairCount: 0,
    repairRecords: [],
    statusLogs: []
  },
  {
    id: '10192',
    categoryNo: '15',
    category: '妇产科、辅助生殖和避孕器械',
    level1No: '01',
    level1Category: '产科检查病床',
    level2No: '01',
    level2Category: '多功能液压产床',
    name: '多功能一体化液压分娩产床',
    model: 'Optima LDR',
    enableDate: '2023/1/15',
    manufactureDate: '2022/12/01',
    productValidity: '12',
    sn: 'LDR-202212-05',
    manufacturer: '芬兰美迪兰医疗器械有限公司',
    calibration: 'No',
    calibrationType: '免计量',
    department: '产科',
    building: '1号楼 综合楼',
    floor: '4',
    nursePhone: '7991318',
    status: '正常运行',
    manager: '产房护士长',
    purchasePrice: 150000,
    repairCount: 0,
    repairRecords: [],
    statusLogs: []
  }
];

export const DEPARTMENTS = [
  '全院科室',
  '影像科',
  '介入放射科',
  '超声科',
  '血液透析室',
  '医疗设备应急库',
  '产科',
  '妇科',
  '重症医学科',
  '麻醉手术科',
  '急诊科',
  '神经内科',
  '检验科'
];

export const CATEGORIES = [
  '全部分类',
  '医用成像器械',
  '医用诊察和监护器械',
  '呼吸、麻醉和急救器械',
  '有源手术器械',
  '临床检验器械',
  '妇产科、辅助生殖和避孕器械'
];
