import { MedicalEquipment } from './types';

export const INITIAL_EQUIPMENT: MedicalEquipment[] = [
  {
    id: '10159',
    categoryNo: '06',
    category: '医用成像器械',
    level1No: '02',
    level1Category: 'X射线计算机体层摄影设备(CT)',
    level2No: '01',
    level2Category: 'X射线计算机体层摄影设备(CT)',
    name: 'X射线计算机体层摄影设备',
    model: 'NeuViz 128',
    manufactureDate: '2020/6/18',
    enableDate: '2020/9/12',
    productValidity: '10',
    sn: 'N1281200421E',
    manufacturer: '沈阳东软医疗系统有限公司',
    calibration: 'Yes',
    calibrationType: '强检类',
    calibrationUnit: '广东省计量科学研究院 (省级)',
    lastCalibrationDate: '2025-08-20',
    nextCalibrationDate: '2026-08-25',
    calibrationCertificateNo: 'JL2025081901',
    department: '影像科',
    building: '1号楼 综合楼',
    floor: '-1',
    nursePhone: '',
    status: '正常运行',
    manager: '崔工程师',
    purchasePrice: 4500000,
    repairCount: 0,
    repairRecords: [],
    statusLogs: []
  },
  {
    id: '10171',
    categoryNo: '06',
    category: '医用成像器械',
    level1No: '01',
    level1Category: '诊断X射线机',
    level2No: '01',
    level2Category: '血管造影X射线机',
    name: 'X射线血管造影机',
    model: 'Arits zee Floor',
    manufactureDate: '2014/3/10',
    enableDate: '2014/5/1',
    productValidity: '10',
    sn: '100005',
    manufacturer: '西门子股份公司',
    calibration: 'Yes',
    calibrationType: '强检类',
    calibrationUnit: '深圳市计量质量检测研究院 (市级)',
    lastCalibrationDate: '2025-07-01',
    nextCalibrationDate: '2026-07-01',
    calibrationCertificateNo: 'JL2025070188',
    department: '介入放射科',
    building: '1号楼 综合楼',
    floor: '-1',
    nursePhone: '7991498',
    status: '正常运行',
    manager: '张工程师',
    purchasePrice: 3800000,
    repairCount: 1,
    repairRecords: [
      {
        id: 'REP-20260510-01',
        equipmentId: '10171',
        equipmentName: 'X射线血管造影机',
        equipmentSn: '100005',
        faultDate: '2026-05-10',
        repairType: '定期预防性保养',
        faultDescription: '球管热容量定标与C臂球管定位校验。',
        technician: '西门子原厂工程师',
        cost: 3500,
        partsReplaced: '球管滤尘风扇',
        resolution: '完成定位校验，热容量指标符合临床要求。',
        status: '已完成',
        completionDate: '2026-05-11'
      }
    ],
    statusLogs: []
  },
  {
    id: '10170',
    categoryNo: '06',
    category: '医用成像器械',
    level1No: '01',
    level1Category: '诊断X射线机',
    level2No: '01',
    level2Category: '血管造影X射线机',
    name: 'X射线血管造影机',
    model: 'AXIOM Artis U',
    manufactureDate: '2012/6/15',
    enableDate: '2012/8/1',
    productValidity: '10',
    sn: '11222',
    manufacturer: '上海西门子医疗器械有限公司',
    calibration: 'Yes',
    calibrationUnit: '市级',
    department: '介入放射科',
    building: '1号楼 综合楼',
    floor: '-1',
    nursePhone: '7991498',
    status: '维护保养中',
    manager: '张工程师',
    purchasePrice: 3200000,
    repairCount: 1,
    repairRecords: [
      {
        id: 'REP-20260802-01',
        equipmentId: '10170',
        equipmentName: 'X射线血管造影机',
        equipmentSn: '11222',
        faultDate: '2026-08-02',
        repairType: '定期预防性保养',
        faultDescription: '年度计量检测与管电压高压校准。',
        technician: '上海西门子维修团队',
        cost: 1200,
        resolution: '正在校准管电压及辐射剂量指标。',
        status: '处理中'
      }
    ],
    statusLogs: []
  },
  {
    id: '10163',
    categoryNo: '06',
    category: '医用成像器械',
    level1No: '01',
    level1Category: '诊断X射线机',
    level2No: '07',
    level2Category: '摄影X射线机',
    name: 'X线摄影系统',
    model: 'RAD SPEED M',
    enableDate: '2013/7/1',
    productValidity: '10',
    sn: '61C795',
    manufacturer: '北京岛津医疗器械有限公司',
    calibration: 'Yes',
    calibrationUnit: '市级',
    department: '影像科',
    building: '1号楼 综合楼',
    floor: '-1',
    nursePhone: '',
    status: '正常运行',
    manager: '王工程师',
    purchasePrice: 1200000,
    repairCount: 0,
    repairRecords: [],
    statusLogs: []
  },
  {
    id: '10154',
    categoryNo: '06',
    category: '医用成像器械',
    level1No: '07',
    level1Category: '超声影像诊断设备',
    level2No: '02',
    level2Category: '超声回波多普勒成像设备',
    name: '便携式彩色超声诊断系统',
    model: 'CX50',
    enableDate: '2021/1/6',
    productValidity: '10',
    sn: 'B3KB6Q',
    manufacturer: '飞利浦超声股份有限公司',
    calibration: 'Yes',
    calibrationUnit: '市级',
    department: '超声科',
    building: '1号楼 综合楼',
    floor: '3',
    nursePhone: '',
    status: '正常运行',
    manager: '刘医生',
    purchasePrice: 480000,
    repairCount: 0,
    repairRecords: [],
    statusLogs: []
  },
  {
    id: '10380',
    categoryNo: '06',
    category: '医用成像器械',
    level1No: '07',
    level1Category: '超声影像诊断设备',
    level2No: '02',
    level2Category: '超声回波多普勒成像设备',
    name: '便携式彩色多普勒超声诊断系统',
    model: 'PA12A',
    enableDate: '2023/1/9',
    productValidity: '',
    sn: '20PA12030002',
    manufacturer: '北京智影技术有限公司',
    calibration: 'Yes',
    calibrationUnit: '市级',
    department: '血液透析室',
    building: '1号楼 综合楼',
    floor: '6',
    nursePhone: '7991162',
    status: '正常运行',
    manager: '赵护士长',
    purchasePrice: 260000,
    repairCount: 0,
    repairRecords: [],
    statusLogs: []
  },
  {
    id: '10416',
    categoryNo: '06',
    category: '医用成像器械',
    level1No: '07',
    level1Category: '超声影像诊断设备',
    level2No: '02',
    level2Category: '超声回波多普勒成像设备',
    name: '便携式彩色多普勒超声诊断系统',
    model: 'PA12A',
    enableDate: '2022/12/28',
    productValidity: '',
    sn: '22PA12110006',
    manufacturer: '北京智影技术有限公司',
    calibration: 'Yes',
    calibrationUnit: '市级',
    department: '医疗设备应急库',
    building: '1号楼 综合楼',
    floor: '9',
    nursePhone: '7991237',
    status: '正常运行',
    manager: '设备科备用',
    purchasePrice: 260000,
    repairCount: 0,
    repairRecords: [],
    statusLogs: []
  },
  {
    id: '9912',
    categoryNo: '03',
    category: '医用诊察和监护器械',
    level1No: '04',
    level1Category: '监护设备',
    level2No: '01',
    level2Category: '病人监护设备',
    name: '便携式多参数监护仪',
    model: 'MEC-2000',
    enableDate: '',
    productValidity: '10',
    sn: 'EB-15004044',
    manufacturer: '深圳迈瑞生物医疗电子股份有限公司',
    calibration: 'Yes',
    calibrationUnit: '市级',
    department: '产科',
    building: '1号楼 综合楼',
    floor: '4',
    nursePhone: '7991318',
    status: '正常运行',
    manager: '陈护士',
    purchasePrice: 38000,
    repairCount: 0,
    repairRecords: [],
    statusLogs: []
  },
  {
    id: '9911',
    categoryNo: '03',
    category: '医用诊察和监护器械',
    level1No: '04',
    level1Category: '监护设备',
    level2No: '01',
    level2Category: '病人监护设备',
    name: '便携式多参数监护仪',
    model: 'MEC-2000',
    enableDate: '',
    productValidity: '10',
    sn: 'EB-15004067',
    manufacturer: '深圳迈瑞生物医疗电子股份有限公司',
    calibration: 'Yes',
    calibrationUnit: '市级',
    department: '妇科',
    building: '1号楼 综合楼',
    floor: '9',
    nursePhone: '7991089',
    status: '故障待修',
    manager: '林护士长',
    purchasePrice: 38000,
    repairCount: 1,
    repairRecords: [
      {
        id: 'REP-20260806-01',
        equipmentId: '9911',
        equipmentName: '便携式多参数监护仪',
        equipmentSn: 'EB-15004067',
        faultDate: '2026-08-06',
        repairType: '紧急故障维修',
        faultDescription: '屏幕显示雪花噪点，心电波形采集干扰严重。',
        technician: '迈瑞工程师',
        cost: 450,
        partsReplaced: '心电主板导联接口',
        resolution: '已提交工单派单，等待配件更换。',
        status: '处理中'
      }
    ],
    statusLogs: []
  },
  {
    id: '10077',
    categoryNo: '03',
    category: '医用诊察和监护器械',
    level1No: '04',
    level1Category: '监护设备',
    level2No: '01',
    level2Category: '病人监护设备',
    name: '病人监护仪',
    model: 'BeneView T5',
    enableDate: '2012/9/20',
    productValidity: '10',
    sn: 'CM-22122924',
    manufacturer: '深圳迈瑞生物医疗电子股份有限公司',
    calibration: 'Yes',
    calibrationUnit: '市级',
    department: '重症医学科',
    building: '1号楼 综合楼',
    floor: '7',
    nursePhone: '7991278',
    status: '正常运行',
    manager: 'ICU护理组',
    purchasePrice: 85000,
    repairCount: 0,
    repairRecords: [],
    statusLogs: []
  },
  {
    id: '10076',
    categoryNo: '03',
    category: '医用诊察和监护器械',
    level1No: '04',
    level1Category: '监护设备',
    level2No: '01',
    level2Category: '病人监护设备',
    name: '病人监护仪',
    model: 'BeneView T5',
    enableDate: '2012/9/20',
    productValidity: '10',
    sn: 'CM-22122925',
    manufacturer: '深圳迈瑞生物医疗电子股份有限公司',
    calibration: 'Yes',
    calibrationUnit: '市级',
    department: '重症医学科',
    building: '1号楼 综合楼',
    floor: '7',
    nursePhone: '7991278',
    status: '正常运行',
    manager: 'ICU护理组',
    purchasePrice: 85000,
    repairCount: 0,
    repairRecords: [],
    statusLogs: []
  },
  {
    id: '10075',
    categoryNo: '03',
    category: '医用诊察和监护器械',
    level1No: '04',
    level1Category: '监护设备',
    level2No: '01',
    level2Category: '病人监护设备',
    name: '病人监护仪',
    model: 'BeneView T5',
    enableDate: '2012/9/20',
    productValidity: '10',
    sn: 'CM-22122938',
    manufacturer: '深圳迈瑞生物医疗电子股份有限公司',
    calibration: 'Yes',
    calibrationUnit: '市级',
    department: '重症医学科',
    building: '1号楼 综合楼',
    floor: '7',
    nursePhone: '7991278',
    status: '故障待修',
    manager: 'ICU护理组',
    purchasePrice: 85000,
    repairCount: 1,
    repairRecords: [
      {
        id: 'REP-20260807-02',
        equipmentId: '10075',
        equipmentName: '病人监护仪',
        equipmentSn: 'CM-22122938',
        faultDate: '2026-08-07',
        repairType: '紧急故障维修',
        faultDescription: '无创血压NIBP充气泵超时报警，无法完成测压。',
        technician: '设备科崔工',
        cost: 320,
        partsReplaced: 'NIBP内部气泵马达',
        resolution: '已报修派单排查，拟更换气泵软管和马达。',
        status: '处理中'
      }
    ],
    statusLogs: []
  },
  {
    id: '10074',
    categoryNo: '03',
    category: '医用诊察和监护器械',
    level1No: '04',
    level1Category: '监护设备',
    level2No: '01',
    level2Category: '病人监护设备',
    name: '病人监护仪',
    model: 'BeneView T5',
    enableDate: '2012/9/20',
    productValidity: '10',
    sn: 'CM-22122939',
    manufacturer: '深圳迈瑞生物医疗电子股份有限公司',
    calibration: 'Yes',
    calibrationUnit: '市级',
    department: '重症医学科',
    building: '1号楼 综合楼',
    floor: '7',
    nursePhone: '7991278',
    status: '正常运行',
    manager: 'ICU护理组',
    purchasePrice: 85000,
    repairCount: 0,
    repairRecords: [],
    statusLogs: []
  },
  {
    id: '10073',
    categoryNo: '03',
    category: '医用诊察和监护器械',
    level1No: '04',
    level1Category: '监护设备',
    level2No: '01',
    level2Category: '病人监护设备',
    name: '病人监护仪',
    model: 'BeneView T5',
    enableDate: '2012/9/20',
    productValidity: '10',
    sn: 'CM-22122967',
    manufacturer: '深圳迈瑞生物医疗电子股份有限公司',
    calibration: 'Yes',
    calibrationUnit: '市级',
    department: '重症医学科',
    building: '1号楼 综合楼',
    floor: '7',
    nursePhone: '7991278',
    status: '正常运行',
    manager: 'ICU护理组',
    purchasePrice: 85000,
    repairCount: 0,
    repairRecords: [],
    statusLogs: []
  },
  {
    id: '10072',
    categoryNo: '03',
    category: '医用诊察和监护器械',
    level1No: '04',
    level1Category: '监护设备',
    level2No: '01',
    level2Category: '病人监护设备',
    name: '病人监护仪',
    model: 'BeneView T5',
    enableDate: '2012/9/20',
    productValidity: '10',
    sn: 'CM-22122970',
    manufacturer: '深圳迈瑞生物医疗电子股份有限公司',
    calibration: 'Yes',
    calibrationUnit: '市级',
    department: '重症医学科',
    building: '1号楼 综合楼',
    floor: '7',
    nursePhone: '7991278',
    status: '正常运行',
    manager: 'ICU护理组',
    purchasePrice: 85000,
    repairCount: 0,
    repairRecords: [],
    statusLogs: []
  },
  {
    id: '10071',
    categoryNo: '03',
    category: '医用诊察和监护器械',
    level1No: '04',
    level1Category: '监护设备',
    level2No: '01',
    level2Category: '病人监护设备',
    name: '病人监护仪',
    model: 'BeneView T5',
    enableDate: '2012/9/20',
    productValidity: '10',
    sn: 'CM-23123378',
    manufacturer: '深圳迈瑞生物医疗电子股份有限公司',
    calibration: 'Yes',
    calibrationUnit: '市级',
    department: '重症医学科',
    building: '1号楼 综合楼',
    floor: '7',
    nursePhone: '7991278',
    status: '正常运行',
    manager: 'ICU护理组',
    purchasePrice: 85000,
    repairCount: 0,
    repairRecords: [],
    statusLogs: []
  },
  {
    id: '10070',
    categoryNo: '03',
    category: '医用诊察和监护器械',
    level1No: '04',
    level1Category: '监护设备',
    level2No: '01',
    level2Category: '病人监护设备',
    name: '病人监护仪',
    model: 'BeneView T5',
    enableDate: '2012/9/20',
    productValidity: '10',
    sn: 'CM-23123390',
    manufacturer: '深圳迈瑞生物医疗电子股份有限公司',
    calibration: 'Yes',
    calibrationUnit: '市级',
    department: '重症医学科',
    building: '1号楼 综合楼',
    floor: '7',
    nursePhone: '7991278',
    status: '正常运行',
    manager: 'ICU护理组',
    purchasePrice: 85000,
    repairCount: 0,
    repairRecords: [],
    statusLogs: []
  },
  {
    id: '10069',
    categoryNo: '03',
    category: '医用诊察和监护器械',
    level1No: '04',
    level1Category: '监护设备',
    level2No: '01',
    level2Category: '病人监护设备',
    name: '病人监护仪',
    model: 'BeneView T5',
    enableDate: '2012/9/20',
    productValidity: '10',
    sn: 'CM-23123529',
    manufacturer: '深圳迈瑞生物医疗电子股份有限公司',
    calibration: 'Yes',
    calibrationUnit: '市级',
    department: '重症医学科',
    building: '1号楼 综合楼',
    floor: '7',
    nursePhone: '7991278',
    status: '维护保养中',
    manager: 'ICU护理组',
    purchasePrice: 85000,
    repairCount: 1,
    repairRecords: [
      {
        id: 'REP-20260804-03',
        equipmentId: '10069',
        equipmentName: '病人监护仪',
        equipmentSn: 'CM-23123529',
        faultDate: '2026-08-04',
        repairType: '定期预防性保养',
        faultDescription: '例行安全及电源接地电阻质控检测。',
        technician: '医学装备科崔工',
        cost: 0,
        resolution: '质控检测符合标准，待复核归还。',
        status: '处理中'
      }
    ],
    statusLogs: []
  },
  {
    id: '10068',
    categoryNo: '03',
    category: '医用诊察和监护器械',
    level1No: '04',
    level1Category: '监护设备',
    level2No: '01',
    level2Category: '病人监护设备',
    name: '病人监护仪',
    model: 'BeneView T5',
    enableDate: '2012/9/20',
    productValidity: '10',
    sn: 'CM-23123535',
    manufacturer: '深圳迈瑞生物医疗电子股份有限公司',
    calibration: 'Yes',
    calibrationUnit: '市级',
    department: '重症医学科',
    building: '1号楼 综合楼',
    floor: '7',
    nursePhone: '7991278',
    status: '正常运行',
    manager: 'ICU护理组',
    purchasePrice: 85000,
    repairCount: 0,
    repairRecords: [],
    statusLogs: []
  },
  {
    id: '10078',
    categoryNo: '03',
    category: '医用诊察和监护器械',
    level1No: '04',
    level1Category: '监护设备',
    level2No: '01',
    level2Category: '病人监护设备',
    name: '病人监护仪',
    model: 'BeneView T5',
    enableDate: '',
    productValidity: '10',
    sn: 'CM-25125208',
    manufacturer: '深圳迈瑞生物医疗电子股份有限公司',
    calibration: 'Yes',
    calibrationUnit: '市级',
    department: '介入放射科',
    building: '1号楼 综合楼',
    floor: '-1',
    nursePhone: '7991498',
    status: '正常运行',
    manager: '介入科护士站',
    purchasePrice: 85000,
    repairCount: 0,
    repairRecords: [],
    statusLogs: []
  },
  {
    id: '10067',
    categoryNo: '03',
    category: '医用诊察和监护器械',
    level1No: '04',
    level1Category: '监护设备',
    level2No: '01',
    level2Category: '病人监护设备',
    name: '病人监护仪',
    model: 'BeneView T8',
    enableDate: '',
    productValidity: '10',
    sn: 'CF-0C107923',
    manufacturer: '深圳迈瑞生物医疗电子股份有限公司',
    calibration: 'Yes',
    calibrationUnit: '市级',
    department: '麻醉手术科',
    building: '1号楼 综合楼',
    floor: '8',
    nursePhone: '7991103',
    status: '正常运行',
    manager: '手术室麻醉组',
    purchasePrice: 120000,
    repairCount: 0,
    repairRecords: [],
    statusLogs: []
  },
  {
    id: '10066',
    categoryNo: '03',
    category: '医用诊察和监护器械',
    level1No: '04',
    level1Category: '监护设备',
    level2No: '01',
    level2Category: '病人监护设备',
    name: '病人监护仪',
    model: 'BeneView T8',
    enableDate: '',
    productValidity: '10',
    sn: 'CF-0C107924',
    manufacturer: '深圳迈瑞生物医疗电子股份有限公司',
    calibration: 'Yes',
    calibrationUnit: '市级',
    department: '麻醉手术科',
    building: '1号楼 综合楼',
    floor: '8',
    nursePhone: '7991103',
    status: '正常运行',
    manager: '手术室麻醉组',
    purchasePrice: 120000,
    repairCount: 0,
    repairRecords: [],
    statusLogs: []
  },
  {
    id: '10065',
    categoryNo: '03',
    category: '医用诊察和监护器械',
    level1No: '04',
    level1Category: '监护设备',
    level2No: '01',
    level2Category: '病人监护设备',
    name: '病人监护仪',
    model: 'BeneView T8',
    enableDate: '',
    productValidity: '10',
    sn: 'CF-41121435',
    manufacturer: '深圳迈瑞生物医疗电子股份有限公司',
    calibration: 'Yes',
    calibrationUnit: '市级',
    department: '麻醉手术科',
    building: '1号楼 综合楼',
    floor: '8',
    nursePhone: '7991103',
    status: '正常运行',
    manager: '手术室麻醉组',
    purchasePrice: 120000,
    repairCount: 0,
    repairRecords: [],
    statusLogs: []
  },
  {
    id: '10064',
    categoryNo: '03',
    category: '医用诊察和监护器械',
    level1No: '04',
    level1Category: '监护设备',
    level2No: '01',
    level2Category: '病人监护设备',
    name: '病人监护仪',
    model: 'BeneView T8',
    enableDate: '',
    productValidity: '10',
    sn: 'CF-41121436',
    manufacturer: '深圳迈瑞生物医疗电子股份有限公司',
    calibration: 'Yes',
    calibrationUnit: '市级',
    department: '麻醉手术科',
    building: '1号楼 综合楼',
    floor: '8',
    nursePhone: '7991103',
    status: '停用/报废',
    manager: '手术室麻醉组',
    purchasePrice: 120000,
    repairCount: 1,
    repairRecords: [
      {
        id: 'REP-20251120-09',
        equipmentId: '10064',
        equipmentName: '病人监护仪',
        equipmentSn: 'CF-41121436',
        faultDate: '2025-11-20',
        repairType: '紧急故障维修',
        faultDescription: '主板供电烧毁，屏幕无法开启。',
        technician: '迈瑞工程师',
        cost: 0,
        resolution: '已超安全使用年限，主板停产无原厂配件，技术鉴定后封存停用。',
        status: '已完成',
        completionDate: '2025-11-22'
      }
    ],
    statusLogs: []
  },
  {
    id: '10185',
    categoryNo: '03',
    category: '医用诊察和监护器械',
    level1No: '01',
    level1Category: '心电诊断设备',
    level2No: '01',
    level2Category: '十二导联心电图机',
    name: '十二导联同步心电图机',
    model: 'BeneHeart R12',
    enableDate: '2023/5/10',
    manufactureDate: '2023/4/15',
    productValidity: '8',
    sn: 'ECG-20230415-08',
    manufacturer: '深圳迈瑞生物医疗电子股份有限公司',
    calibration: 'Yes',
    calibrationType: '强检(国家免费)',
    catalogueCode: 'QJ-01',
    feePolicy: 'free_national',
    calibrationUnit: '市计量质量检测研究院 (法定强检)',
    lastCalibrationDate: '2025-05-15',
    nextCalibrationDate: '2026-05-15',
    calibrationCertificateNo: 'QJ-ECG-2025-0588',
    department: '重症医学科',
    building: '1号楼 综合楼',
    floor: '7',
    nursePhone: '7991278',
    status: '正常运行',
    manager: '心电主管技师',
    purchasePrice: 42000,
    repairCount: 0,
    repairRecords: [],
    statusLogs: []
  },
  {
    id: '10186',
    categoryNo: '03',
    category: '医用诊察和监护器械',
    level1No: '02',
    level1Category: '脑电诊断设备',
    level2No: '01',
    level2Category: '数字脑电地形图仪',
    name: '数字视频脑电图仪',
    model: 'EEG-1200C',
    enableDate: '2022/8/18',
    manufactureDate: '2022/6/20',
    productValidity: '10',
    sn: 'EEG-202206-89',
    manufacturer: '日本光电工业株式会社',
    calibration: 'Yes',
    calibrationType: '强检(国家免费)',
    catalogueCode: 'QJ-02',
    feePolicy: 'free_national',
    calibrationUnit: '广东省计量科学研究院 (法定强检)',
    lastCalibrationDate: '2025-08-10',
    nextCalibrationDate: '2026-08-10',
    calibrationCertificateNo: 'QJ-EEG-2025-0192',
    department: '神经内科',
    building: '1号楼 综合楼',
    floor: '5',
    nursePhone: '7991120',
    status: '正常运行',
    manager: '神经内科脑电室',
    purchasePrice: 180000,
    repairCount: 0,
    repairRecords: [],
    statusLogs: []
  },
  {
    id: '10195',
    categoryNo: '03',
    category: '医用诊察和监护器械',
    level1No: '03',
    level1Category: '生理参数测量',
    level2No: '01',
    level2Category: '台式水银/电子血压计',
    name: '医用精密台式血压计',
    model: 'HBP-1300',
    enableDate: '2024/1/10',
    manufactureDate: '2023/12/01',
    productValidity: '5',
    sn: 'BP-20231201-99',
    manufacturer: '欧姆龙(大连)有限公司',
    calibration: 'Yes',
    calibrationType: '强检(国家免费)',
    catalogueCode: 'QJ-07',
    feePolicy: 'free_national',
    calibrationUnit: '县/区级法定计量检定所',
    lastCalibrationDate: '2025-11-20',
    nextCalibrationDate: '2026-05-20',
    calibrationCertificateNo: 'QJ-BP-2025-9921',
    department: '急诊科',
    building: '1号楼 综合楼',
    floor: '1',
    nursePhone: '7991120',
    status: '正常运行',
    manager: '急诊分诊台',
    purchasePrice: 2800,
    repairCount: 0,
    repairRecords: [],
    statusLogs: []
  },
  {
    id: '10188',
    categoryNo: '08',
    category: '呼吸、麻醉和急救器械',
    level1No: '03',
    level1Category: '输液与推注设备',
    level2No: '01',
    level2Category: '医用双通道注射泵',
    name: '双通道微量注射泵',
    model: 'BeneFusion SP5',
    enableDate: '2023/3/15',
    manufactureDate: '2023/2/10',
    productValidity: '8',
    sn: 'SP5-202302-009',
    manufacturer: '深圳迈瑞生物医疗电子股份有限公司',
    calibration: 'Yes',
    calibrationType: '定期校准(自费)',
    catalogueCode: 'JZ-01',
    feePolicy: 'paid_hospital',
    calibrationUnit: '华南国家计量测试中心 (校准部)',
    lastCalibrationDate: '2025-04-10',
    nextCalibrationDate: '2026-04-10',
    calibrationCertificateNo: 'JZ-CAL-2025-4421',
    department: '重症医学科',
    building: '1号楼 综合楼',
    floor: '7',
    nursePhone: '7991278',
    status: '正常运行',
    manager: 'ICU护理组',
    purchasePrice: 16000,
    repairCount: 0,
    repairRecords: [],
    statusLogs: []
  },
  {
    id: '10189',
    categoryNo: '01',
    category: '有源手术器械',
    level1No: '01',
    level1Category: '高频手术设备',
    level2No: '01',
    level2Category: '高频电刀发生器',
    name: '高频电外科能量平台 (电刀)',
    model: 'Force FX-8C',
    enableDate: '2021/6/18',
    manufactureDate: '2021/4/20',
    productValidity: '10',
    sn: 'VALLEYLAB-8812',
    manufacturer: '美敦力柯惠医疗器材有限公司',
    calibration: 'Yes',
    calibrationType: '定期校准(自费)',
    catalogueCode: 'JZ-03',
    feePolicy: 'paid_hospital',
    calibrationUnit: '省医疗器械质量监督检验所 (校准室)',
    lastCalibrationDate: '2025-06-25',
    nextCalibrationDate: '2026-06-25',
    calibrationCertificateNo: 'JZ-CAL-2025-1033',
    department: '麻醉手术科',
    building: '1号楼 综合楼',
    floor: '8',
    nursePhone: '7991103',
    status: '正常运行',
    manager: '手术室器械组',
    purchasePrice: 280000,
    repairCount: 0,
    repairRecords: [],
    statusLogs: []
  },
  {
    id: '10176',
    categoryNo: '08',
    category: '呼吸、麻醉和急救器械',
    level1No: '02',
    level1Category: '心脏除颤设备',
    level2No: '01',
    level2Category: '双相波除颤监护仪',
    name: '双相波除颤起搏监护仪',
    model: 'BeneHeart D3',
    enableDate: '2022/10/12',
    manufactureDate: '2022/9/01',
    productValidity: '8',
    sn: 'D3-202209-441',
    manufacturer: '深圳迈瑞生物医疗电子股份有限公司',
    calibration: 'Yes',
    calibrationType: '定期校准(自费)',
    catalogueCode: 'JZ-04',
    feePolicy: 'paid_hospital',
    calibrationUnit: '深圳市计量质量检测研究院 (校准中心)',
    lastCalibrationDate: '2025-10-15',
    nextCalibrationDate: '2026-10-15',
    calibrationCertificateNo: 'JZ-CAL-2025-8890',
    department: '急诊科',
    building: '1号楼 综合楼',
    floor: '1',
    nursePhone: '7991120',
    status: '正常运行',
    manager: '王护士长 / 急诊抢救室',
    purchasePrice: 75000,
    repairCount: 0,
    repairRecords: [],
    statusLogs: []
  },
  {
    id: '10196',
    categoryNo: '08',
    category: '呼吸、麻醉和急救器械',
    level1No: '01',
    level1Category: '医用呼吸机',
    level2No: '02',
    level2Category: '急救转运呼吸机',
    name: '电动涡轮急救转运呼吸机',
    model: 'SV300',
    enableDate: '2023/4/20',
    manufactureDate: '2023/3/10',
    productValidity: '8',
    sn: 'SV300-202303-118',
    manufacturer: '深圳迈瑞生物医疗电子股份有限公司',
    calibration: 'Yes',
    calibrationType: '定期校准(自费)',
    catalogueCode: 'JZ-05',
    feePolicy: 'paid_hospital',
    calibrationUnit: '广东省计量科学研究院 (气体流量校准室)',
    lastCalibrationDate: '2025-09-10',
    nextCalibrationDate: '2026-09-10',
    calibrationCertificateNo: 'JZ-CAL-2025-9923',
    department: '急诊科',
    building: '1号楼 综合楼',
    floor: '1',
    nursePhone: '7991120',
    status: '正常运行',
    manager: '王护士长 / 急诊抢救室',
    purchasePrice: 180000,
    repairCount: 0,
    repairRecords: [],
    statusLogs: []
  },
  {
    id: '10197',
    categoryNo: '03',
    category: '医用诊察和监护器械',
    level1No: '01',
    level1Category: '心电诊断设备',
    level2No: '01',
    level2Category: '数字式十二导联心电图机',
    name: '十二导联自动分析心电图机',
    model: 'BeneHeart R12',
    enableDate: '2022/8/15',
    manufactureDate: '2022/7/01',
    productValidity: '8',
    sn: 'R12-202207-092',
    manufacturer: '深圳迈瑞生物医疗电子股份有限公司',
    calibration: 'Yes',
    calibrationType: '强检(国家免费)',
    catalogueCode: 'QJ-01',
    feePolicy: 'free_national',
    calibrationUnit: '日照市计量测试所 (法定强检)',
    lastCalibrationDate: '2025-08-15',
    nextCalibrationDate: '2026-08-15',
    calibrationCertificateNo: 'QJ-ECG-2025-1102',
    department: '急诊科',
    building: '1号楼 综合楼',
    floor: '1',
    nursePhone: '7991120',
    status: '正常运行',
    manager: '王护士长 / 急诊抢救室',
    purchasePrice: 42000,
    repairCount: 0,
    repairRecords: [],
    statusLogs: []
  },
  {
    id: '10198',
    categoryNo: '08',
    category: '呼吸、麻醉和急救器械',
    level1No: '04',
    level1Category: '心肺复苏及辅助设备',
    level2No: '01',
    level2Category: '便携式全自动胸外按压机',
    name: '便携式电动心肺复苏机',
    model: 'E6 AutoCPR',
    enableDate: '2023/11/10',
    manufactureDate: '2023/10/05',
    productValidity: '8',
    sn: 'CPR-202310-004',
    manufacturer: '苏州心锐医疗器械有限公司',
    calibration: 'Yes',
    calibrationType: '定期校准(自费)',
    catalogueCode: 'JZ-08',
    feePolicy: 'paid_hospital',
    calibrationUnit: '深圳市计量质量检测研究院 (校准中心)',
    lastCalibrationDate: '2025-11-12',
    nextCalibrationDate: '2026-11-12',
    calibrationCertificateNo: 'JZ-CAL-2025-8812',
    department: '急诊科',
    building: '1号楼 综合楼',
    floor: '1',
    nursePhone: '7991120',
    status: '故障待修',
    lastFaultReason: '锂电池无法充电，外接AC电源插座松动报错',
    manager: '王护士长 / 急诊抢救室',
    purchasePrice: 125000,
    repairCount: 1,
    repairRecords: [
      {
        id: 'REP-20260814-05',
        equipmentId: '10198',
        equipmentName: '便携式电动心肺复苏机',
        equipmentSn: 'CPR-202310-004',
        faultDate: '2026-08-14',
        repairType: '紧急故障维修',
        faultDescription: '锂电池无法充电，外接AC电源插座松动报错',
        technician: '设备科崔工',
        cost: 0,
        resolution: '已派单至医学工程科，准备更换电源板和专用电池。',
        status: '处理中'
      }
    ],
    statusLogs: []
  },
  {
    id: '10199',
    categoryNo: '08',
    category: '呼吸、麻醉和急救器械',
    level1No: '05',
    level1Category: '洗胃设备',
    level2No: '01',
    level2Category: '自动洗胃机',
    name: '全自动自动控制洗胃机',
    model: 'GX-III',
    enableDate: '2021/5/12',
    manufactureDate: '2021/4/10',
    productValidity: '8',
    sn: 'GX3-202104-033',
    manufacturer: '上海康人医学仪器设备有限公司',
    calibration: 'No',
    calibrationType: '免计量',
    department: '急诊科',
    building: '1号楼 综合楼',
    floor: '1',
    nursePhone: '7991120',
    status: '维护保养中',
    manager: '王护士长 / 急诊抢救室',
    purchasePrice: 28000,
    repairCount: 1,
    repairRecords: [
      {
        id: 'REP-20260812-02',
        equipmentId: '10199',
        equipmentName: '全自动自动控制洗胃机',
        equipmentSn: 'GX3-202104-033',
        faultDate: '2026-08-12',
        repairType: '定期预防性保养',
        faultDescription: '例行管路压力传感器校准与电磁阀密封保养。',
        technician: '医学装备科孙志强',
        cost: 150,
        resolution: '电磁阀密封圈更换完毕，正在执行冲洗压力验证。',
        status: '处理中'
      }
    ],
    statusLogs: []
  },
  {
    id: '10175',
    categoryNo: '08',
    category: '呼吸、麻醉和急救器械',
    level1No: '01',
    level1Category: '医用呼吸机',
    level2No: '01',
    level2Category: '重症治疗呼吸机',
    name: '重症有创呼吸机',
    model: 'PB 840',
    enableDate: '2020/5/20',
    manufactureDate: '2020/3/15',
    productValidity: '10',
    sn: 'PB840-2020-09',
    manufacturer: '美敦力呼吸与监测事业部',
    calibration: 'Yes',
    calibrationType: '定期校准(自费)',
    catalogueCode: 'JZ-05',
    feePolicy: 'paid_hospital',
    calibrationUnit: '广东省计量科学研究院 (气体流量校准室)',
    lastCalibrationDate: '2025-05-18',
    nextCalibrationDate: '2026-05-18',
    calibrationCertificateNo: 'JZ-CAL-2025-5512',
    department: '重症医学科',
    building: '1号楼 综合楼',
    floor: '7',
    nursePhone: '7991278',
    status: '正常运行',
    manager: 'ICU呼吸治疗师',
    purchasePrice: 320000,
    repairCount: 0,
    repairRecords: [],
    statusLogs: []
  },
  {
    id: '10190',
    categoryNo: '22',
    category: '临床检验器械',
    level1No: '05',
    level1Category: '离心机设备',
    level2No: '01',
    level2Category: '台式高速冷冻离心机',
    name: '台式高速冷冻离心机',
    model: 'Micro 21R',
    enableDate: '2022/11/05',
    manufactureDate: '2022/9/10',
    productValidity: '10',
    sn: 'THERMO-202209-12',
    manufacturer: '赛默飞世尔科技(中国)有限公司',
    calibration: 'Yes',
    calibrationType: '定期校准(自费)',
    catalogueCode: 'JZ-07',
    feePolicy: 'paid_hospital',
    calibrationUnit: '市计量质量检测所',
    lastCalibrationDate: '2025-11-01',
    nextCalibrationDate: '2026-11-01',
    calibrationCertificateNo: 'JZ-CAL-2025-7731',
    department: '检验科',
    building: '1号楼 综合楼',
    floor: '2',
    nursePhone: '7991115',
    status: '正常运行',
    manager: '生化检验组',
    purchasePrice: 68000,
    repairCount: 0,
    repairRecords: [],
    statusLogs: []
  },
  {
    id: '10192',
    categoryNo: '15',
    category: '妇产科、辅助生殖和避孕器械',
    level1No: '01',
    level1Category: '产科检查病床',
    level2No: '01',
    level2Category: '多功能液压产床',
    name: '多功能一体化液压分娩产床',
    model: 'Optima LDR',
    enableDate: '2023/1/15',
    manufactureDate: '2022/12/01',
    productValidity: '12',
    sn: 'LDR-202212-05',
    manufacturer: '芬兰美迪兰医疗器械有限公司',
    calibration: 'No',
    calibrationType: '免计量',
    department: '产科',
    building: '1号楼 综合楼',
    floor: '4',
    nursePhone: '7991318',
    status: '正常运行',
    manager: '产房护士长',
    purchasePrice: 150000,
    repairCount: 0,
    repairRecords: [],
    statusLogs: []
  }
];

export const DEPARTMENTS = [
  '全院科室',
  '影像科',
  '介入放射科',
  '超声科',
  '血液透析室',
  '医疗设备应急库',
  '产科',
  '妇科',
  '重症医学科',
  '麻醉手术科',
  '急诊科',
  '神经内科',
  '检验科'
];

export const CATEGORIES = [
  '全部分类',
  '医用成像器械',
  '医用诊察和监护器械',
  '呼吸、麻醉和急救器械',
  '有源手术器械',
  '临床检验器械',
  '妇产科、辅助生殖和避孕器械'
];
